#!/bin/bash

SHADERC=~/bin/shaderc
HOME="$(cd -P "$(dirname "${BASH_SOURCE[0]}")"; pwd)"

function fakePart() {
	if [ -f $1_mtl.h -a ! -f $1_$3.h ]
	then
		sed "s/$1_$2_mtl/$1_$2_$3/" <$1_mtl.h >$1_$3.h
	fi
}

function compilePart() {
	case $1 in
		vertex) EXT=vs;;
		fragment) EXT=fs;;
		compute) EXT=cs;;
	esac

	if [ $2 == "instancing" ]
	then
		PREFIX=${EXT}i

	else
		PREFIX=${EXT}
	fi

	if [ "$(uname)" == "Darwin" ]
	then
		${SHADERC} -f $2.${EXT} -o ${PREFIX}_mtl.h -i ${HOME}/include --type $1 --platform osx -p metal --bin2c ${PREFIX}_$3_mtl
		fakePart ${PREFIX} $3 glsl
		fakePart ${PREFIX} $3 essl
		fakePart ${PREFIX} $3 spv
		fakePart ${PREFIX} $3 dx9
		fakePart ${PREFIX} $3 dx11

	else
		${SHADERC} -f $2.${EXT} -o ${PREFIX}_mtl.h -i ${HOME}/include --type $1 --platform linux -p 400 --bin2c ${PREFIX}_$3_glsl
		${SHADERC} -f $2.${EXT} -o ${PREFIX}_mtl.h -i ${HOME}/include --type $1 --platform linux -p 300_es --bin2c ${PREFIX}_$3_essl
		${SHADERC} -f $2.${EXT} -o ${PREFIX}_mtl.h -i ${HOME}/include --type $1 --platform linux -p spirv --bin2c ${PREFIX}_$3_spv
	fi
}

function compileShader() {
	cd ${HOME}/$1

	if [ -f shader.vs ]
	then
		compilePart vertex shader $1
	fi

	if [ -f shader.fs ]
	then
		compilePart fragment shader $1
	fi

	if [ -f instancing.vs ]
	then
		compilePart vertex instancing $1
	fi

	cd ${HOME}

	cat $1/vs_glsl.h $1/vs_essl.h $1/vs_spv.h $1/vs_dx9.h $1/vs_dx11.h $1/vs_mtl.h >$1shader.h
	echo "extern const uint8_t* vs_$1_pssl;" >>$1shader.h
	echo "extern const uint32_t vs_$1_pssl_size;" >>$1shader.h

	cat $1/fs_glsl.h $1/fs_essl.h $1/fs_spv.h $1/fs_dx9.h $1/fs_dx11.h $1/fs_mtl.h >>$1shader.h
	echo "extern const uint8_t* fs_$1_pssl;" >>$1shader.h
	echo "extern const uint32_t fs_$1_pssl_size;" >>$1shader.h

	if [ -f $1/vsi_mtl.h ]
	then
		cat $1/vsi_glsl.h $1/vsi_essl.h $1/vsi_spv.h $1/vsi_dx9.h $1/vsi_dx11.h $1/vsi_mtl.h >>$1shader.h
		echo "extern const uint8_t* vsi_$1_pssl;" >>$1shader.h
		echo "extern const uint32_t vsi_$1_pssl_size;" >>$1shader.h
	fi
}

compileShader background
compileShader skybox
compileShader fixed
compileShader colored
compileShader textured
compileShader blendmapped
