//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2024 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.



#pragma once


//
//	Include files
//

#include <algorithm>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include "OtException.h"
#include "OtIdentifier.h"
#include "OtInternal.h"
#include "OtObject.h"
#include "OtSource.h"
#include "OtStatement.h"
#include "OtSymbol.h"


//
//	Forward declarations
//

class OtMemberReferenceClass;
using OtMemberReference = OtObjectPointer<OtMemberReferenceClass>;

class OtStackReferenceClass;
using OtStackReference = OtObjectPointer<OtStackReferenceClass>;


//
//	OtByteCode
//

class OtByteCodeClass;
using OtByteCode = OtObjectPointer<OtByteCodeClass>;

class OtByteCodeClass : public OtInternalClass {
public:
	// possible opcodes
	typedef enum {
		// opcodes generated by the compiler
		statementOpcode,
		pushOpcode,
		pushNullOpcode,
		popOpcode,
		popCountOpcode,
		dupOpcode,
		swapOpcode,
		moveOpcode,
		jumpOpcode,
		jumpTrueOpcode,
		jumpFalseOpcode,
		memberOpcode,
		superOpcode,
		methodOpcode,
		exitOpcode,
		pushTryOpcode,
		popTryOpcode,

		// opcodes generated by the optimizer
		pushStackOpcode,
		pushObjectMemberOpcode,
		pushMemberOpcode,
		assignStackOpcode,
		assignMemberOpcode
	} OtOpcode;

	// constructors
	OtByteCodeClass() = default;
	OtByteCodeClass(OtSource s, OtID i) : source(s), id(i) {}

	// add compiler opcodes
	inline void statement() { emitOpcode(statementOpcode); }
	inline void push(OtObject value) { emitOpcode(pushOpcode); emitConstant(value); }
	inline void pushNull() { emitOpcode(pushNullOpcode); }
	inline void pop() { emitOpcode(popOpcode); }
	inline void pop(size_t count) { emitOpcode(popCountOpcode); emitNumber(count); }
	inline void dup() { emitOpcode(dupOpcode); }
	inline void swap() { emitOpcode(swapOpcode); }
	inline void move(size_t count) { emitOpcode(moveOpcode); emitNumber(count); }
	inline size_t jump(size_t offset) { emitOpcode(jumpOpcode); return emitJump(offset); }
	inline size_t jumpTrue(size_t offset) { emitOpcode(jumpTrueOpcode); return emitJump(offset); }
	inline size_t jumpFalse(size_t offset) { emitOpcode(jumpFalseOpcode); return emitJump(offset); }
	inline void member(OtID id) { emitOpcode(memberOpcode); emitID(id); }
	inline void method(OtID id, size_t count) { emitOpcode(methodOpcode); emitID(id); emitNumber(count); }
	inline void super(OtID id) { emitOpcode(superOpcode); emitID(id); }
	inline void exit() { emitOpcode(exitOpcode); }
	inline size_t pushTry() { emitOpcode(pushTryOpcode); return emitJump(0); }
	inline void pushTry(size_t offset) { emitOpcode(pushTryOpcode); emitJump(offset); }
	inline void popTry() { emitOpcode(popTryOpcode); }

	// patch jump offset
	inline void patchJump(size_t jump) { jumps[jump] = bytecode.size(); }

	// add optimizer opcodes
	inline void pushStack(size_t slot) { emitOpcode(pushStackOpcode); emitNumber(slot); }
	inline void pushObjectMember(OtObject object, OtID member) { emitOpcode(pushObjectMemberOpcode); emitConstant(object); emitID(member); }
	inline void pushMember(OtID member) { emitOpcode(pushMemberOpcode); emitID(member); }
	inline void assignStack(size_t slot) { emitOpcode(assignStackOpcode); emitNumber(slot); }
	inline void assignMember(OtObject object, OtID member) { emitOpcode(assignMemberOpcode); emitConstant(object); emitID(member); }

	// get current code size
	inline size_t size() { return bytecode.size(); }

	// get opcode
	inline uint8_t getOpcode(size_t& pc) {
		return bytecode[pc++];
	}

	// get variable length number
	inline size_t getNumber(size_t& pc) {
		size_t result = 0;
		size_t shift = 0;

		while (true) {
			auto byte = bytecode[pc++];
			result |= size_t(byte & 0x7f) << shift;

			if (!(byte & 0x80)) {
				break;
			}

			shift += 7;
		}

		return result;
	}

	// get an identifier
	inline OtID getID(size_t& pc) { return (OtID) getNumber(pc); }

	// disassemble the bytecode
	std::string disassemble();

	// copy from other bytecode
	void copyOpcode(OtByteCode bytecode, size_t pc);

	// add statement reference
	inline void addStatement(size_t sourceStart, size_t sourceEnd, size_t opcodeStart, size_t opcodeEnd) {
		statements.emplace_back(sourceStart, sourceEnd, opcodeStart, opcodeEnd);
	}

	// add a new symbol located on the heap
	inline void addSymbol(const OtSymbol& symbol) {
		symbols.emplace_back(symbol);
	}

	// get code parts
	inline std::string getModule() { return source->getModule(); }
	inline OtSource& getSource() { return source; }
	inline OtID getID() { return id; }
	inline uint8_t* getCode() { return bytecode.data(); }
	inline OtObject& getConstant(size_t index) { return constants[index]; }
	inline std::vector<size_t>& getJumps() { return jumps; }
	inline size_t getJump(size_t jump) { return jumps[jump]; }
	inline std::vector<OtStatement>& getStatements() { return statements; }
	inline std::vector<OtSymbol>& getSymbols() { return symbols; }

	// bytecode introspection
	size_t getOpcodeSize(size_t pc);

	bool isPush(size_t pc, OtObject& object);
	bool isPushStackReference(size_t pc, OtStackReference& reference);
	bool isPushMemberReference(size_t pc, OtMemberReference& reference);
	bool isSwap(size_t pc);
	bool isMember(size_t pc, OtID& member);
	bool isMethodDeref(size_t pc);
	bool isMethodAssign(size_t pc);
	bool isAnyJump(size_t pc, size_t& offset);

	size_t getStatementStart(size_t pc);
	size_t getStatementEnd(size_t pc);
	size_t getLineNumber(size_t pc);
	std::string getStatementSourceCode(size_t pc);

	std::vector<std::string> getUsedSymbolNames(size_t pc);

	// get type definition
	static OtType getMeta();

private:
	// emit parts to bytecode
	inline void emitOpcode(OtOpcode opcode) {
		bytecode.emplace_back((uint8_t) opcode);
	}

	inline void emitConstant(OtObject constant) {
		auto index = constants.size();
		constants.emplace_back(constant);
		emitNumber(index);
	}

	inline size_t emitJump(size_t offset) {
		auto jump = jumps.size();
		jumps.emplace_back(offset);
		emitNumber(jump);
		return jump;
	}

	inline void emitID(OtID id) { emitNumber((size_t) id); }

	inline void emitNumber(size_t number) {
		while (number > 0x7f) {
			bytecode.emplace_back(((uint8_t)(number & 0x7f)) | 0x80);
			number >>= 7;
		}

		bytecode.emplace_back((uint8_t) number);
	}

	// properties
	OtSource source;
	OtID id;
	std::vector<uint8_t> bytecode;
	std::vector<OtObject> constants;
	std::vector<size_t> jumps;
	std::vector<OtStatement> statements;
	std::vector<OtSymbol> symbols;

	// internal method identifiers used by compiler
	OtID assignID = OtIdentifier::create("__assign__");
	OtID dereferenceID = OtIdentifier::create("__deref__");
};
