//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2024 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.



#pragma once


//
//	Include files
//

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

#include "OtException.h"
#include "OtInternal.h"
#include "OtObject.h"
#include "OtSource.h"


//
//	Forward declarations
//

class OtMemberReferenceClass;
using OtMemberReference = OtObjectPointer<OtMemberReferenceClass>;

class OtStackReferenceClass;
using OtStackReference = OtObjectPointer<OtStackReferenceClass>;


//
//	OtByteCode
//

class OtByteCodeClass;
using OtByteCode = OtObjectPointer<OtByteCodeClass>;

class OtByteCodeClass : public OtInternalClass {
public:
	// possible opcodes
	typedef enum {
		// opcodes generated by compiler
		markOpcode,
		pushOpcode,
		popOpcode,
		popCountOpcode,
		dupOpcode,
		swapOpcode,
		moveOpcode,
		reserveOpcode,
		pushSymbolOpcode,
		popSymbolsOpcode,
		jumpOpcode,
		jumpTrueOpcode,
		jumpFalseOpcode,
		memberOpcode,
		superOpcode,
		methodOpcode,
		exitOpcode,
		pushTryOpcode,
		popTryOpcode,

		// opcodes generated by optimizer
		pushStackOpcode,
		pushObjectMemberOpcode,
		pushMemberOpcode,
		assignStackOpcode,
		assignMemberOpcode
	} OtOpcode;

	// constructors
	OtByteCodeClass() = default;
	OtByteCodeClass(OtSource s, const std::string& n) : source(s), name(n) {}

	// add compiler instructions to code
	inline void mark(size_t mark) { emitOpcode(markOpcode); emitMark(mark); }
	inline void push(OtObject value) { emitOpcode(pushOpcode); emitConstant(value); }
	inline void pop() { emitOpcode(popOpcode); }
	inline void pop(size_t count) { emitOpcode(popCountOpcode); emitNumber(count); }
	inline void dup() { emitOpcode(dupOpcode); }
	inline void swap() { emitOpcode(swapOpcode); }
	inline void move(size_t count) { emitOpcode(moveOpcode); emitNumber(count); }
	inline void reserve() { emitOpcode(reserveOpcode); }
	inline void pushSymbol(size_t symbol) { emitOpcode(pushSymbolOpcode); emitNumber(symbol); }
	inline void pushSymbol(const char* name) { emitOpcode(pushSymbolOpcode); emitSymbol(name); }
	inline void pushSymbol(const std::string_view name) { emitOpcode(pushSymbolOpcode); emitSymbol(name); }
	inline void pushSymbol(const std::string& name) { emitOpcode(pushSymbolOpcode); emitSymbol(name); }
	inline void popSymbols(size_t count) { emitOpcode(popSymbolsOpcode); emitNumber(count); }
	inline size_t jump(size_t offset) { emitOpcode(jumpOpcode); return emitOffset(offset); }
	inline size_t jumpTrue(size_t offset) { emitOpcode(jumpTrueOpcode); return emitOffset(offset); }
	inline size_t jumpFalse(size_t offset) { emitOpcode(jumpFalseOpcode); return emitOffset(offset); }
	inline void member(size_t symbol) { emitOpcode(memberOpcode); emitNumber(symbol); }
	inline void member(const char* name) { emitOpcode(memberOpcode); emitSymbol(name); }
	inline void member(const std::string_view name) { emitOpcode(memberOpcode); emitSymbol(name); }
	inline void member(const std::string& name) { emitOpcode(memberOpcode); emitSymbol(name); }
	inline void method(size_t symbol, size_t count) { emitOpcode(methodOpcode); emitNumber(symbol); emitNumber(count); }
	inline void method(const char* name, size_t count) { emitOpcode(methodOpcode); emitSymbol(name); emitNumber(count); }
	inline void method(const std::string_view name, size_t count) { emitOpcode(methodOpcode); emitSymbol(name); emitNumber(count); }
	inline void method(const std::string& name, size_t count) { emitOpcode(methodOpcode); emitSymbol(name); emitNumber(count); }
	inline void super(size_t symbol) { emitOpcode(superOpcode); emitNumber(symbol); }
	inline void super(const char* name) { emitOpcode(superOpcode); emitSymbol(name); }
	inline void super(const std::string_view name) { emitOpcode(superOpcode); emitSymbol(name); }
	inline void super(const std::string& name) { emitOpcode(superOpcode); emitSymbol(name); }
	inline void exit() { emitOpcode(exitOpcode); }
	inline size_t pushTry() { emitOpcode(pushTryOpcode); return emitOffset(0); }
	inline void pushTry(size_t offset) { emitOpcode(pushTryOpcode); emitOffset(offset); }
	inline void popTry() { emitOpcode(popTryOpcode); }

	// patch jump offset
	inline void patchJump(size_t offset) { offsets[offset] = bytecode.size(); }

	// add optimizer instructions to code
	inline void pushStack(size_t slot) { emitOpcode(pushStackOpcode); emitNumber(slot); }
	inline void pushObjectMember(OtObject object, size_t member) { emitOpcode(pushObjectMemberOpcode); emitConstant(object); emitNumber(member); }
	inline void pushMember(const size_t member) { emitOpcode(pushMemberOpcode); emitNumber(member); }
	inline void assignStack(size_t slot) { emitOpcode(assignStackOpcode); emitNumber(slot); }
	inline void assignMember(OtObject object, size_t member) { emitOpcode(assignMemberOpcode); emitConstant(object); emitNumber(member); }

	// get current code size
	inline size_t size() { return bytecode.size(); }

	// get opcode
	inline uint8_t getOpcode(size_t& pc) {
		return bytecode[pc++];
	}

	// get variable length number
	inline size_t getNumber(size_t& pc) {
		size_t result = 0;
		size_t digit = 0;

		while (bytecode[pc] & 0x80) {
			size_t value = bytecode[pc++] & 0x7f;
			result |= value << (7 * digit++);
		}

		return result | (size_t) bytecode[pc++] << (7 * digit);
	}

	// disassemble the bytecode
	std::string disassemble();

	// copy instruction from other bytecode
	void copyInstruction(OtByteCode bytecode, size_t pc);

	// get code parts
	inline OtSource getSource() { return source; }
	inline std::string& getName() { return name; }
	inline uint8_t* getCode() { return bytecode.data(); }
	inline OtObject& getConstant(size_t index) { return constants[index]; }
	inline std::vector<size_t>& getOffsets() { return offsets; }
	inline size_t getOffset(size_t index) { return offsets[index]; }
	inline size_t getMark(size_t index) { return marks[index]; }
	inline size_t getNextMark(size_t index) { return index + 1 < marks.size() ? marks[index + 1] : source->size(); }

	// bytecode introspection
	size_t getInstructionSize(size_t pc);
	bool isPush(size_t pc, OtObject& object);
	bool isPushStackReference(size_t pc, OtStackReference& reference);
	bool isPushMemberReference(size_t pc, OtMemberReference& reference);
	bool isSwap(size_t pc);
	bool isMember(size_t pc, size_t& member);
	bool isMethodDeref(size_t pc);
	bool isMethodAssign(size_t pc);
	bool isAnyJump(size_t pc, size_t& offset);

	// get type definition
	static OtType getMeta();

private:
	// emit parts to bytecode
	inline void emitOpcode(OtOpcode opcode) {
		bytecode.emplace_back((uint8_t) opcode);
	}

	inline void emitConstant(OtObject constant) {
		auto index = constants.size();
		constants.emplace_back(constant);
		emitNumber(index);
	}

	inline void emitSymbol(const char* name) {
		emitNumber(OtSymbol::create(name));
	}

	inline void emitSymbol(const std::string_view name) {
		emitNumber(OtSymbol::create(name));
	}

	inline void emitSymbol(const std::string& name) {
		emitNumber(OtSymbol::create(name));
	}

	inline void emitMark(size_t mark) {
		auto index = marks.size();
		marks.emplace_back(mark);
		emitNumber(index);
	}

	inline size_t emitOffset(size_t offset) {
		auto index = offsets.size();
		offsets.emplace_back(offset);
		emitNumber(index);
		return index;
	}

	inline void emitNumber(size_t number) {
		while (number > 127) {
			bytecode.emplace_back(((uint8_t)(number & 127)) | 128);
			number >>= 7;
		}

		bytecode.emplace_back((uint8_t) number);
	}

	OtSource source;
	std::string name;
	std::vector<uint8_t> bytecode;
	std::vector<OtObject> constants;
	std::vector<size_t> marks;
	std::vector<size_t> offsets;
};
