#!/bin/sh
#
#	ObjectTalk Scripting Language
#	Copyright (c) 2020-2022 Johan A. Goossens. All rights reserved.
#
#	This work is licensed under the terms of the MIT license.
#	For a copy, see <https://opensource.org/licenses/MIT>.

docker container rm ot-ubuntu; true
docker image rm ot-ubuntu; true
