#!/bin/sh
#
#	ObjectTalk Scripting Language
#	Copyright (c) 1993-2024 Johan A. Goossens. All rights reserved.
#
#	This work is licensed under the terms of the MIT license.
#	For a copy, see <https://opensource.org/licenses/MIT>.

docker build -t ot-ubuntu .
docker run --interactive --tty --name ot-ubuntu --volume $(cd ../..; pwd):/ot ot-ubuntu bash
docker container rm ot-ubuntu
