//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.

#version 450 core

layout(local_size_x=16, local_size_y=16, local_size_z=1) in;

layout(set=0, binding=0) uniform sampler2D inTexture;
layout(set=1, binding=0, rgba8) uniform writeonly image2D outTexture;

layout(std140, set=2, binding=0) uniform UBO {
	vec2 offset;
	float brightness;
	float transparency;
};

void main() {
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(outTexture);

	if (coord.x >= size.x || coord.y >= size.y) {
		return;
	}

	vec2 uv = (vec2(coord) + 0.5) / vec2(size);

	vec4 color;
	color  = texture(inTexture, uv - offset * 4.0) * 0.05;
	color += texture(inTexture, uv - offset * 3.0) * 0.09;
	color += texture(inTexture, uv - offset * 2.0) * 0.12;
	color += texture(inTexture, uv - offset * 1.0) * 0.15;
	color += texture(inTexture, uv + offset * 0.0) * 0.16;
	color += texture(inTexture, uv + offset * 1.0) * 0.15;
	color += texture(inTexture, uv + offset * 2.0) * 0.12;
	color += texture(inTexture, uv + offset * 3.0) * 0.09;
	color += texture(inTexture, uv + offset * 4.0) * 0.05;

	imageStore(outTexture, coord, color * vec4(brightness, brightness, brightness, transparency));
}
