//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2025 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do NOT edit this file as it is automatically created by the build system.
//


//
//	Include files
//

#include <cstddef>
#include <cstdint>


//
//	Shader references
//

extern const uint32_t OtCubeMapCrossFrag[];
extern const size_t OtCubeMapCrossFragSize;
extern const uint32_t OtCubeMapCrossVert[];
extern const size_t OtCubeMapCrossVertSize;
extern const uint32_t OtHdrReprojectFrag[];
extern const size_t OtHdrReprojectFragSize;
extern const uint32_t OtDeferredVert[];
extern const size_t OtDeferredVertSize;
extern const uint32_t OtDeferredAnimatedVert[];
extern const size_t OtDeferredAnimatedVertSize;
extern const uint32_t OtDeferredInstancingVert[];
extern const size_t OtDeferredInstancingVertSize;
extern const uint32_t OtDeferredLightingFrag[];
extern const size_t OtDeferredLightingFragSize;
extern const uint32_t OtDeferredPbrFrag[];
extern const size_t OtDeferredPbrFragSize;
extern const uint32_t OtBloomDownSampleComp[];
extern const size_t OtBloomDownSampleCompSize;
extern const uint32_t OtBloomUpSampleComp[];
extern const size_t OtBloomUpSampleCompSize;
extern const uint32_t OtBlurComp[];
extern const size_t OtBlurCompSize;
extern const uint32_t OtContrastSaturationBrightnessComp[];
extern const size_t OtContrastSaturationBrightnessCompSize;
extern const uint32_t OtFogComp[];
extern const size_t OtFogCompSize;
extern const uint32_t OtFxaaComp[];
extern const size_t OtFxaaCompSize;
extern const uint32_t OtGaussianComp[];
extern const size_t OtGaussianCompSize;
extern const uint32_t OtIslandizerComp[];
extern const size_t OtIslandizerCompSize;
extern const uint32_t OtNeedleComp[];
extern const size_t OtNeedleCompSize;
extern const uint32_t OtNormalMapperComp[];
extern const size_t OtNormalMapperCompSize;
extern const uint32_t OtPixelateComp[];
extern const size_t OtPixelateCompSize;
extern const uint32_t OtPostProcessingComp[];
extern const size_t OtPostProcessingCompSize;
extern const uint32_t OtPosterizeComp[];
extern const size_t OtPosterizeCompSize;
extern const uint32_t OtRgbaAdjustComp[];
extern const size_t OtRgbaAdjustCompSize;
extern const uint32_t OtRgbaCurveComp[];
extern const size_t OtRgbaCurveCompSize;
extern const uint32_t OtSeamlessTileComp[];
extern const size_t OtSeamlessTileCompSize;
extern const uint32_t OtSharpenComp[];
extern const size_t OtSharpenCompSize;
extern const uint32_t OtForwardVert[];
extern const size_t OtForwardVertSize;
extern const uint32_t OtForwardInstancingVert[];
extern const size_t OtForwardInstancingVertSize;
extern const uint32_t OtForwardPbrFrag[];
extern const size_t OtForwardPbrFragSize;
extern const uint32_t OtCheckerBoardComp[];
extern const size_t OtCheckerBoardCompSize;
extern const uint32_t OtColorWheelComp[];
extern const size_t OtColorWheelCompSize;
extern const uint32_t OtFbmComp[];
extern const size_t OtFbmCompSize;
extern const uint32_t OtFloodComp[];
extern const size_t OtFloodCompSize;
extern const uint32_t OtTileableFbmComp[];
extern const size_t OtTileableFbmCompSize;
extern const uint32_t OtGodRaysComp[];
extern const size_t OtGodRaysCompSize;
extern const uint32_t OtOcclusionOpaqueFrag[];
extern const size_t OtOcclusionOpaqueFragSize;
extern const uint32_t OtOcclusionTransparentFrag[];
extern const size_t OtOcclusionTransparentFragSize;
extern const uint32_t OtRenderLightComp[];
extern const size_t OtRenderLightCompSize;
extern const uint32_t OtGrassFrag[];
extern const size_t OtGrassFragSize;
extern const size_t OtGrassVertSize;
extern const uint32_t OtGrassVert[];
extern const uint32_t OtSimpleGrassVert[];
extern const size_t OtSimpleGrassVertSize;
extern const uint32_t OtGridFrag[];
extern const size_t OtGridFragSize;
extern const uint32_t OtGridVert[];
extern const size_t OtGridVertSize;
extern const uint32_t OtOutlineFrag[];
extern const size_t OtOutlineFragSize;
extern const uint32_t OtSelectOpaqueFrag[];
extern const size_t OtSelectOpaqueFragSize;
extern const uint32_t OtSelectTransparentFrag[];
extern const size_t OtSelectTransparentFragSize;
extern const uint32_t OtBrdfLutComp[];
extern const size_t OtBrdfLutCompSize;
extern const uint32_t OtIblEnvironmentMapFrag[];
extern const size_t OtIblEnvironmentMapFragSize;
extern const uint32_t OtIblIrradianceMapFrag[];
extern const size_t OtIblIrradianceMapFragSize;
extern const uint32_t OtFullScreenVert[];
extern const size_t OtFullScreenVertSize;
extern const uint32_t OtSimpleVert[];
extern const size_t OtSimpleVertSize;
extern const uint32_t OtSimpleAnimatedVert[];
extern const size_t OtSimpleAnimatedVertSize;
extern const uint32_t OtSimpleInstancingVert[];
extern const size_t OtSimpleInstancingVertSize;
extern const uint32_t OtParticlesFrag[];
extern const size_t OtParticlesFragSize;
extern const uint32_t OtParticlesVert[];
extern const size_t OtParticlesVertSize;
extern const uint32_t OtPickingOpaqueFrag[];
extern const size_t OtPickingOpaqueFragSize;
extern const uint32_t OtPickingTransparentFrag[];
extern const size_t OtPickingTransparentFragSize;
extern const uint32_t OtPointLightsFrag[];
extern const size_t OtPointLightsFragSize;
extern const uint32_t OtPointLightsVert[];
extern const size_t OtPointLightsVertSize;
extern const uint32_t OtCanvasFrag[];
extern const size_t OtCanvasFragSize;
extern const uint32_t OtCanvasVert[];
extern const size_t OtCanvasVertSize;
extern const uint32_t OtCompositingFrag[];
extern const size_t OtCompositingFragSize;
extern const uint32_t OtMeshPreviewFrag[];
extern const size_t OtMeshPreviewFragSize;
extern const uint32_t OtMeshPreviewVert[];
extern const size_t OtMeshPreviewVertSize;
extern const uint32_t OtOscilloscopeFrag[];
extern const size_t OtOscilloscopeFragSize;
extern const uint32_t OtOscilloscopeVert[];
extern const size_t OtOscilloscopeVertSize;
extern const uint32_t OtShadowOpaqueFrag[];
extern const size_t OtShadowOpaqueFragSize;
extern const uint32_t OtShadowTransparentFrag[];
extern const size_t OtShadowTransparentFragSize;
extern const uint32_t OtSkyFrag[];
extern const size_t OtSkyFragSize;
extern const uint32_t OtSkyVert[];
extern const size_t OtSkyVertSize;
extern const uint32_t OtSkyBoxFrag[];
extern const size_t OtSkyBoxFragSize;
extern const uint32_t OtSimpleTerrainVert[];
extern const size_t OtSimpleTerrainVertSize;
extern const uint32_t OtTerrainFrag[];
extern const size_t OtTerrainFragSize;
extern const uint32_t OtTerrainVert[];
extern const size_t OtTerrainVertSize;
extern const uint32_t OtWaterFrag[];
extern const size_t OtWaterFragSize;
extern const uint32_t OtWaterVert[];
extern const size_t OtWaterVertSize;
