//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtAdsr
//

class OtAdsr : public OtFaust {
protected:
	float fButton0;
	int iVec0[2];
	float fHslider0;
	int iRec1[2];
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fHslider1;
	float fHslider2;
	double fConst2;
	float fHslider3;
	double fRec0[2];
	
 public:
	OtAdsr() {
	}
	
	OtAdsr(const OtAdsr&) = default;
	
	virtual ~OtAdsr() = default;
	
	OtAdsr& operator=(const OtAdsr&) = default;
	
	void metadata(Meta* m) override { 
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Envelope");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtAdsr -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("envelopes.lib/adsre:author", "Julius O. Smith III");
		m->declare("envelopes.lib/adsre:licence", "STK-4.3");
		m->declare("envelopes.lib/author", "GRAME");
		m->declare("envelopes.lib/copyright", "GRAME");
		m->declare("envelopes.lib/license", "LGPL with exception");
		m->declare("envelopes.lib/name", "Faust Envelope Library");
		m->declare("envelopes.lib/version", "1.3.0");
		m->declare("filename", "OtAdsr.dsp");
		m->declare("id", "adsr");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "ADSR");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	int getNumInputs() override {
		return 0;
	}
	int getNumOutputs() override {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 0.001 * fConst0;
		fConst2 = 1.0 / fConst0;
	}
	
	virtual void instanceResetUserInterface() {
		fButton0 = static_cast<float>(0.0);
		fHslider0 = static_cast<float>(1.0);
		fHslider1 = static_cast<float>(1.0);
		fHslider2 = static_cast<float>(1.0);
		fHslider3 = static_cast<float>(0.8);
	}
	
	virtual void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			iRec1[l1] = 0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec0[l2] = 0.0;
		}
	}
	
	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
	
	virtual OtAdsr* clone() {
		return new OtAdsr(*this);
	}
	
	int getSampleRate() override {
		return fSampleRate;
	}
	
	void buildUserInterface(UI* ui_interface) override {
		ui_interface->openVerticalBox("ADSR");
		ui_interface->declare(&fButton0, "0", "");
		ui_interface->addButton("Gate", &fButton0);
		ui_interface->declare(&fHslider1, "1", "");
		ui_interface->declare(&fHslider1, "format", "%.2fms");
		ui_interface->addHorizontalSlider("Attack", &fHslider1, float(1.0), float(0.0), float(1e+01), float(0.1));
		ui_interface->declare(&fHslider2, "2", "");
		ui_interface->declare(&fHslider2, "format", "%.2fms");
		ui_interface->addHorizontalSlider("Decay", &fHslider2, float(1.0), float(0.0), float(1e+01), float(0.1));
		ui_interface->declare(&fHslider3, "3", "");
		ui_interface->declare(&fHslider3, "format", "%.2f%%");
		ui_interface->addHorizontalSlider("Sustain", &fHslider3, float(0.8), float(0.0), float(1.0), float(1.0));
		ui_interface->declare(&fHslider0, "4", "");
		ui_interface->declare(&fHslider0, "format", "%.2fms");
		ui_interface->addHorizontalSlider("Release", &fHslider0, float(1.0), float(0.0), float(1e+01), float(0.1));
		ui_interface->closeBox();
	}
	
	void compute(int count, [[maybe_unused]] float** inputs, float** outputs) override {
		float* output0 = outputs[0];
		int iSlow0 = static_cast<double>(fButton0) > 0.0;
		double fSlow1 = 0.001 * static_cast<double>(fHslider0);
		double fSlow2 = static_cast<double>(fHslider1);
		int iSlow3 = static_cast<int>(fConst1 * fSlow2);
		double fSlow4 = 0.001 * static_cast<double>(fHslider2);
		double fSlow5 = 0.001 * fSlow2;
		double fSlow6 = static_cast<double>(iSlow0);
		double fSlow7 = static_cast<double>(fHslider3) * fSlow6;
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iVec0[0] = iSlow0;
			iRec1[0] = iSlow0 * (iRec1[1] + 1);
			int iTemp0 = iSlow0 - iVec0[1];
			int iTemp1 = (iRec1[0] < iSlow3) | (iTemp0 * (iTemp0 > 0));
			double fTemp2 = 0.1447178002894356 * ((iSlow0) ? ((iTemp1) ? fSlow5 : fSlow4) : fSlow1);
			int iTemp3 = std::fabs(fTemp2) < 2.220446049250313e-16;
			double fTemp4 = ((iTemp3) ? 0.0 : std::exp(-(fConst2 / ((iTemp3) ? 1.0 : fTemp2))));
			fRec0[0] = (1.0 - fTemp4) * ((iSlow0) ? ((iTemp1) ? fSlow6 : fSlow7) : 0.0) + fTemp4 * fRec0[1];
			output0[i0] = static_cast<float>(fRec0[0]);
			iVec0[1] = iVec0[0];
			iRec1[1] = iRec1[0];
			fRec0[1] = fRec0[0];
		}
	}

	struct Parameters {
		float gate;
		float attack;
		float decay;
		float sustain;
		float release;
	};

	inline void setParameters(Parameters& parameters) {
		fButton0 = parameters.gate;
		fHslider1 = parameters.attack;
		fHslider2 = parameters.decay;
		fHslider3 = parameters.sustain;
		fHslider0 = parameters.release;
	}

	inline void getParameters(Parameters& parameters) {
		parameters.gate = fButton0;
		parameters.attack = fHslider1;
		parameters.decay = fHslider2;
		parameters.sustain = fHslider3;
		parameters.release = fHslider0;
	}

	inline void setGate(float value) { fButton0 = value; }
	inline void setAttack(float value) { fHslider1 = value; }
	inline void setDecay(float value) { fHslider2 = value; }
	inline void setSustain(float value) { fHslider3 = value; }
	inline void setRelease(float value) { fHslider0 = value; }

	inline float getGate() { return fButton0; }
	inline float getAttack() { return fHslider1; }
	inline float getDecay() { return fHslider2; }
	inline float getSustain() { return fHslider3; }
	inline float getRelease() { return fHslider0; }
};
