//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtAdsr
//

class OtAdsr : public OtFaust {
protected:
	int iVec0[2];
	float fVslider0;
	int iRec1[2];
	int fSampleRate;
	double fConst0;
	float fVslider1;
	float fVslider2;
	double fConst1;
	float fVslider3;
	double fRec0[2];
	
 public:
	OtAdsr() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Envelope");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtAdsr -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("envelopes.lib/adsre:author", "Julius O. Smith III");
		m->declare("envelopes.lib/adsre:licence", "STK-4.3");
		m->declare("envelopes.lib/author", "GRAME");
		m->declare("envelopes.lib/copyright", "GRAME");
		m->declare("envelopes.lib/license", "LGPL with exception");
		m->declare("envelopes.lib/name", "Faust Envelope Library");
		m->declare("envelopes.lib/version", "1.3.0");
		m->declare("filename", "OtAdsr.dsp");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "ADSR");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 1.0 / fConst0;
	}
	
	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(0.03);
		fVslider1 = static_cast<float>(0.01);
		fVslider2 = static_cast<float>(0.05);
		fVslider3 = static_cast<float>(0.8);
	}
	
	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			iRec1[l1] = 0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec0[l2] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
	
	inline void buildUserInterface(UI* ui_interface) {
		ui_interface->openHorizontalBox("ADSR");
		ui_interface->declare(&fVslider1, "1", "");
		ui_interface->declare(&fVslider1, "format", "%.3fs");
		ui_interface->declare(&fVslider1, "style", "knob");
		ui_interface->addVerticalSlider("Attack", &fVslider1, float(0.01), float(0.0), float(1e+01), float(0.1));
		ui_interface->declare(&fVslider2, "2", "");
		ui_interface->declare(&fVslider2, "format", "%.3fs");
		ui_interface->declare(&fVslider2, "style", "knob");
		ui_interface->addVerticalSlider("Decay", &fVslider2, float(0.05), float(0.0), float(1e+01), float(0.1));
		ui_interface->declare(&fVslider3, "3", "");
		ui_interface->declare(&fVslider3, "format", "%.2f");
		ui_interface->declare(&fVslider3, "style", "knob");
		ui_interface->addVerticalSlider("Sustain", &fVslider3, float(0.8), float(0.0), float(1.0), float(1.0));
		ui_interface->declare(&fVslider0, "4", "");
		ui_interface->declare(&fVslider0, "format", "%.3fs");
		ui_interface->declare(&fVslider0, "style", "knob");
		ui_interface->addVerticalSlider("Release", &fVslider0, float(0.03), float(0.0), float(1e+01), float(0.1));
		ui_interface->closeBox();
	}
	
	inline void compute(int count, float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = static_cast<double>(fVslider0);
		double fSlow1 = static_cast<double>(fVslider1);
		int iSlow2 = static_cast<int>(fConst0 * fSlow1);
		double fSlow3 = static_cast<double>(fVslider2);
		double fSlow4 = static_cast<double>(fVslider3);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			int iTemp0 = static_cast<double>(input0[i0]) > 0.0;
			iVec0[0] = iTemp0;
			iRec1[0] = iTemp0 * (iRec1[1] + 1);
			int iTemp1 = iTemp0 - iVec0[1];
			int iTemp2 = (iRec1[0] < iSlow2) | (iTemp1 * (iTemp1 > 0));
			double fTemp3 = 0.1447178002894356 * ((iTemp0) ? ((iTemp2) ? fSlow1 : fSlow3) : fSlow0);
			int iTemp4 = std::fabs(fTemp3) < 2.220446049250313e-16;
			double fTemp5 = ((iTemp4) ? 0.0 : std::exp(-(fConst1 / ((iTemp4) ? 1.0 : fTemp3))));
			double fTemp6 = static_cast<double>(iTemp0);
			fRec0[0] = (1.0 - fTemp5) * ((iTemp0) ? ((iTemp2) ? fTemp6 : fSlow4 * fTemp6) : 0.0) + fTemp5 * fRec0[1];
			output0[i0] = static_cast<float>(fRec0[0]);
			iVec0[1] = iVec0[0];
			iRec1[1] = iRec1[0];
			fRec0[1] = fRec0[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("ADSR");
		changed |= editAttack();
		ImGui::SameLine();
		changed |= editDecay();
		ImGui::SameLine();
		changed |= editSustain();
		ImGui::SameLine();
		changed |= editRelease();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float attack = 0.01f;
		float decay = 0.05f;
		float sustain = 0.8f;
		float release = 0.03f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider1 = parameters.attack;
		fVslider2 = parameters.decay;
		fVslider3 = parameters.sustain;
		fVslider0 = parameters.release;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.attack = fVslider1;
		parameters.decay = fVslider2;
		parameters.sustain = fVslider3;
		parameters.release = fVslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("attack", &fVslider1, 0.01f);
		callback("decay", &fVslider2, 0.05f);
		callback("sustain", &fVslider3, 0.8f);
		callback("release", &fVslider0, 0.03f);
	}

	inline bool editAttack() { return OtUi::knob("Attack", &fVslider1, 0.0f, 10.0f, "%.3fs"); }
	inline bool editDecay() { return OtUi::knob("Decay", &fVslider2, 0.0f, 10.0f, "%.3fs"); }
	inline bool editSustain() { return OtUi::knob("Sustain", &fVslider3, 0.0f, 1.0f, "%.2f"); }
	inline bool editRelease() { return OtUi::knob("Release", &fVslider0, 0.0f, 10.0f, "%.3fs"); }

	inline void setAttack(float value) { fVslider1 = value; }
	inline void setDecay(float value) { fVslider2 = value; }
	inline void setSustain(float value) { fVslider3 = value; }
	inline void setRelease(float value) { fVslider0 = value; }

	inline float getAttack() { return fVslider1; }
	inline float getDecay() { return fVslider2; }
	inline float getSustain() { return fVslider3; }
	inline float getRelease() { return fVslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
