//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated by source/build.py
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"


//
//  OtAutoWah
//

static double OtAutoWah_faustpower2_f(double value) {
	return value * value;
}

class OtAutoWah : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fVslider0;
	double fConst2;
	double fRec0[2];
	double fConst3;
	double fConst4;
	double fRec3[2];
	double fRec2[2];
	double fConst5;
	double fConst6;
	double fRec4[2];
	double fRec5[2];
	double fRec1[3];

public:
	OtAutoWah() {
		init(OtAudioSettings::sampleRate);
	}

	inline void metadata(Meta* m) {
		m->declare("analyzers.lib/name", "Faust Analyzer Library");
		m->declare("analyzers.lib/version", "1.3.0");
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Modulation");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtAutoWah -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtAutoWah.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/tf2:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "WahWah");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Routing Library");
		m->declare("signals.lib/version", "1.6.0");
		m->declare("vaeffects.lib/name", "Faust Virtual Analog Filter Effect Library");
		m->declare("vaeffects.lib/version", "1.5.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 44.1 / fConst0;
		fConst2 = 1.0 - fConst1;
		fConst3 = std::exp(-(1e+01 / fConst0));
		fConst4 = 1.0 - fConst3;
		fConst5 = 1413.7166941154069 / fConst0;
		fConst6 = 2827.4333882308138 / fConst0;
	}

	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(0.4);
	}

	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fRec0[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec3[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec2[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec4[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec5[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 3; l5 = l5 + 1) {
			fRec1[l5] = 0.0;
		}
	}

	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	inline int getSampleRate() {
		return fSampleRate;
	}

	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = fConst1 * static_cast<double>(fVslider0);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			fRec0[0] = fSlow0 + fConst2 * fRec0[1];
			double fTemp0 = static_cast<double>(input0[i0]);
			double fTemp1 = std::fabs(fTemp0);
			fRec3[0] = std::max<double>(fTemp1, fConst3 * fRec3[1] + fConst4 * fTemp1);
			fRec2[0] = 0.0001000000000000001 * std::pow(4.0, fRec3[0]) + 0.999 * fRec2[1];
			double fTemp2 = std::pow(2.0, 2.3 * fRec3[0]);
			double fTemp3 = 1.0 - fConst5 * (fTemp2 / std::pow(2.0, 2.0 * (1.0 - fRec3[0]) + 1.0));
			fRec4[0] = 0.999 * fRec4[1] - 0.0020000000000000018 * fTemp3 * std::cos(fConst6 * fTemp2);
			fRec5[0] = 0.0010000000000000009 * OtAutoWah_faustpower2_f(fTemp3) + 0.999 * fRec5[1];
			fRec1[0] = fTemp0 * fRec2[0] - (fRec4[0] * fRec1[1] + fRec5[0] * fRec1[2]);
			output0[i0] = static_cast<float>(fRec0[0] * (fRec1[0] - fRec1[1]) + fTemp0 * (1.0 - fRec0[0]));
			fRec0[1] = fRec0[0];
			fRec3[1] = fRec3[0];
			fRec2[1] = fRec2[0];
			fRec4[1] = fRec4[0];
			fRec5[1] = fRec5[0];
			fRec1[2] = fRec1[1];
			fRec1[1] = fRec1[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtAudioUi::knobWidth();
		auto knobHeight = OtAudioUi::knobHeight();
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Auto Wah");
		changed |= editLevel();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float level = 0.4f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider0 = parameters.level;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.level = fVslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("level", &fVslider0, 0.4f);
	}

	inline bool editLevel() { return OtAudioUi::knob("Level", &fVslider0, 0.0f, 1.0f, "%.2f", false); }

	inline void setLevel(float value) { fVslider0 = value; }

	inline float getLevel() { return fVslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
