//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2025 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtChorus
//

class OtChorusSIG0 {
private:	
	int iRec1[2];

public:	
	int getNumInputsOtChorusSIG0() {
		return 0;
	}
	int getNumOutputsOtChorusSIG0() {
		return 1;
	}
	
	void instanceInitOtChorusSIG0([[maybe_unused]] int sample_rate) {
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			iRec1[l2] = 0;
		}
	}
	
	void fillOtChorusSIG0(int count, double* table) {
		for (int i1 = 0; i1 < count; i1 = i1 + 1) {
			iRec1[0] = iRec1[1] + 1;
			table[i1] = std::sin(9.587379924285257e-05 * static_cast<double>(iRec1[0] + -1));
			iRec1[1] = iRec1[0];
		}
	}
};

static OtChorusSIG0* newOtChorusSIG0() { return (OtChorusSIG0*)new OtChorusSIG0(); }
static void deleteOtChorusSIG0(OtChorusSIG0* dsp) { delete dsp; }

static double ftbl0OtChorusSIG0[65536];

class OtChorus : public OtFaust {
private:
	int IOTA0;
	double fVec0[65536];
	float fHslider0;
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fHslider1;
	float fHslider2;
	double fConst2;
	float fHslider3;
	double fRec0[2];
	double fVec1[65536];
	
 public:
	OtChorus() {
	}
	
	OtChorus(const OtChorus&) = default;
	
	virtual ~OtChorus() = default;
	
	OtChorus& operator=(const OtChorus&) = default;
	
	void metadata(Meta* m) override { 
		m->declare("author", "Albert Graef");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtChorus -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "chorus.dsp");
		m->declare("math.lib/author", "GRAME");
		m->declare("math.lib/copyright", "GRAME");
		m->declare("math.lib/deprecated", "This library is deprecated and is not maintained anymore. It will be removed in August 2017.");
		m->declare("math.lib/license", "LGPL with exception");
		m->declare("math.lib/name", "Math Library");
		m->declare("math.lib/version", "1.0");
		m->declare("music.lib/author", "GRAME");
		m->declare("music.lib/copyright", "GRAME");
		m->declare("music.lib/deprecated", "This library is deprecated and is not maintained anymore. It will be removed in August 2017.");
		m->declare("music.lib/license", "LGPL with exception");
		m->declare("music.lib/name", "Music Library");
		m->declare("music.lib/version", "1.0");
		m->declare("name", "chorus -- a simple chorus effect");
		m->declare("version", "1.0");
	}

	int getNumInputs() override {
		return 2;
	}
	int getNumOutputs() override {
		return 2;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
		OtChorusSIG0* sig0 = newOtChorusSIG0();
		sig0->instanceInitOtChorusSIG0(sample_rate);
		sig0->fillOtChorusSIG0(65536, ftbl0OtChorusSIG0);
		deleteOtChorusSIG0(sig0);
	}
	
	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 0.5 * fConst0;
		fConst2 = 1.0 / fConst0;
	}
	
	virtual void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(0.5);
		fHslider1 = static_cast<float>(0.025);
		fHslider2 = static_cast<float>(0.02);
		fHslider3 = static_cast<float>(2.0);
	}
	
	virtual void instanceClear() {
		IOTA0 = 0;
		for (int l0 = 0; l0 < 65536; l0 = l0 + 1) {
			fVec0[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec0[l1] = 0.0;
		}
		for (int l3 = 0; l3 < 65536; l3 = l3 + 1) {
			fVec1[l3] = 0.0;
		}
	}
	
	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
	
	virtual OtChorus* clone() {
		return new OtChorus(*this);
	}
	
	int getSampleRate() override {
		return fSampleRate;
	}
	
	void buildUserInterface(UI* ui_interface) override {
		ui_interface->openVerticalBox("chorus");
		ui_interface->addHorizontalSlider("delay", &fHslider1, float(0.025), float(0.0), float(0.2), float(0.001));
		ui_interface->addHorizontalSlider("depth", &fHslider2, float(0.02), float(0.0), float(1.0), float(0.001));
		ui_interface->addHorizontalSlider("freq", &fHslider3, float(2.0), float(0.0), float(1e+01), float(0.01));
		ui_interface->addHorizontalSlider("level", &fHslider0, float(0.5), float(0.0), float(1.0), float(0.01));
		ui_interface->closeBox();
	}
	
	void compute(int count, float** inputs, float** outputs) override {
		float* input0 = inputs[0];
		float* input1 = inputs[1];
		float* output0 = outputs[0];
		float* output1 = outputs[1];
		double fSlow0 = static_cast<double>(fHslider0);
		double fSlow1 = fConst1 * static_cast<double>(fHslider1);
		double fSlow2 = static_cast<double>(fHslider2);
		double fSlow3 = fConst2 * static_cast<double>(fHslider3);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			fVec0[IOTA0 & 65535] = fTemp0;
			fRec0[0] = fSlow3 + (fRec0[1] - std::floor(fSlow3 + fRec0[1]));
			double fTemp1 = 65536.0 * (fRec0[0] - std::floor(fRec0[0]));
			double fTemp2 = std::floor(fTemp1);
			int iTemp3 = static_cast<int>(fTemp2);
			double fTemp4 = fSlow1 * (fSlow2 * ((fTemp2 + (1.0 - fTemp1)) * ftbl0OtChorusSIG0[iTemp3 & 65535] + (fTemp1 - fTemp2) * ftbl0OtChorusSIG0[(iTemp3 + 1) & 65535]) + 1.0);
			int iTemp5 = static_cast<int>(fTemp4);
			int iTemp6 = iTemp5 & 65535;
			double fTemp7 = static_cast<double>(iTemp5);
			double fTemp8 = fTemp7 + (1.0 - fTemp4);
			double fTemp9 = fTemp4 - fTemp7;
			int iTemp10 = (iTemp5 + 1) & 65535;
			output0[i0] = static_cast<float>(fTemp0 + fSlow0 * (fVec0[(IOTA0 - iTemp6) & 65535] * fTemp8 + fTemp9 * fVec0[(IOTA0 - iTemp10) & 65535]));
			double fTemp11 = static_cast<double>(input1[i0]);
			fVec1[IOTA0 & 65535] = fTemp11;
			output1[i0] = static_cast<float>(fTemp11 + fSlow0 * (fTemp8 * fVec1[(IOTA0 - iTemp6) & 65535] + fTemp9 * fVec1[(IOTA0 - iTemp10) & 65535]));
			IOTA0 = IOTA0 + 1;
			fRec0[1] = fRec0[0];
		}
	}
};
