//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtChorus
//

class OtChorusSIG0 {
protected:	
	int iRec1[2];

public:	
	int getNumInputsOtChorusSIG0() {
		return 0;
	}
	int getNumOutputsOtChorusSIG0() {
		return 1;
	}
	
	void instanceInitOtChorusSIG0([[maybe_unused]] int sample_rate) {
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			iRec1[l2] = 0;
		}
	}
	
	void fillOtChorusSIG0(int count, double* table) {
		for (int i1 = 0; i1 < count; i1 = i1 + 1) {
			iRec1[0] = iRec1[1] + 1;
			table[i1] = std::sin(9.587379924285257e-05 * static_cast<double>(iRec1[0] + -1));
			iRec1[1] = iRec1[0];
		}
	}

};

static OtChorusSIG0* newOtChorusSIG0() { return (OtChorusSIG0*)new OtChorusSIG0(); }
static void deleteOtChorusSIG0(OtChorusSIG0* dsp) { delete dsp; }

static double ftbl0OtChorusSIG0[65536];

class OtChorus : public OtFaust {
protected:
	int IOTA0;
	double fVec0[65536];
	float fVslider0;
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fVslider1;
	float fVslider2;
	double fConst2;
	float fVslider3;
	double fRec0[2];
	double fVec1[65536];
	
 public:
	OtChorus() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("category", "Effect");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtChorus -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtChorus.dsp");
		m->declare("license", "MIT");
		m->declare("math.lib/author", "GRAME");
		m->declare("math.lib/copyright", "GRAME");
		m->declare("math.lib/deprecated", "This library is deprecated and is not maintained anymore. It will be removed in August 2017.");
		m->declare("math.lib/license", "LGPL with exception");
		m->declare("math.lib/name", "Math Library");
		m->declare("math.lib/version", "1.0");
		m->declare("music.lib/author", "GRAME");
		m->declare("music.lib/copyright", "GRAME");
		m->declare("music.lib/deprecated", "This library is deprecated and is not maintained anymore. It will be removed in August 2017.");
		m->declare("music.lib/license", "LGPL with exception");
		m->declare("music.lib/name", "Music Library");
		m->declare("music.lib/version", "1.0");
		m->declare("name", "Chorus");
	}

	inline int getNumInputs() {
		return 2;
	}
	inline int getNumOutputs() {
		return 2;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
		OtChorusSIG0* sig0 = newOtChorusSIG0();
		sig0->instanceInitOtChorusSIG0(sample_rate);
		sig0->fillOtChorusSIG0(65536, ftbl0OtChorusSIG0);
		deleteOtChorusSIG0(sig0);
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 0.5 * fConst0;
		fConst2 = 1.0 / fConst0;
	}
	
	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(0.5);
		fVslider1 = static_cast<float>(0.025);
		fVslider2 = static_cast<float>(0.02);
		fVslider3 = static_cast<float>(2.0);
	}
	
	inline void instanceClear() {
		IOTA0 = 0;
		for (int l0 = 0; l0 < 65536; l0 = l0 + 1) {
			fVec0[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec0[l1] = 0.0;
		}
		for (int l3 = 0; l3 < 65536; l3 = l3 + 1) {
			fVec1[l3] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
		
	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* input1 = inputs[1];
		float* output0 = outputs[0];
		float* output1 = outputs[1];
		double fSlow0 = static_cast<double>(fVslider0);
		double fSlow1 = fConst1 * static_cast<double>(fVslider1);
		double fSlow2 = static_cast<double>(fVslider2);
		double fSlow3 = fConst2 * static_cast<double>(fVslider3);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			fVec0[IOTA0 & 65535] = fTemp0;
			fRec0[0] = fSlow3 + (fRec0[1] - std::floor(fSlow3 + fRec0[1]));
			double fTemp1 = 65536.0 * (fRec0[0] - std::floor(fRec0[0]));
			double fTemp2 = std::floor(fTemp1);
			int iTemp3 = static_cast<int>(fTemp2);
			double fTemp4 = fSlow1 * (fSlow2 * ((fTemp2 + (1.0 - fTemp1)) * ftbl0OtChorusSIG0[iTemp3 & 65535] + (fTemp1 - fTemp2) * ftbl0OtChorusSIG0[(iTemp3 + 1) & 65535]) + 1.0);
			int iTemp5 = static_cast<int>(fTemp4);
			int iTemp6 = iTemp5 & 65535;
			double fTemp7 = static_cast<double>(iTemp5);
			double fTemp8 = fTemp7 + (1.0 - fTemp4);
			double fTemp9 = fTemp4 - fTemp7;
			int iTemp10 = (iTemp5 + 1) & 65535;
			output0[i0] = static_cast<float>(fTemp0 + fSlow0 * (fVec0[(IOTA0 - iTemp6) & 65535] * fTemp8 + fTemp9 * fVec0[(IOTA0 - iTemp10) & 65535]));
			double fTemp11 = static_cast<double>(input1[i0]);
			fVec1[IOTA0 & 65535] = fTemp11;
			output1[i0] = static_cast<float>(fTemp11 + fSlow0 * (fTemp8 * fVec1[(IOTA0 - iTemp6) & 65535] + fTemp9 * fVec1[(IOTA0 - iTemp10) & 65535]));
			IOTA0 = IOTA0 + 1;
			fRec0[1] = fRec0[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Chorus");
		changed |= editLevel();
		ImGui::SameLine();
		changed |= editFreq();
		ImGui::SameLine();
		changed |= editDelay();
		ImGui::SameLine();
		changed |= editDepth();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float level = 0.5f;
		float freq = 2.0f;
		float delay = 0.025f;
		float depth = 0.02f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider0 = parameters.level;
		fVslider3 = parameters.freq;
		fVslider1 = parameters.delay;
		fVslider2 = parameters.depth;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.level = fVslider0;
		parameters.freq = fVslider3;
		parameters.delay = fVslider1;
		parameters.depth = fVslider2;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("level", &fVslider0, 0.5f);
		callback("freq", &fVslider3, 2.0f);
		callback("delay", &fVslider1, 0.025f);
		callback("depth", &fVslider2, 0.02f);
	}

	inline bool editLevel() { return OtUi::knob("Level", &fVslider0, 0.0f, 1.0f, "%.2f", false); }
	inline bool editFreq() { return OtUi::knob("Freq", &fVslider3, 0.0f, 10.0f, "%.2f", false); }
	inline bool editDelay() { return OtUi::knob("Delay", &fVslider1, 0.0f, 0.2f, "%.2f", false); }
	inline bool editDepth() { return OtUi::knob("Depth", &fVslider2, 0.0f, 1.0f, "%.2f", false); }

	inline void setLevel(float value) { fVslider0 = value; }
	inline void setFreq(float value) { fVslider3 = value; }
	inline void setDelay(float value) { fVslider1 = value; }
	inline void setDepth(float value) { fVslider2 = value; }

	inline float getLevel() { return fVslider0; }
	inline float getFreq() { return fVslider3; }
	inline float getDelay() { return fVslider1; }
	inline float getDepth() { return fVslider2; }

private:
	bool initialized = false;
	float width;
	float height;
};
