//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtCompressor
//

class OtCompressor : public OtFaust {
private:
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fHslider0;
	double fConst2;
	double fRec2[2];
	double fConst3;
	float fHslider1;
	double fRec3[2];
	double fRec1[2];
	float fHslider2;
	double fRec4[2];
	float fHslider3;
	double fRec5[2];
	double fRec0[2];

 public:
	OtCompressor() {
	}

	OtCompressor(const OtCompressor&) = default;

	virtual ~OtCompressor() = default;

	OtCompressor& operator=(const OtCompressor&) = default;

	void metadata(Meta* m) override {
		m->declare("analyzers.lib/amp_follower_ar:author", "Jonatan Liljedahl, revised by Romain Michon");
		m->declare("analyzers.lib/name", "Faust Analyzer Library");
		m->declare("analyzers.lib/version", "1.3.0");
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Compressor");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtCompressor -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("compressors.lib/compression_gain_mono:author", "Julius O. Smith III");
		m->declare("compressors.lib/compression_gain_mono:copyright", "Copyright (C) 2014-2020 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("compressors.lib/compression_gain_mono:license", "MIT-style STK-4.3 license");
		m->declare("compressors.lib/compressor_lad_mono:author", "Julius O. Smith III");
		m->declare("compressors.lib/compressor_lad_mono:copyright", "Copyright (C) 2014-2020 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("compressors.lib/compressor_lad_mono:license", "MIT-style STK-4.3 license");
		m->declare("compressors.lib/compressor_mono:author", "Julius O. Smith III");
		m->declare("compressors.lib/compressor_mono:copyright", "Copyright (C) 2014-2020 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("compressors.lib/compressor_mono:license", "MIT-style STK-4.3 license");
		m->declare("compressors.lib/name", "Faust Compressor Effect Library");
		m->declare("compressors.lib/version", "1.6.0");
		m->declare("filename", "compressor.dsp");
		m->declare("id", "compressor");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Compressor");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/onePoleSwitching:author", "Jonatan Liljedahl, revised by Dario Sanfilippo");
		m->declare("signals.lib/onePoleSwitching:licence", "STK-4.3");
		m->declare("signals.lib/version", "1.6.0");
	}

	int getNumInputs() override {
		return 1;
	}
	int getNumOutputs() override {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 44.1 / fConst0;
		fConst2 = 1.0 - fConst1;
		fConst3 = 1.0 / fConst0;
	}

	virtual void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(2e+02);
		fHslider1 = static_cast<float>(1e+01);
		fHslider2 = static_cast<float>(-1e+01);
		fHslider3 = static_cast<float>(4.0);
	}

	virtual void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fRec2[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec3[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec1[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec4[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec5[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fRec0[l5] = 0.0;
		}
	}

	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	virtual OtCompressor* clone() {
		return new OtCompressor(*this);
	}

	int getSampleRate() override {
		return fSampleRate;
	}

	void buildUserInterface(UI* ui_interface) override {
		ui_interface->openVerticalBox("Compressor");
		ui_interface->declare(&fHslider3, "0", "");
		ui_interface->addHorizontalSlider("Ratio", &fHslider3, float(4.0), float(1.0), float(2e+01), float(0.1));
		ui_interface->declare(&fHslider2, "1", "");
		ui_interface->declare(&fHslider2, "format", "%.0fdB");
		ui_interface->addHorizontalSlider("Thresh", &fHslider2, float(-1e+01), float(-5e+01), float(0.0), float(1.0));
		ui_interface->declare(&fHslider1, "2", "");
		ui_interface->declare(&fHslider1, "format", "%.0fms");
		ui_interface->addHorizontalSlider("Attack", &fHslider1, float(1e+01), float(0.0), float(2e+02), float(1.0));
		ui_interface->declare(&fHslider0, "3", "");
		ui_interface->declare(&fHslider0, "format", "%.0fms");
		ui_interface->addHorizontalSlider("Release", &fHslider0, float(2e+02), float(5.0), float(1e+03), float(1.0));
		ui_interface->closeBox();
	}

	void compute(int count, float** inputs, float** outputs) override {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = fConst1 * static_cast<double>(fHslider0);
		double fSlow1 = fConst1 * static_cast<double>(fHslider1);
		double fSlow2 = fConst1 * static_cast<double>(fHslider2);
		double fSlow3 = fConst1 * static_cast<double>(fHslider3);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			double fTemp1 = std::fabs(fTemp0);
			fRec2[0] = fSlow0 + fConst2 * fRec2[1];
			double fTemp2 = 0.001 * fRec2[0];
			int iTemp3 = std::fabs(fTemp2) < 2.220446049250313e-16;
			fRec3[0] = fSlow1 + fConst2 * fRec3[1];
			double fTemp4 = 0.001 * fRec3[0];
			int iTemp5 = std::fabs(fTemp4) < 2.220446049250313e-16;
			double fTemp6 = ((fTemp1 > fRec1[1]) ? ((iTemp5) ? 0.0 : std::exp(-(fConst3 / ((iTemp5) ? 1.0 : fTemp4)))) : ((iTemp3) ? 0.0 : std::exp(-(fConst3 / ((iTemp3) ? 1.0 : fTemp2)))));
			fRec1[0] = fTemp1 * (1.0 - fTemp6) + fRec1[1] * fTemp6;
			fRec4[0] = fSlow2 + fConst2 * fRec4[1];
			double fTemp7 = 0.0005 * fRec3[0];
			int iTemp8 = std::fabs(fTemp7) < 2.220446049250313e-16;
			double fTemp9 = ((iTemp8) ? 0.0 : std::exp(-(fConst3 / ((iTemp8) ? 1.0 : fTemp7))));
			fRec5[0] = fSlow3 + fConst2 * fRec5[1];
			fRec0[0] = std::max<double>(2e+01 * std::log10(std::max<double>(2.2250738585072014e-308, fRec1[0])) - fRec4[0], 0.0) * (1.0 - fTemp9) * (1.0 / std::max<double>(2.220446049250313e-16, fRec5[0]) + -1.0) + fTemp9 * fRec0[1];
			output0[i0] = static_cast<float>(fTemp0 * std::pow(1e+01, 0.05 * fRec0[0]));
			fRec2[1] = fRec2[0];
			fRec3[1] = fRec3[0];
			fRec1[1] = fRec1[0];
			fRec4[1] = fRec4[0];
			fRec5[1] = fRec5[0];
			fRec0[1] = fRec0[0];
		}
	}
};
