//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtEq
//

static double OtEq_faustpower2_f(double value) {
	return value * value;
}

class OtEq : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fHslider0;
	float fHslider1;
	double fVec0[2];
	double fRec4[2];
	double fRec3[3];
	float fHslider2;
	double fRec6[2];
	double fRec5[3];
	float fHslider3;
	double fRec7[2];
	float fHslider4;
	float fHslider5;
	double fConst2;
	double fRec2[3];
	double fVec1[2];
	double fRec1[2];
	double fRec0[3];
	float fHslider6;
	double fRec9[2];
	double fRec8[3];
	
 public:
	OtEq() {
	}
	
	OtEq(const OtEq&) = default;
	
	virtual ~OtEq() = default;
	
	OtEq& operator=(const OtEq&) = default;
	
	void metadata(Meta* m) override { 
		m->declare("analyzers.lib/name", "Faust Analyzer Library");
		m->declare("analyzers.lib/version", "1.3.0");
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Envelope");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtEq -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtEq.dsp");
		m->declare("filters.lib/filterbank:author", "Julius O. Smith III");
		m->declare("filters.lib/filterbank:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/filterbank:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/highpass:author", "Julius O. Smith III");
		m->declare("filters.lib/highpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/highshelf:author", "Julius O. Smith III");
		m->declare("filters.lib/highshelf:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/highshelf:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/low_shelf:author", "Julius O. Smith III");
		m->declare("filters.lib/low_shelf:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/low_shelf:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowpass0_highpass1:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowpass:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowshelf:author", "Julius O. Smith III");
		m->declare("filters.lib/lowshelf:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowshelf:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/peak_eq:author", "Julius O. Smith III");
		m->declare("filters.lib/peak_eq:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/peak_eq:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf1:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf1s:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1s:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2s:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2s:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "ADSR");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	int getNumInputs() override {
		return 1;
	}
	int getNumOutputs() override {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 3.141592653589793 / fConst0;
		fConst2 = 6.283185307179586 / fConst0;
	}
	
	virtual void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(8e+03);
		fHslider1 = static_cast<float>(2e+02);
		fHslider2 = static_cast<float>(0.0);
		fHslider3 = static_cast<float>(1e+03);
		fHslider4 = static_cast<float>(0.0);
		fHslider5 = static_cast<float>(4e+01);
		fHslider6 = static_cast<float>(0.0);
	}
	
	virtual void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fVec0[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec4[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 3; l2 = l2 + 1) {
			fRec3[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec6[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 3; l4 = l4 + 1) {
			fRec5[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fRec7[l5] = 0.0;
		}
		for (int l6 = 0; l6 < 3; l6 = l6 + 1) {
			fRec2[l6] = 0.0;
		}
		for (int l7 = 0; l7 < 2; l7 = l7 + 1) {
			fVec1[l7] = 0.0;
		}
		for (int l8 = 0; l8 < 2; l8 = l8 + 1) {
			fRec1[l8] = 0.0;
		}
		for (int l9 = 0; l9 < 3; l9 = l9 + 1) {
			fRec0[l9] = 0.0;
		}
		for (int l10 = 0; l10 < 2; l10 = l10 + 1) {
			fRec9[l10] = 0.0;
		}
		for (int l11 = 0; l11 < 3; l11 = l11 + 1) {
			fRec8[l11] = 0.0;
		}
	}
	
	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
	
	virtual OtEq* clone() {
		return new OtEq(*this);
	}
	
	int getSampleRate() override {
		return fSampleRate;
	}
		
	void compute(int count, [[maybe_unused]] float** inputs, float** outputs) override {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = std::tan(fConst1 * static_cast<double>(fHslider0));
		double fSlow1 = 1.0 / fSlow0;
		double fSlow2 = 1.0 / ((fSlow1 + 1.0000000000000004) / fSlow0 + 1.0);
		double fSlow3 = 1.0 / (fSlow1 + 1.0);
		double fSlow4 = 1.0 - fSlow1;
		double fSlow5 = std::tan(fConst1 * static_cast<double>(fHslider1));
		double fSlow6 = 1.0 / fSlow5;
		double fSlow7 = 1.0 / ((fSlow6 + 1.0000000000000004) / fSlow5 + 1.0);
		double fSlow8 = 1.0 / OtEq_faustpower2_f(fSlow5);
		double fSlow9 = 1.0 / (fSlow6 + 1.0);
		double fSlow10 = 1.0 - fSlow6;
		double fSlow11 = (fSlow6 + -1.0000000000000004) / fSlow5 + 1.0;
		double fSlow12 = 2.0 * (1.0 - fSlow8);
		double fSlow13 = std::pow(1e+01, 0.05 * static_cast<double>(fHslider2));
		double fSlow14 = 0.0010000000000000009 * static_cast<double>(fHslider3);
		double fSlow15 = static_cast<double>(fHslider4);
		int iSlow16 = fSlow15 > 0.0;
		double fSlow17 = static_cast<double>(fHslider5);
		double fSlow18 = fConst1 * (std::pow(1e+01, 0.05 * std::fabs(fSlow15)) / fSlow17);
		double fSlow19 = fConst1 / fSlow17;
		double fSlow20 = (fSlow1 + -1.0000000000000004) / fSlow0 + 1.0;
		double fSlow21 = OtEq_faustpower2_f(fSlow0);
		double fSlow22 = 2.0 * (1.0 - 1.0 / fSlow21);
		double fSlow23 = std::pow(1e+01, 0.05 * static_cast<double>(fHslider6)) / fSlow21;
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			fVec0[0] = fTemp0;
			fRec4[0] = -(fSlow9 * (fSlow10 * fRec4[1] - fSlow6 * (fTemp0 - fVec0[1])));
			fRec3[0] = fRec4[0] - fSlow7 * (fSlow11 * fRec3[2] + fSlow12 * fRec3[1]);
			fRec6[0] = -(fSlow9 * (fSlow10 * fRec6[1] - (fTemp0 + fVec0[1])));
			fRec5[0] = fRec6[0] - fSlow7 * (fSlow11 * fRec5[2] + fSlow12 * fRec5[1]);
			fRec7[0] = fSlow14 + 0.999 * fRec7[1];
			double fTemp1 = std::tan(fConst1 * fRec7[0]);
			double fTemp2 = 1.0 / fTemp1;
			double fTemp3 = fRec7[0] / std::sin(fConst2 * fRec7[0]);
			double fTemp4 = fSlow18 * fTemp3;
			double fTemp5 = fSlow19 * fTemp3;
			double fTemp6 = ((iSlow16) ? fTemp5 : fTemp4);
			double fTemp7 = 2.0 * fRec2[1] * (1.0 - 1.0 / OtEq_faustpower2_f(fTemp1));
			double fTemp8 = (fTemp2 + fTemp6) / fTemp1 + 1.0;
			fRec2[0] = fSlow7 * (fSlow8 * (fRec3[2] + (fRec3[0] - 2.0 * fRec3[1])) + fSlow13 * (fRec5[2] + fRec5[0] + 2.0 * fRec5[1])) - (fRec2[2] * ((fTemp2 - fTemp6) / fTemp1 + 1.0) + fTemp7) / fTemp8;
			double fTemp9 = ((iSlow16) ? fTemp4 : fTemp5);
			double fTemp10 = (fTemp7 + fRec2[0] * ((fTemp2 + fTemp9) / fTemp1 + 1.0) + fRec2[2] * ((fTemp2 - fTemp9) / fTemp1 + 1.0)) / fTemp8;
			fVec1[0] = fTemp10;
			fRec1[0] = -(fSlow3 * (fSlow4 * fRec1[1] - (fTemp10 + fVec1[1])));
			fRec0[0] = fRec1[0] - fSlow2 * (fSlow20 * fRec0[2] + fSlow22 * fRec0[1]);
			fRec9[0] = -(fSlow3 * (fSlow4 * fRec9[1] - fSlow1 * (fTemp10 - fVec1[1])));
			fRec8[0] = fRec9[0] - fSlow2 * (fSlow20 * fRec8[2] + fSlow22 * fRec8[1]);
			output0[i0] = static_cast<float>(fSlow2 * (fRec0[2] + fRec0[0] + 2.0 * fRec0[1] + fSlow23 * (fRec8[2] + (fRec8[0] - 2.0 * fRec8[1]))));
			fVec0[1] = fVec0[0];
			fRec4[1] = fRec4[0];
			fRec3[2] = fRec3[1];
			fRec3[1] = fRec3[0];
			fRec6[1] = fRec6[0];
			fRec5[2] = fRec5[1];
			fRec5[1] = fRec5[0];
			fRec7[1] = fRec7[0];
			fRec2[2] = fRec2[1];
			fRec2[1] = fRec2[0];
			fVec1[1] = fVec1[0];
			fRec1[1] = fRec1[0];
			fRec0[2] = fRec0[1];
			fRec0[1] = fRec0[0];
			fRec9[1] = fRec9[0];
			fRec8[2] = fRec8[1];
			fRec8[1] = fRec8[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		auto frame = ImGui::GetFrameHeightWithSpacing();
		auto padding = ImGui::GetStyle().WindowPadding;
		float width1 = 0.0f;
		float height1 = 0.0f;
		float width2 = 0.0f;
		float height2 = 0.0f;
		width2 = std::max(width2, knobWidth);
		height2 += knobHeight;
		width2 = std::max(width2, knobWidth);
		height2 += knobHeight;
		width2 += padding.x * 2.0f;
		height2 += frame + padding.y * 2.0f;
		width1 += width2;
		height1 = std::max(height1, height2);
		width1 += spacing.x;
		float width3 = 0.0f;
		float height3 = 0.0f;
		width3 = std::max(width3, knobWidth);
		height3 += knobHeight;
		width3 = std::max(width3, knobWidth);
		height3 += knobHeight;
		width3 = std::max(width3, knobWidth);
		height3 += knobHeight;
		width3 += padding.x * 2.0f;
		height3 += frame + padding.y * 2.0f;
		width1 += width3;
		height1 = std::max(height1, height3);
		width1 += spacing.x;
		float width4 = 0.0f;
		float height4 = 0.0f;
		width4 = std::max(width4, knobWidth);
		height4 += knobHeight;
		width4 = std::max(width4, knobWidth);
		height4 += knobHeight;
		width4 += padding.x * 2.0f;
		height4 += frame + padding.y * 2.0f;
		width1 += width4;
		height1 = std::max(height1, height4);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginChild("Parametric EQ", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY);
		ImGui::BeginChild("Low", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY | ImGuiChildFlags_Borders);
		OtUi::header("Low");
		changed |= OtUi::knob("Level", &fHslider2, -40.0f, 40.0f, "%.1f");
		changed |= OtUi::knob("Freq", &fHslider1, 1.0f, 5000.0f, "%.0f");
		ImGui::EndChild();
		ImGui::SameLine();
		ImGui::BeginChild("Notch", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY | ImGuiChildFlags_Borders);
		OtUi::header("Notch");
		changed |= OtUi::knob("Level", &fHslider4, -40.0f, 40.0f, "%.1f");
		changed |= OtUi::knob("Freq", &fHslider3, 20.0f, 10000.0f, "%.0f");
		changed |= OtUi::knob("Q", &fHslider5, 1.0f, 1000.0f, "%.1f");
		ImGui::EndChild();
		ImGui::SameLine();
		ImGui::BeginChild("High", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY | ImGuiChildFlags_Borders);
		OtUi::header("High");
		changed |= OtUi::knob("Level", &fHslider6, -40.0f, 40.0f, "%.1f");
		changed |= OtUi::knob("Freq", &fHslider0, 20.0f, 10000.0f, "%.0f");
		ImGui::EndChild();
		ImGui::EndChild();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float lowLevel = 0.0f;
		float lowFreq = 200.0f;
		float notchLevel = 0.0f;
		float notchFreq = 1000.0f;
		float notchQ = 40.0f;
		float highLevel = 0.0f;
		float highFreq = 8000.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider2 = parameters.lowLevel;
		fHslider1 = parameters.lowFreq;
		fHslider4 = parameters.notchLevel;
		fHslider3 = parameters.notchFreq;
		fHslider5 = parameters.notchQ;
		fHslider6 = parameters.highLevel;
		fHslider0 = parameters.highFreq;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.lowLevel = fHslider2;
		parameters.lowFreq = fHslider1;
		parameters.notchLevel = fHslider4;
		parameters.notchFreq = fHslider3;
		parameters.notchQ = fHslider5;
		parameters.highLevel = fHslider6;
		parameters.highFreq = fHslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("lowLevel", &fHslider2, 0.0f);
		callback("lowFreq", &fHslider1, 200.0f);
		callback("notchLevel", &fHslider4, 0.0f);
		callback("notchFreq", &fHslider3, 1000.0f);
		callback("notchQ", &fHslider5, 40.0f);
		callback("highLevel", &fHslider6, 0.0f);
		callback("highFreq", &fHslider0, 8000.0f);
	}

	inline void setLowLevel(float value) { fHslider2 = value; }
	inline void setLowFreq(float value) { fHslider1 = value; }
	inline void setNotchLevel(float value) { fHslider4 = value; }
	inline void setNotchFreq(float value) { fHslider3 = value; }
	inline void setNotchQ(float value) { fHslider5 = value; }
	inline void setHighLevel(float value) { fHslider6 = value; }
	inline void setHighFreq(float value) { fHslider0 = value; }

	inline float getLowLevel() { return fHslider2; }
	inline float getLowFreq() { return fHslider1; }
	inline float getNotchLevel() { return fHslider4; }
	inline float getNotchFreq() { return fHslider3; }
	inline float getNotchQ() { return fHslider5; }
	inline float getHighLevel() { return fHslider6; }
	inline float getHighFreq() { return fHslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
