//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtFlanger
//

class OtFlanger : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	float fVslider0;
	double fConst1;
	double fRec1[2];
	int IOTA0;
	double fVec0[1024];
	float fVslider1;
	double fRec2[2];
	double fRec0[2];
	float fVslider2;
	double fRec3[2];
	
 public:
	OtFlanger() {
	}
	
	OtFlanger(const OtFlanger&) = default;
	
	virtual ~OtFlanger() = default;
	
	OtFlanger& operator=(const OtFlanger&) = default;
	
	void metadata(Meta* m) override { 
		m->declare("category", "Modulation");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtFlanger -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("delays.lib/name", "Faust Delay Library");
		m->declare("delays.lib/version", "1.2.0");
		m->declare("filename", "OtFlanger.dsp");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Flanger");
		m->declare("phaflangers.lib/name", "Faust Phaser and Flanger Library");
		m->declare("phaflangers.lib/version", "1.1.0");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	int getNumInputs() override {
		return 1;
	}
	int getNumOutputs() override {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = 44.1 / std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 1.0 - fConst0;
	}
	
	virtual void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(6e+01);
		fVslider1 = static_cast<float>(0.2);
		fVslider2 = static_cast<float>(5e+01);
	}
	
	virtual void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fRec1[l0] = 0.0;
		}
		IOTA0 = 0;
		for (int l1 = 0; l1 < 1024; l1 = l1 + 1) {
			fVec0[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec2[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec0[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec3[l4] = 0.0;
		}
	}
	
	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
	
	virtual OtFlanger* clone() {
		return new OtFlanger(*this);
	}
	
	int getSampleRate() override {
		return fSampleRate;
	}
		
	void compute(int count, [[maybe_unused]] float** inputs, float** outputs) override {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = fConst0 * static_cast<double>(fVslider0);
		double fSlow1 = fConst0 * static_cast<double>(fVslider1);
		double fSlow2 = fConst0 * static_cast<double>(fVslider2);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			fRec1[0] = fSlow0 + fConst1 * fRec1[1];
			double fTemp1 = 0.01 * fRec1[0] * fRec0[1] - fTemp0;
			fVec0[IOTA0 & 1023] = fTemp1;
			fRec2[0] = fSlow1 + fConst1 * fRec2[1];
			double fTemp2 = 51.2 * fRec2[0];
			int iTemp3 = static_cast<int>(fTemp2);
			double fTemp4 = std::floor(fTemp2);
			fRec0[0] = fVec0[(IOTA0 - std::min<int>(513, std::max<int>(0, iTemp3))) & 1023] * (fTemp4 + (1.0 - fTemp2)) + (fTemp2 - fTemp4) * fVec0[(IOTA0 - std::min<int>(513, std::max<int>(0, iTemp3 + 1))) & 1023];
			fRec3[0] = fSlow2 + fConst1 * fRec3[1];
			output0[i0] = static_cast<float>(0.5 * (fTemp0 + 0.01 * fRec0[0] * fRec3[0]));
			fRec1[1] = fRec1[0];
			IOTA0 = IOTA0 + 1;
			fRec2[1] = fRec2[0];
			fRec0[1] = fRec0[0];
			fRec3[1] = fRec3[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginChild("Flanger", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY);
		changed |= OtUi::knob("Delay", &fVslider1, 0.0f, 10.0f, "%.1fms");
		ImGui::SameLine();
		changed |= OtUi::knob("Depth", &fVslider2, 0.0f, 100.0f, "%.0f%%");
		ImGui::SameLine();
		changed |= OtUi::knob("Feedback", &fVslider0, 0.0f, 100.0f, "%.0f%%");
		ImGui::EndChild();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float delay = 0.2f;
		float depth = 50.0f;
		float feedback = 60.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider1 = parameters.delay;
		fVslider2 = parameters.depth;
		fVslider0 = parameters.feedback;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.delay = fVslider1;
		parameters.depth = fVslider2;
		parameters.feedback = fVslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("delay", &fVslider1, 0.2f);
		callback("depth", &fVslider2, 50.0f);
		callback("feedback", &fVslider0, 60.0f);
	}

	inline void setDelay(float value) { fVslider1 = value; }
	inline void setDepth(float value) { fVslider2 = value; }
	inline void setFeedback(float value) { fVslider0 = value; }

	inline float getDelay() { return fVslider1; }
	inline float getDepth() { return fVslider2; }
	inline float getFeedback() { return fVslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
