//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"


//
//  OtFuzzFace
//

static double OtFuzzFace_faustpower2_f(double value) {
	return value * value;
}
static double OtFuzzFace_faustpower3_f(double value) {
	return value * value * value;
}

class OtFuzzFace : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	double fConst2;
	double fConst3;
	float fHslider0;
	double fRec1[2];
	double fConst4;
	double fConst5;
	float fVslider0;
	double fRec2[2];
	double fConst6;
	double fConst7;
	double fConst8;
	double fConst9;
	double fConst10;
	double fConst11;
	double fConst12;
	double fConst13;
	double fConst14;
	double fConst15;
	double fConst16;
	double fConst17;
	double fConst18;
	double fConst19;
	double fConst20;
	double fConst21;
	double fConst22;
	double fConst23;
	double fConst24;
	double fConst25;
	double fConst26;
	double fConst27;
	double fConst28;
	double fConst29;
	double fConst30;
	double fConst31;
	double fConst32;
	double fConst33;
	double fConst34;
	double fConst35;
	double fConst36;
	double fConst37;
	double fConst38;
	double fConst39;
	double fConst40;
	double fConst41;
	double fConst42;
	double fConst43;
	double fConst44;
	double fConst45;
	double fConst46;
	double fConst47;
	double fConst48;
	double fConst49;
	double fConst50;
	double fConst51;
	double fConst52;
	double fConst53;
	double fConst54;
	double fConst55;
	double fConst56;
	double fConst57;
	double fConst58;
	double fConst59;
	double fConst60;
	double fConst61;
	double fConst62;
	double fConst63;
	double fConst64;
	double fConst65;
	double fConst66;
	double fConst67;
	double fConst68;
	double fConst69;
	double fRec0[4];
	double fConst70;
	double fConst71;
	double fConst72;
	double fConst73;
	double fConst74;
	double fConst75;
	double fConst76;
	double fConst77;
	double fConst78;
	double fConst79;
	double fConst80;
	double fConst81;
	double fConst82;
	double fConst83;
	double fConst84;
	double fConst85;
	double fConst86;
	
 public:
	OtFuzzFace() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("category", "Fuzz");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtFuzzFace -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("description", "Micke Fuller Fuzz Face simulation");
		m->declare("filename", "OtFuzzFace.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Fuzz Face Fuller");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 7.55358741622564e-17 * fConst0;
		fConst2 = 1.68148957452649e-16 * fConst0;
		fConst3 = fConst0 * (fConst0 * (fConst1 + 1.61641996632585e-12) + -1.6091784998802e-10 + fConst0 * (-1.63110208134281e-12 - fConst2) + 1.69410806769336e-10);
		fConst4 = 3.35312097339121e-19 * fConst0;
		fConst5 = fConst0 * (fConst4 + 3.24149709132582e-15) + -1.46288954534563e-14;
		fConst6 = 4.27176866080457e-16 * fConst0;
		fConst7 = fConst0 * (fConst6 + 6.43214948741896e-16) + 3.45797348759893e-55;
		fConst8 = 4.27512178177797e-16 * fConst0;
		fConst9 = fConst0 * (-6.43443174346988e-16 - fConst8) + -3.26234246975457e-55;
		fConst10 = 1.50628899360393e-19 * fConst0;
		fConst11 = fConst0 * (fConst0 * (-3.21835699976039e-15 - fConst10) + -1.53335572595511e-54);
		fConst12 = OtFuzzFace_faustpower2_f(fConst0);
		fConst13 = 4.24521866169651e-16 * fConst0;
		fConst14 = 7.60754167271764e-56 - fConst13;
		fConst15 = 4.24672495069012e-16 * fConst0;
		fConst16 = fConst15 + -7.17715343346006e-56;
		fConst17 = 2.14216383033367e-13 * fConst0;
		fConst18 = fConst0 * (-7.44216743501989e-12 - fConst17) + 3.21607474370948e-11;
		fConst19 = 2.1438453199082e-13 * fConst0;
		fConst20 = fConst0 * (fConst19 + 7.44787041826973e-12) + -3.21721587173494e-11;
		fConst21 = 2.12884980228095e-13 * fConst0;
		fConst22 = fConst21 + 7.07536443616085e-12;
		fConst23 = 2.12960516102257e-13 * fConst0;
		fConst24 = -7.07787491781686e-12 - fConst23;
		fConst25 = fConst0 * (fConst0 * (1.61641996632585e-12 - fConst1) + 1.6091784998802e-10 + fConst0 * (fConst2 + -1.63110208134281e-12) + -1.69410806769336e-10);
		fConst26 = fConst0 * (3.24149709132582e-15 - fConst4) + 1.46288954534563e-14;
		fConst27 = fConst0 * (6.43214948741896e-16 - fConst6) + -3.45797348759893e-55;
		fConst28 = fConst0 * (fConst8 + -6.43443174346988e-16) + 3.26234246975457e-55;
		fConst29 = fConst0 * (fConst0 * (fConst10 + -3.21835699976039e-15) + 1.53335572595511e-54);
		fConst30 = fConst13 + 7.60754167271764e-56;
		fConst31 = -7.17715343346006e-56 - fConst15;
		fConst32 = fConst0 * (fConst17 + -7.44216743501989e-12) + -3.21607474370948e-11;
		fConst33 = fConst0 * (7.44787041826973e-12 - fConst19) + 3.21721587173494e-11;
		fConst34 = 7.07536443616085e-12 - fConst21;
		fConst35 = fConst23 + -7.07787491781686e-12;
		fConst36 = 2.51786247207522e-17 * fConst0;
		fConst37 = 5.60496524842164e-17 * fConst0;
		fConst38 = fConst0 * (fConst0 * (fConst36 + -1.61641996632585e-12) + 1.6091784998802e-10 + fConst0 * (1.63110208134281e-12 - fConst37) + -1.69410806769336e-10);
		fConst39 = 1.1177069911304e-19 * fConst0;
		fConst40 = fConst0 * (fConst39 + -3.24149709132582e-15) + 1.46288954534563e-14;
		fConst41 = 1.42392288693486e-16 * fConst0;
		fConst42 = fConst0 * (fConst41 + -6.43214948741896e-16) + -3.45797348759893e-55;
		fConst43 = 1.42504059392599e-16 * fConst0;
		fConst44 = fConst0 * (6.43443174346988e-16 - fConst43) + 3.26234246975457e-55;
		fConst45 = 5.02096331201311e-20 * fConst0;
		fConst46 = fConst0 * (fConst0 * (3.21835699976039e-15 - fConst45) + 1.53335572595511e-54);
		fConst47 = 1.41507288723217e-16 * fConst0;
		fConst48 = -7.60754167271764e-56 - fConst47;
		fConst49 = 1.41557498356337e-16 * fConst0;
		fConst50 = fConst49 + 7.17715343346006e-56;
		fConst51 = 7.14054610111223e-14 * fConst0;
		fConst52 = fConst0 * (7.44216743501989e-12 - fConst51) + -3.21607474370948e-11;
		fConst53 = 7.14615106636066e-14 * fConst0;
		fConst54 = fConst0 * (fConst53 + -7.44787041826973e-12) + 3.21721587173494e-11;
		fConst55 = 7.09616600760317e-14 * fConst0;
		fConst56 = fConst55 + -7.07536443616085e-12;
		fConst57 = 7.09868387007524e-14 * fConst0;
		fConst58 = 7.07787491781686e-12 - fConst57;
		fConst59 = fConst0 * (fConst0 * (fConst37 + 1.63110208134281e-12) + 1.69410806769336e-10 + fConst0 * (-1.61641996632585e-12 - fConst36) + -1.6091784998802e-10);
		fConst60 = fConst0 * (-3.24149709132582e-15 - fConst39) + -1.46288954534563e-14;
		fConst61 = fConst0 * (-6.43214948741896e-16 - fConst41) + 3.45797348759893e-55;
		fConst62 = fConst0 * (fConst43 + 6.43443174346988e-16) + -3.26234246975457e-55;
		fConst63 = fConst0 * (fConst0 * (fConst45 + 3.21835699976039e-15) + -1.53335572595511e-54);
		fConst64 = fConst47 + -7.60754167271764e-56;
		fConst65 = 7.17715343346006e-56 - fConst49;
		fConst66 = fConst0 * (fConst51 + 7.44216743501989e-12) + 3.21607474370948e-11;
		fConst67 = fConst0 * (-7.44787041826973e-12 - fConst53) + -3.21721587173494e-11;
		fConst68 = -7.07536443616085e-12 - fConst55;
		fConst69 = fConst57 + 7.07787491781686e-12;
		fConst70 = 2.0681037922594e-13 * fConst0;
		fConst71 = 1.65448303380752e-13 * fConst0;
		fConst72 = fConst12 * (fConst70 + 4.74739615579661e-12 + (-3.79791692463729e-12 - fConst71));
		fConst73 = 1.12549866245409e-13 * fConst0;
		fConst74 = 1.40687332806762e-13 * fConst0;
		fConst75 = fConst12 * (fConst73 + 2.58361695553557e-12 + (-3.22952119441946e-12 - fConst74));
		fConst76 = OtFuzzFace_faustpower3_f(fConst0);
		fConst77 = 4.96344910142255e-13 * fConst0;
		fConst78 = 6.20431137677819e-13 * fConst0;
		fConst79 = fConst12 * (fConst77 + 3.79791692463729e-12 + (-4.74739615579661e-12 - fConst78));
		fConst80 = 4.22061998420285e-13 * fConst0;
		fConst81 = 3.37649598736228e-13 * fConst0;
		fConst82 = fConst12 * (fConst80 + 3.22952119441946e-12 + (-2.58361695553557e-12 - fConst81));
		fConst83 = fConst12 * (3.79791692463729e-12 - fConst77 + fConst78 + -4.74739615579661e-12);
		fConst84 = fConst12 * (fConst81 + -2.58361695553557e-12 + (3.22952119441946e-12 - fConst80));
		fConst85 = fConst12 * (fConst71 + -3.79791692463729e-12 + (4.74739615579661e-12 - fConst70));
		fConst86 = fConst12 * (2.58361695553557e-12 - fConst73 + fConst74 + -3.22952119441946e-12);
	}
	
	inline void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(0.5);
		fVslider0 = static_cast<float>(0.5);
	}
	
	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fRec1[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec2[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 4; l2 = l2 + 1) {
			fRec0[l2] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
		
	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = 0.007000000000000006 * (1.0 - static_cast<double>(fHslider0));
		double fSlow1 = 0.007000000000000006 * (1.0 - static_cast<double>(fVslider0));
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			fRec1[0] = fSlow0 + 0.993 * fRec1[1];
			fRec2[0] = fSlow1 + 0.993 * fRec2[1];
			double fTemp0 = fConst59 + fRec1[0] * (fConst0 * (fConst60 + fRec2[0] * (fConst61 + fConst62 * fRec2[0])) + 6.96979875434139e-54 + fConst63 + fConst12 * fRec2[0] * (fConst64 + fConst65 * fRec2[0])) + fRec2[0] * (fConst0 * (fConst66 + fConst67 * fRec2[0]) + fConst12 * (fConst68 + fConst69 * fRec2[0])) + 7.31444772672817e-10;
			fRec0[0] = static_cast<double>(input0[i0]) - (fRec0[1] * (fConst3 + fRec1[0] * (fConst0 * (fConst5 + fRec2[0] * (fConst7 + fConst9 * fRec2[0])) + 2.09093962630242e-53 + fConst11 + fConst12 * fRec2[0] * (fConst14 + fConst16 * fRec2[0])) + fRec2[0] * (fConst0 * (fConst18 + fConst20 * fRec2[0]) + fConst12 * (fConst22 + fConst24 * fRec2[0])) + 2.19433431801845e-09) + fRec0[2] * (fConst25 + fRec1[0] * (fConst0 * (fConst26 + fRec2[0] * (fConst27 + fConst28 * fRec2[0])) + 2.09093962630242e-53 + fConst29 + fConst12 * fRec2[0] * (fConst30 + fConst31 * fRec2[0])) + fRec2[0] * (fConst0 * (fConst32 + fConst33 * fRec2[0]) + fConst12 * (fConst34 + fConst35 * fRec2[0])) + 2.19433431801845e-09) + fRec0[3] * (fConst38 + fRec1[0] * (fConst0 * (fConst40 + fRec2[0] * (fConst42 + fConst44 * fRec2[0])) + 6.96979875434139e-54 + fConst46 + fConst12 * fRec2[0] * (fConst48 + fConst50 * fRec2[0])) + fRec2[0] * (fConst0 * (fConst52 + fConst54 * fRec2[0]) + fConst12 * (fConst56 + fConst58 * fRec2[0])) + 7.31444772672817e-10)) / fTemp0;
			double fTemp1 = 2.8231994953894e-16 * fRec2[0];
			double fTemp2 = 4.1501032582223993e-16 * fRec2[0];
			double fTemp3 = 8.4695984861682025e-16 * fRec2[0];
			double fTemp4 = 1.2450309774667304e-15 * fRec2[0];
			output0[i0] = static_cast<float>((fRec0[0] * (fConst72 + fRec1[0] * (fConst75 + fConst76 * fRec2[0] * (fTemp1 + -1.11420586447254e-13 + 1.39275733059067e-13)) + fConst76 * fRec2[0] * (1.63788262077463e-13 - fTemp2 + -2.04735327596828e-13)) + fRec0[1] * (fConst79 + fRec1[0] * (fConst82 + fConst76 * fRec2[0] * (3.34261759341761e-13 - fTemp3 + -4.17827199177201e-13)) + fConst76 * fRec2[0] * (fTemp4 + -4.91364786232388e-13 + 6.14205982790485e-13)) + fRec0[2] * (fConst83 + fRec1[0] * (fConst84 + fConst76 * fRec2[0] * (fTemp3 + -3.34261759341761e-13 + 4.17827199177201e-13)) + fConst76 * fRec2[0] * (4.91364786232388e-13 - fTemp4 + -6.14205982790485e-13)) + fRec0[3] * (fConst85 + fRec1[0] * (fConst86 + fConst76 * fRec2[0] * (1.11420586447254e-13 - fTemp1 + -1.39275733059067e-13)) + fConst76 * fRec2[0] * (fTemp2 + -1.63788262077463e-13 + 2.04735327596828e-13))) / fTemp0);
			fRec1[1] = fRec1[0];
			fRec2[1] = fRec2[0];
			for (int j0 = 3; j0 > 0; j0 = j0 - 1) {
				fRec0[j0] = fRec0[j0 - 1];
			}
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("FuzzFace");
		changed |= editDrive();
		ImGui::SameLine();
		changed |= editFuzz();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float drive = 0.5f;
		float fuzz = 0.5f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider0 = parameters.drive;
		fVslider0 = parameters.fuzz;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.drive = fHslider0;
		parameters.fuzz = fVslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("drive", &fHslider0, 0.5f);
		callback("fuzz", &fVslider0, 0.5f);
	}

	inline bool editDrive() { return OtUi::knob("Drive", &fHslider0, 0.0f, 1.0f, "%.2f", false); }
	inline bool editFuzz() { return OtUi::knob("Fuzz", &fVslider0, 0.0f, 1.0f, "%.2f", false); }

	inline void setDrive(float value) { fHslider0 = value; }
	inline void setFuzz(float value) { fVslider0 = value; }

	inline float getDrive() { return fHslider0; }
	inline float getFuzz() { return fVslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
