//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated by source/build.py
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"


//
//  OtFuzzFace
//

static double OtFuzzFace_faustpower3_f(double value) {
	return value * value * value;
}
static double OtFuzzFace_faustpower2_f(double value) {
	return value * value;
}

class OtFuzzFace : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	double fConst2;
	float fVslider0;
	double fRec1[2];
	double fConst3;
	double fConst4;
	double fConst5;
	double fConst6;
	double fConst7;
	double fConst8;
	double fConst9;
	double fConst10;
	double fConst11;
	double fConst12;
	double fConst13;
	double fConst14;
	double fConst15;
	double fConst16;
	double fConst17;
	double fConst18;
	double fConst19;
	double fConst20;
	double fConst21;
	double fConst22;
	double fConst23;
	double fConst24;
	double fRec0[6];
	double fConst25;
	double fConst26;
	double fConst27;
	double fConst28;
	double fConst29;
	float fHslider0;
	double fRec2[2];
	double fConst30;
	double fConst31;
	double fConst32;
	double fConst33;
	double fConst34;
	double fConst35;
	double fConst36;
	double fConst37;
	double fConst38;
	double fConst39;
	double fConst40;
	double fConst41;
	double fConst42;
	double fConst43;
	double fConst44;
	double fConst45;
	double fConst46;
	double fConst47;
	double fConst48;
	double fConst49;
	double fConst50;
	double fConst51;
	double fConst52;
	double fConst53;
	double fConst54;
	double fConst55;
	double fConst56;
	double fConst57;
	double fConst58;
	double fConst59;
	double fConst60;
	double fConst61;
	double fConst62;
	double fConst63;

public:
	OtFuzzFace() {
		init(OtAudioSettings::sampleRate);
	}

	inline void metadata(Meta* m) {
		m->declare("category", "Distortion");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtFuzzFace -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("description", "Jimmy Hendrix Fuzz Face simulation");
		m->declare("filename", "OtFuzzFace.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Fuzz Face");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 1.19695732274265e-21 * fConst0;
		fConst2 = fConst0 * (fConst0 * (-1.99042653510896e-15 - fConst1) + 1.83615604104971e-13) + 1.59369187419145e-10;
		fConst3 = 1.86646037645036e-28 * fConst0;
		fConst4 = fConst0 * (fConst0 * (fConst0 * (-3.04929833179984e-20 - fConst3) + -2.91602352831988e-14) + 2.29636966370042e-11) + 3.22347316362488e-09;
		fConst5 = fConst0 * (fConst0 * (fConst0 * (fConst3 + 3.16899403862238e-20) + 3.11506369039915e-14) + -2.30719916990074e-11) + -3.22479494130986e-09;
		fConst6 = 7.97971548495099e-22 * fConst0;
		fConst7 = fConst0 * (fConst0 * (fConst6 + -3.98085307021793e-15) + -3.67231208209942e-13) + 1.06246124946097e-10;
		fConst8 = 3.73292075290073e-28 * fConst0;
		fConst9 = fConst0 * (fConst0 * (fConst0 * (fConst8 + 2.03286555453323e-20) + -5.83204705663976e-14) + -4.59273932740084e-11) + 2.14898210908325e-09;
		fConst10 = fConst0 * (fConst0 * (fConst0 * (-2.11266269241492e-20 - fConst8) + 6.2301273807983e-14) + 4.61439833980148e-11) + -2.14986329420657e-09;
		fConst11 = fConst0 * (fConst0 * (fConst6 + 3.98085307021793e-15) + -3.67231208209942e-13) + -1.06246124946097e-10;
		fConst12 = fConst0 * (fConst0 * (fConst0 * (2.03286555453323e-20 - fConst8) + 5.83204705663976e-14) + -4.59273932740084e-11) + -2.14898210908325e-09;
		fConst13 = fConst0 * (fConst0 * (fConst0 * (fConst8 + -2.11266269241492e-20) + -6.2301273807983e-14) + 4.61439833980148e-11) + 2.14986329420657e-09;
		fConst14 = fConst0 * (fConst0 * (1.99042653510896e-15 - fConst1) + 1.83615604104971e-13) + -1.59369187419145e-10;
		fConst15 = fConst0 * (fConst0 * (fConst0 * (fConst3 + -3.04929833179984e-20) + 2.91602352831988e-14) + 2.29636966370042e-11) + -3.22347316362488e-09;
		fConst16 = fConst0 * (fConst0 * (fConst0 * (3.16899403862238e-20 - fConst3) + -3.11506369039915e-14) + -2.30719916990074e-11) + 3.22479494130986e-09;
		fConst17 = 3.98985774247549e-22 * fConst0;
		fConst18 = fConst0 * (fConst0 * (fConst17 + -1.99042653510896e-15) + 1.83615604104971e-13) + -5.31230624730483e-11;
		fConst19 = 3.73292075290073e-29 * fConst0;
		fConst20 = fConst0 * (fConst0 * (fConst0 * (1.01643277726662e-20 - fConst19) + -2.91602352831988e-14) + 2.29636966370042e-11) + -1.07449105454163e-09;
		fConst21 = fConst0 * (fConst0 * (fConst0 * (fConst19 + -1.05633134620746e-20) + 3.11506369039915e-14) + -2.30719916990074e-11) + 1.07493164710329e-09;
		fConst22 = fConst0 * (fConst0 * (fConst17 + 1.99042653510896e-15) + 1.83615604104971e-13) + 5.31230624730483e-11;
		fConst23 = fConst0 * (fConst0 * (fConst0 * (fConst19 + 1.01643277726662e-20) + 2.91602352831988e-14) + 2.29636966370042e-11) + 1.07449105454163e-09;
		fConst24 = fConst0 * (fConst0 * (fConst0 * (-1.05633134620746e-20 - fConst19) + -3.11506369039915e-14) + -2.30719916990074e-11) + -1.07493164710329e-09;
		fConst25 = OtFuzzFace_faustpower3_f(fConst0);
		fConst26 = 4.76991513499346e-20 * fConst0;
		fConst27 = fConst26 + -5.00346713698171e-13;
		fConst28 = -5.38351707988916e-15 - fConst26;
		fConst29 = fConst26 + 5.38351707988916e-15;
		fConst30 = 5.00346713698171e-13 - fConst26;
		fConst31 = OtFuzzFace_faustpower2_f(fConst0);
		fConst32 = 5.05730339185222e-13 * fConst0;
		fConst33 = fConst32 + 1.16162215422261e-12;
		fConst34 = -1.16162215422261e-12 - fConst32;
		fConst35 = 1.43097454049804e-19 * fConst0;
		fConst36 = 5.00346713698171e-13 - fConst35;
		fConst37 = fConst35 + 5.38351707988916e-15;
		fConst38 = -5.38351707988916e-15 - fConst35;
		fConst39 = fConst35 + -5.00346713698171e-13;
		fConst40 = 1.16162215422261e-12 - fConst32;
		fConst41 = fConst32 + -1.16162215422261e-12;
		fConst42 = 9.53983026998693e-20 * fConst0;
		fConst43 = fConst42 + 1.00069342739634e-12;
		fConst44 = 1.07670341597783e-14 - fConst42;
		fConst45 = fConst42 + -1.07670341597783e-14;
		fConst46 = -1.00069342739634e-12 - fConst42;
		fConst47 = 1.01146067837044e-12 * fConst0;
		fConst48 = -2.32324430844522e-12 - fConst47;
		fConst49 = fConst47 + 2.32324430844522e-12;
		fConst50 = fConst42 + -1.00069342739634e-12;
		fConst51 = -1.07670341597783e-14 - fConst42;
		fConst52 = fConst42 + 1.07670341597783e-14;
		fConst53 = 1.00069342739634e-12 - fConst42;
		fConst54 = fConst47 + -2.32324430844522e-12;
		fConst55 = 2.32324430844522e-12 - fConst47;
		fConst56 = -5.00346713698171e-13 - fConst35;
		fConst57 = fConst35 + -5.38351707988916e-15;
		fConst58 = 5.38351707988916e-15 - fConst35;
		fConst59 = fConst35 + 5.00346713698171e-13;
		fConst60 = fConst26 + 5.00346713698171e-13;
		fConst61 = 5.38351707988916e-15 - fConst26;
		fConst62 = fConst26 + -5.38351707988916e-15;
		fConst63 = -5.00346713698171e-13 - fConst26;
	}

	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(0.5);
		fHslider0 = static_cast<float>(0.5);
	}

	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fRec1[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 6; l1 = l1 + 1) {
			fRec0[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec2[l2] = 0.0;
		}
	}

	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	inline int getSampleRate() {
		return fSampleRate;
	}

	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = 0.007000000000000006 * (1.0 - static_cast<double>(fVslider0));
		double fSlow1 = 0.007000000000000006 * (1.0 - static_cast<double>(fHslider0));
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			fRec1[0] = fSlow0 + 0.993 * fRec1[1];
			double fTemp0 = fConst0 * (fConst22 + fRec1[0] * (fConst23 + fConst24 * fRec1[0])) + 2.44402781742033e-09;
			fRec0[0] = static_cast<double>(input0[i0]) - (fRec0[1] * (fConst0 * (fConst2 + fRec1[0] * (fConst4 + fConst5 * fRec1[0])) + 1.22201390871017e-08) + fRec0[2] * (fConst0 * (fConst7 + fRec1[0] * (fConst9 + fConst10 * fRec1[0])) + 2.44402781742033e-08) + fRec0[3] * (fConst0 * (fConst11 + fRec1[0] * (fConst12 + fConst13 * fRec1[0])) + 2.44402781742033e-08) + fRec0[4] * (fConst0 * (fConst14 + fRec1[0] * (fConst15 + fConst16 * fRec1[0])) + 1.22201390871017e-08) + fRec0[5] * (fConst0 * (fConst18 + fRec1[0] * (fConst20 + fConst21 * fRec1[0])) + 2.44402781742033e-09)) / fTemp0;
			fRec2[0] = fSlow1 + 0.993 * fRec2[1];
			double fTemp1 = fConst31 * (fConst33 + fConst34 * fRec2[0]);
			double fTemp2 = fConst31 * (fConst40 + fConst41 * fRec2[0]);
			output0[i0] = static_cast<float>(0.2 * ((fRec0[0] * (fConst25 * fRec1[0] * (fConst27 + fRec1[0] * (fConst28 + fConst29 * fRec2[0]) + fConst30 * fRec2[0]) + fTemp1) + fRec0[1] * (fConst25 * fRec1[0] * (fConst36 + fRec1[0] * (fConst37 + fConst38 * fRec2[0]) + fConst39 * fRec2[0]) + fTemp2) + fRec0[2] * (fConst25 * fRec1[0] * (fConst43 + fRec1[0] * (fConst44 + fConst45 * fRec2[0]) + fConst46 * fRec2[0]) + fConst31 * (fConst48 + fConst49 * fRec2[0])) + fRec0[3] * (fConst25 * fRec1[0] * (fConst50 + fRec1[0] * (fConst51 + fConst52 * fRec2[0]) + fConst53 * fRec2[0]) + fConst31 * (fConst54 + fConst55 * fRec2[0])) + fRec0[4] * (fTemp1 + fConst25 * fRec1[0] * (fConst56 + fRec1[0] * (fConst57 + fConst58 * fRec2[0]) + fConst59 * fRec2[0])) + fRec0[5] * (fTemp2 + fConst25 * fRec1[0] * (fConst60 + fRec1[0] * (fConst61 + fConst62 * fRec2[0]) + fConst63 * fRec2[0]))) / fTemp0));
			fRec1[1] = fRec1[0];
			for (int j0 = 5; j0 > 0; j0 = j0 - 1) {
				fRec0[j0] = fRec0[j0 - 1];
			}
			fRec2[1] = fRec2[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("FuzzFace");
		changed |= editDrive();
		ImGui::SameLine();
		changed |= editFuzz();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float drive = 0.5f;
		float fuzz = 0.5f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider0 = parameters.drive;
		fVslider0 = parameters.fuzz;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.drive = fHslider0;
		parameters.fuzz = fVslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("drive", &fHslider0, 0.5f);
		callback("fuzz", &fVslider0, 0.5f);
	}

	inline bool editDrive() { return OtUi::knob("Drive", &fHslider0, 0.0f, 1.0f, "%.2f", false); }
	inline bool editFuzz() { return OtUi::knob("Fuzz", &fVslider0, 0.0f, 1.0f, "%.2f", false); }

	inline void setDrive(float value) { fHslider0 = value; }
	inline void setFuzz(float value) { fVslider0 = value; }

	inline float getDrive() { return fHslider0; }
	inline float getFuzz() { return fVslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
