//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated by source/build.py
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"


//
//  OtGraphicEQ
//

static double OtGraphicEQ_faustpower2_f(double value) {
	return value * value;
}

class OtGraphicEQ : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	double fConst2;
	double fConst3;
	double fConst4;
	double fConst5;
	double fConst6;
	double fConst7;
	double fConst8;
	double fConst9;
	double fVec0[2];
	double fRec10[2];
	double fConst10;
	double fConst11;
	double fConst12;
	double fRec9[3];
	double fConst13;
	double fConst14;
	double fRec8[3];
	double fConst15;
	double fConst16;
	double fConst17;
	double fConst18;
	double fConst19;
	double fConst20;
	double fConst21;
	double fRec7[3];
	double fConst22;
	double fConst23;
	double fConst24;
	double fConst25;
	double fConst26;
	double fConst27;
	double fRec6[3];
	double fConst28;
	double fConst29;
	double fConst30;
	double fConst31;
	double fConst32;
	double fConst33;
	double fRec5[3];
	double fConst34;
	double fConst35;
	double fConst36;
	double fConst37;
	double fConst38;
	double fConst39;
	double fRec4[3];
	double fConst40;
	double fConst41;
	double fConst42;
	double fConst43;
	double fConst44;
	double fConst45;
	double fRec3[3];
	double fConst46;
	double fConst47;
	double fConst48;
	double fConst49;
	double fConst50;
	double fConst51;
	double fRec2[3];
	double fConst52;
	double fConst53;
	double fConst54;
	double fConst55;
	double fConst56;
	double fConst57;
	double fRec1[3];
	double fConst58;
	double fConst59;
	double fConst60;
	double fConst61;
	double fConst62;
	double fConst63;
	double fRec0[3];
	double fConst64;
	float fVslider0;
	double fConst65;
	double fRec11[2];
	double fConst66;
	double fConst67;
	double fConst68;
	double fConst69;
	double fConst70;
	double fConst71;
	double fConst72;
	double fRec24[2];
	double fRec23[3];
	double fRec22[3];
	double fVec1[2];
	double fRec21[2];
	double fConst73;
	double fConst74;
	double fRec20[3];
	double fConst75;
	double fConst76;
	double fRec19[3];
	double fRec18[3];
	double fRec17[3];
	double fRec16[3];
	double fRec15[3];
	double fRec14[3];
	double fRec13[3];
	double fRec12[3];
	float fVslider1;
	double fRec25[2];
	double fConst77;
	double fConst78;
	double fConst79;
	double fConst80;
	double fConst81;
	double fConst82;
	double fConst83;
	double fRec37[2];
	double fRec36[3];
	double fRec35[3];
	double fVec2[2];
	double fRec34[2];
	double fConst84;
	double fConst85;
	double fRec33[3];
	double fConst86;
	double fConst87;
	double fRec32[3];
	double fRec31[3];
	double fRec30[3];
	double fRec29[3];
	double fRec28[3];
	double fRec27[3];
	double fRec26[3];
	float fVslider2;
	double fRec38[2];
	double fConst88;
	double fConst89;
	double fConst90;
	double fConst91;
	double fConst92;
	double fConst93;
	double fConst94;
	double fRec49[2];
	double fRec48[3];
	double fRec47[3];
	double fVec3[2];
	double fRec46[2];
	double fConst95;
	double fConst96;
	double fRec45[3];
	double fConst97;
	double fConst98;
	double fRec44[3];
	double fRec43[3];
	double fRec42[3];
	double fRec41[3];
	double fRec40[3];
	double fRec39[3];
	float fVslider3;
	double fRec50[2];
	double fConst99;
	double fConst100;
	double fConst101;
	double fConst102;
	double fConst103;
	double fConst104;
	double fConst105;
	double fRec60[2];
	double fRec59[3];
	double fRec58[3];
	double fVec4[2];
	double fRec57[2];
	double fConst106;
	double fConst107;
	double fRec56[3];
	double fConst108;
	double fConst109;
	double fRec55[3];
	double fRec54[3];
	double fRec53[3];
	double fRec52[3];
	double fRec51[3];
	float fVslider4;
	double fRec61[2];
	double fConst110;
	double fConst111;
	double fConst112;
	double fConst113;
	double fConst114;
	double fConst115;
	double fConst116;
	double fRec70[2];
	double fRec69[3];
	double fRec68[3];
	double fVec5[2];
	double fRec67[2];
	double fConst117;
	double fConst118;
	double fRec66[3];
	double fConst119;
	double fConst120;
	double fRec65[3];
	double fRec64[3];
	double fRec63[3];
	double fRec62[3];
	float fVslider5;
	double fRec71[2];
	double fConst121;
	double fConst122;
	double fConst123;
	double fConst124;
	double fConst125;
	double fConst126;
	double fConst127;
	double fRec79[2];
	double fRec78[3];
	double fRec77[3];
	double fVec6[2];
	double fRec76[2];
	double fConst128;
	double fConst129;
	double fRec75[3];
	double fConst130;
	double fConst131;
	double fRec74[3];
	double fRec73[3];
	double fRec72[3];
	float fVslider6;
	double fRec80[2];
	double fConst132;
	double fConst133;
	double fConst134;
	double fConst135;
	double fConst136;
	double fConst137;
	double fConst138;
	double fRec87[2];
	double fRec86[3];
	double fRec85[3];
	double fVec7[2];
	double fRec84[2];
	double fConst139;
	double fConst140;
	double fRec83[3];
	double fConst141;
	double fConst142;
	double fRec82[3];
	double fRec81[3];
	float fVslider7;
	double fRec88[2];
	double fConst143;
	double fConst144;
	double fConst145;
	double fConst146;
	double fConst147;
	double fRec94[2];
	double fRec93[3];
	double fRec92[3];
	double fVec8[2];
	double fRec91[2];
	double fConst148;
	double fRec90[3];
	double fConst149;
	double fRec89[3];
	float fVslider8;
	double fRec95[2];
	double fConst150;
	double fConst151;
	double fRec98[2];
	double fRec97[3];
	double fRec96[3];
	float fVslider9;
	double fRec99[2];

public:
	OtGraphicEQ() {
		init(OtAudioSettings::sampleRate);
	}

	inline void metadata(Meta* m) {
		m->declare("analyzers.lib/name", "Faust Analyzer Library");
		m->declare("analyzers.lib/version", "1.3.0");
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Equalizer");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtGraphicEQ -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtGraphicEQ.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/highpass:author", "Julius O. Smith III");
		m->declare("filters.lib/highpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/highpass_plus_lowpass:author", "Julius O. Smith III");
		m->declare("filters.lib/highpass_plus_lowpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/highpass_plus_lowpass:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowpass0_highpass1:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowpass:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/mth_octave_filterbank5:author", "Julius O. Smith III");
		m->declare("filters.lib/mth_octave_filterbank5:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/mth_octave_filterbank5:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/mth_octave_filterbank:author", "Julius O. Smith III");
		m->declare("filters.lib/mth_octave_filterbank:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/mth_octave_filterbank:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/mth_octave_filterbank_default:author", "Julius O. Smith III");
		m->declare("filters.lib/mth_octave_filterbank_default:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/mth_octave_filterbank_default:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/tf1:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf1s:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1s:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2s:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2s:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Graphic EQ");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = std::tan(50265.48245743669 / fConst0);
		fConst2 = OtGraphicEQ_faustpower2_f(fConst1);
		fConst3 = 1.0 / fConst1;
		fConst4 = (fConst3 + 0.6180339887498947) / fConst1 + 1.0;
		fConst5 = 1.0 / (fConst2 * fConst4);
		fConst6 = (fConst3 + 1.6180339887498947) / fConst1 + 1.0;
		fConst7 = 1.0 / (fConst2 * fConst6);
		fConst8 = 1.0 / (fConst3 + 1.0);
		fConst9 = 1.0 - fConst3;
		fConst10 = 1.0 / fConst6;
		fConst11 = (fConst3 + -1.6180339887498947) / fConst1 + 1.0;
		fConst12 = 2.0 * (1.0 - 1.0 / fConst2);
		fConst13 = 1.0 / fConst4;
		fConst14 = (fConst3 + -0.6180339887498947) / fConst1 + 1.0;
		fConst15 = std::tan(196.34954084936206 / fConst0);
		fConst16 = 1.0 / fConst15;
		fConst17 = 1.0 / ((fConst16 + 1.618033988749895) / fConst15 + 1.0);
		fConst18 = (fConst16 + -1.618033988749895) / fConst15 + 1.0;
		fConst19 = OtGraphicEQ_faustpower2_f(fConst15);
		fConst20 = 1.0 / fConst19;
		fConst21 = 2.0 * (1.0 - fConst20);
		fConst22 = std::tan(392.6990816987241 / fConst0);
		fConst23 = 1.0 / fConst22;
		fConst24 = 1.0 / ((fConst23 + 1.618033988749895) / fConst22 + 1.0);
		fConst25 = (fConst23 + -1.618033988749895) / fConst22 + 1.0;
		fConst26 = OtGraphicEQ_faustpower2_f(fConst22);
		fConst27 = 2.0 * (1.0 - 1.0 / fConst26);
		fConst28 = std::tan(785.3981633974482 / fConst0);
		fConst29 = 1.0 / fConst28;
		fConst30 = 1.0 / ((fConst29 + 1.618033988749895) / fConst28 + 1.0);
		fConst31 = (fConst29 + -1.618033988749895) / fConst28 + 1.0;
		fConst32 = OtGraphicEQ_faustpower2_f(fConst28);
		fConst33 = 2.0 * (1.0 - 1.0 / fConst32);
		fConst34 = std::tan(1570.7963267948965 / fConst0);
		fConst35 = 1.0 / fConst34;
		fConst36 = 1.0 / ((fConst35 + 1.618033988749895) / fConst34 + 1.0);
		fConst37 = (fConst35 + -1.618033988749895) / fConst34 + 1.0;
		fConst38 = OtGraphicEQ_faustpower2_f(fConst34);
		fConst39 = 2.0 * (1.0 - 1.0 / fConst38);
		fConst40 = std::tan(3141.592653589793 / fConst0);
		fConst41 = 1.0 / fConst40;
		fConst42 = 1.0 / ((fConst41 + 1.618033988749895) / fConst40 + 1.0);
		fConst43 = (fConst41 + -1.618033988749895) / fConst40 + 1.0;
		fConst44 = OtGraphicEQ_faustpower2_f(fConst40);
		fConst45 = 2.0 * (1.0 - 1.0 / fConst44);
		fConst46 = std::tan(6283.185307179586 / fConst0);
		fConst47 = 1.0 / fConst46;
		fConst48 = 1.0 / ((fConst47 + 1.618033988749895) / fConst46 + 1.0);
		fConst49 = (fConst47 + -1.618033988749895) / fConst46 + 1.0;
		fConst50 = OtGraphicEQ_faustpower2_f(fConst46);
		fConst51 = 2.0 * (1.0 - 1.0 / fConst50);
		fConst52 = std::tan(12566.370614359172 / fConst0);
		fConst53 = 1.0 / fConst52;
		fConst54 = 1.0 / ((fConst53 + 1.618033988749895) / fConst52 + 1.0);
		fConst55 = (fConst53 + -1.618033988749895) / fConst52 + 1.0;
		fConst56 = OtGraphicEQ_faustpower2_f(fConst52);
		fConst57 = 2.0 * (1.0 - 1.0 / fConst56);
		fConst58 = std::tan(25132.741228718343 / fConst0);
		fConst59 = 1.0 / fConst58;
		fConst60 = 1.0 / ((fConst59 + 1.618033988749895) / fConst58 + 1.0);
		fConst61 = (fConst59 + -1.618033988749895) / fConst58 + 1.0;
		fConst62 = OtGraphicEQ_faustpower2_f(fConst58);
		fConst63 = 2.0 * (1.0 - 1.0 / fConst62);
		fConst64 = 44.1 / fConst0;
		fConst65 = 1.0 - fConst64;
		fConst66 = (fConst59 + 0.6180339887498947) / fConst58 + 1.0;
		fConst67 = 1.0 / (fConst62 * fConst66);
		fConst68 = (fConst59 + 1.6180339887498947) / fConst58 + 1.0;
		fConst69 = 1.0 / (fConst62 * fConst68);
		fConst70 = 1.0 / (fConst59 + 1.0);
		fConst71 = 1.0 - fConst59;
		fConst72 = 1.0 / (fConst58 * fConst4);
		fConst73 = 1.0 / fConst68;
		fConst74 = (fConst59 + -1.6180339887498947) / fConst58 + 1.0;
		fConst75 = 1.0 / fConst66;
		fConst76 = (fConst59 + -0.6180339887498947) / fConst58 + 1.0;
		fConst77 = (fConst53 + 0.6180339887498947) / fConst52 + 1.0;
		fConst78 = 1.0 / (fConst56 * fConst77);
		fConst79 = (fConst53 + 1.6180339887498947) / fConst52 + 1.0;
		fConst80 = 1.0 / (fConst56 * fConst79);
		fConst81 = 1.0 / (fConst53 + 1.0);
		fConst82 = 1.0 - fConst53;
		fConst83 = 1.0 / (fConst52 * fConst66);
		fConst84 = 1.0 / fConst79;
		fConst85 = (fConst53 + -1.6180339887498947) / fConst52 + 1.0;
		fConst86 = 1.0 / fConst77;
		fConst87 = (fConst53 + -0.6180339887498947) / fConst52 + 1.0;
		fConst88 = (fConst47 + 0.6180339887498947) / fConst46 + 1.0;
		fConst89 = 1.0 / (fConst50 * fConst88);
		fConst90 = (fConst47 + 1.6180339887498947) / fConst46 + 1.0;
		fConst91 = 1.0 / (fConst50 * fConst90);
		fConst92 = 1.0 / (fConst47 + 1.0);
		fConst93 = 1.0 - fConst47;
		fConst94 = 1.0 / (fConst46 * fConst77);
		fConst95 = 1.0 / fConst90;
		fConst96 = (fConst47 + -1.6180339887498947) / fConst46 + 1.0;
		fConst97 = 1.0 / fConst88;
		fConst98 = (fConst47 + -0.6180339887498947) / fConst46 + 1.0;
		fConst99 = (fConst41 + 0.6180339887498947) / fConst40 + 1.0;
		fConst100 = 1.0 / (fConst44 * fConst99);
		fConst101 = (fConst41 + 1.6180339887498947) / fConst40 + 1.0;
		fConst102 = 1.0 / (fConst44 * fConst101);
		fConst103 = 1.0 / (fConst41 + 1.0);
		fConst104 = 1.0 - fConst41;
		fConst105 = 1.0 / (fConst40 * fConst88);
		fConst106 = 1.0 / fConst101;
		fConst107 = (fConst41 + -1.6180339887498947) / fConst40 + 1.0;
		fConst108 = 1.0 / fConst99;
		fConst109 = (fConst41 + -0.6180339887498947) / fConst40 + 1.0;
		fConst110 = (fConst35 + 0.6180339887498947) / fConst34 + 1.0;
		fConst111 = 1.0 / (fConst38 * fConst110);
		fConst112 = (fConst35 + 1.6180339887498947) / fConst34 + 1.0;
		fConst113 = 1.0 / (fConst38 * fConst112);
		fConst114 = 1.0 / (fConst35 + 1.0);
		fConst115 = 1.0 - fConst35;
		fConst116 = 1.0 / (fConst34 * fConst99);
		fConst117 = 1.0 / fConst112;
		fConst118 = (fConst35 + -1.6180339887498947) / fConst34 + 1.0;
		fConst119 = 1.0 / fConst110;
		fConst120 = (fConst35 + -0.6180339887498947) / fConst34 + 1.0;
		fConst121 = (fConst29 + 0.6180339887498947) / fConst28 + 1.0;
		fConst122 = 1.0 / (fConst32 * fConst121);
		fConst123 = (fConst29 + 1.6180339887498947) / fConst28 + 1.0;
		fConst124 = 1.0 / (fConst32 * fConst123);
		fConst125 = 1.0 / (fConst29 + 1.0);
		fConst126 = 1.0 - fConst29;
		fConst127 = 1.0 / (fConst28 * fConst110);
		fConst128 = 1.0 / fConst123;
		fConst129 = (fConst29 + -1.6180339887498947) / fConst28 + 1.0;
		fConst130 = 1.0 / fConst121;
		fConst131 = (fConst29 + -0.6180339887498947) / fConst28 + 1.0;
		fConst132 = (fConst23 + 0.6180339887498947) / fConst22 + 1.0;
		fConst133 = 1.0 / (fConst26 * fConst132);
		fConst134 = (fConst23 + 1.6180339887498947) / fConst22 + 1.0;
		fConst135 = 1.0 / (fConst26 * fConst134);
		fConst136 = 1.0 / (fConst23 + 1.0);
		fConst137 = 1.0 - fConst23;
		fConst138 = 1.0 / (fConst22 * fConst121);
		fConst139 = 1.0 / fConst134;
		fConst140 = (fConst23 + -1.6180339887498947) / fConst22 + 1.0;
		fConst141 = 1.0 / fConst132;
		fConst142 = (fConst23 + -0.6180339887498947) / fConst22 + 1.0;
		fConst143 = 1.0 / ((fConst16 + 0.6180339887498947) / fConst15 + 1.0);
		fConst144 = (fConst16 + 1.6180339887498947) / fConst15 + 1.0;
		fConst145 = 1.0 / fConst144;
		fConst146 = 1.0 / (fConst16 + 1.0);
		fConst147 = 1.0 - fConst16;
		fConst148 = (fConst16 + -1.6180339887498947) / fConst15 + 1.0;
		fConst149 = (fConst16 + -0.6180339887498947) / fConst15 + 1.0;
		fConst150 = 1.0 / (fConst19 * fConst144);
		fConst151 = 1.0 / (fConst15 * fConst132);
	}

	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(-1e+01);
		fVslider1 = static_cast<float>(-1e+01);
		fVslider2 = static_cast<float>(-1e+01);
		fVslider3 = static_cast<float>(-1e+01);
		fVslider4 = static_cast<float>(-1e+01);
		fVslider5 = static_cast<float>(-1e+01);
		fVslider6 = static_cast<float>(-1e+01);
		fVslider7 = static_cast<float>(-1e+01);
		fVslider8 = static_cast<float>(-1e+01);
		fVslider9 = static_cast<float>(-1e+01);
	}

	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fVec0[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec10[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 3; l2 = l2 + 1) {
			fRec9[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 3; l3 = l3 + 1) {
			fRec8[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 3; l4 = l4 + 1) {
			fRec7[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 3; l5 = l5 + 1) {
			fRec6[l5] = 0.0;
		}
		for (int l6 = 0; l6 < 3; l6 = l6 + 1) {
			fRec5[l6] = 0.0;
		}
		for (int l7 = 0; l7 < 3; l7 = l7 + 1) {
			fRec4[l7] = 0.0;
		}
		for (int l8 = 0; l8 < 3; l8 = l8 + 1) {
			fRec3[l8] = 0.0;
		}
		for (int l9 = 0; l9 < 3; l9 = l9 + 1) {
			fRec2[l9] = 0.0;
		}
		for (int l10 = 0; l10 < 3; l10 = l10 + 1) {
			fRec1[l10] = 0.0;
		}
		for (int l11 = 0; l11 < 3; l11 = l11 + 1) {
			fRec0[l11] = 0.0;
		}
		for (int l12 = 0; l12 < 2; l12 = l12 + 1) {
			fRec11[l12] = 0.0;
		}
		for (int l13 = 0; l13 < 2; l13 = l13 + 1) {
			fRec24[l13] = 0.0;
		}
		for (int l14 = 0; l14 < 3; l14 = l14 + 1) {
			fRec23[l14] = 0.0;
		}
		for (int l15 = 0; l15 < 3; l15 = l15 + 1) {
			fRec22[l15] = 0.0;
		}
		for (int l16 = 0; l16 < 2; l16 = l16 + 1) {
			fVec1[l16] = 0.0;
		}
		for (int l17 = 0; l17 < 2; l17 = l17 + 1) {
			fRec21[l17] = 0.0;
		}
		for (int l18 = 0; l18 < 3; l18 = l18 + 1) {
			fRec20[l18] = 0.0;
		}
		for (int l19 = 0; l19 < 3; l19 = l19 + 1) {
			fRec19[l19] = 0.0;
		}
		for (int l20 = 0; l20 < 3; l20 = l20 + 1) {
			fRec18[l20] = 0.0;
		}
		for (int l21 = 0; l21 < 3; l21 = l21 + 1) {
			fRec17[l21] = 0.0;
		}
		for (int l22 = 0; l22 < 3; l22 = l22 + 1) {
			fRec16[l22] = 0.0;
		}
		for (int l23 = 0; l23 < 3; l23 = l23 + 1) {
			fRec15[l23] = 0.0;
		}
		for (int l24 = 0; l24 < 3; l24 = l24 + 1) {
			fRec14[l24] = 0.0;
		}
		for (int l25 = 0; l25 < 3; l25 = l25 + 1) {
			fRec13[l25] = 0.0;
		}
		for (int l26 = 0; l26 < 3; l26 = l26 + 1) {
			fRec12[l26] = 0.0;
		}
		for (int l27 = 0; l27 < 2; l27 = l27 + 1) {
			fRec25[l27] = 0.0;
		}
		for (int l28 = 0; l28 < 2; l28 = l28 + 1) {
			fRec37[l28] = 0.0;
		}
		for (int l29 = 0; l29 < 3; l29 = l29 + 1) {
			fRec36[l29] = 0.0;
		}
		for (int l30 = 0; l30 < 3; l30 = l30 + 1) {
			fRec35[l30] = 0.0;
		}
		for (int l31 = 0; l31 < 2; l31 = l31 + 1) {
			fVec2[l31] = 0.0;
		}
		for (int l32 = 0; l32 < 2; l32 = l32 + 1) {
			fRec34[l32] = 0.0;
		}
		for (int l33 = 0; l33 < 3; l33 = l33 + 1) {
			fRec33[l33] = 0.0;
		}
		for (int l34 = 0; l34 < 3; l34 = l34 + 1) {
			fRec32[l34] = 0.0;
		}
		for (int l35 = 0; l35 < 3; l35 = l35 + 1) {
			fRec31[l35] = 0.0;
		}
		for (int l36 = 0; l36 < 3; l36 = l36 + 1) {
			fRec30[l36] = 0.0;
		}
		for (int l37 = 0; l37 < 3; l37 = l37 + 1) {
			fRec29[l37] = 0.0;
		}
		for (int l38 = 0; l38 < 3; l38 = l38 + 1) {
			fRec28[l38] = 0.0;
		}
		for (int l39 = 0; l39 < 3; l39 = l39 + 1) {
			fRec27[l39] = 0.0;
		}
		for (int l40 = 0; l40 < 3; l40 = l40 + 1) {
			fRec26[l40] = 0.0;
		}
		for (int l41 = 0; l41 < 2; l41 = l41 + 1) {
			fRec38[l41] = 0.0;
		}
		for (int l42 = 0; l42 < 2; l42 = l42 + 1) {
			fRec49[l42] = 0.0;
		}
		for (int l43 = 0; l43 < 3; l43 = l43 + 1) {
			fRec48[l43] = 0.0;
		}
		for (int l44 = 0; l44 < 3; l44 = l44 + 1) {
			fRec47[l44] = 0.0;
		}
		for (int l45 = 0; l45 < 2; l45 = l45 + 1) {
			fVec3[l45] = 0.0;
		}
		for (int l46 = 0; l46 < 2; l46 = l46 + 1) {
			fRec46[l46] = 0.0;
		}
		for (int l47 = 0; l47 < 3; l47 = l47 + 1) {
			fRec45[l47] = 0.0;
		}
		for (int l48 = 0; l48 < 3; l48 = l48 + 1) {
			fRec44[l48] = 0.0;
		}
		for (int l49 = 0; l49 < 3; l49 = l49 + 1) {
			fRec43[l49] = 0.0;
		}
		for (int l50 = 0; l50 < 3; l50 = l50 + 1) {
			fRec42[l50] = 0.0;
		}
		for (int l51 = 0; l51 < 3; l51 = l51 + 1) {
			fRec41[l51] = 0.0;
		}
		for (int l52 = 0; l52 < 3; l52 = l52 + 1) {
			fRec40[l52] = 0.0;
		}
		for (int l53 = 0; l53 < 3; l53 = l53 + 1) {
			fRec39[l53] = 0.0;
		}
		for (int l54 = 0; l54 < 2; l54 = l54 + 1) {
			fRec50[l54] = 0.0;
		}
		for (int l55 = 0; l55 < 2; l55 = l55 + 1) {
			fRec60[l55] = 0.0;
		}
		for (int l56 = 0; l56 < 3; l56 = l56 + 1) {
			fRec59[l56] = 0.0;
		}
		for (int l57 = 0; l57 < 3; l57 = l57 + 1) {
			fRec58[l57] = 0.0;
		}
		for (int l58 = 0; l58 < 2; l58 = l58 + 1) {
			fVec4[l58] = 0.0;
		}
		for (int l59 = 0; l59 < 2; l59 = l59 + 1) {
			fRec57[l59] = 0.0;
		}
		for (int l60 = 0; l60 < 3; l60 = l60 + 1) {
			fRec56[l60] = 0.0;
		}
		for (int l61 = 0; l61 < 3; l61 = l61 + 1) {
			fRec55[l61] = 0.0;
		}
		for (int l62 = 0; l62 < 3; l62 = l62 + 1) {
			fRec54[l62] = 0.0;
		}
		for (int l63 = 0; l63 < 3; l63 = l63 + 1) {
			fRec53[l63] = 0.0;
		}
		for (int l64 = 0; l64 < 3; l64 = l64 + 1) {
			fRec52[l64] = 0.0;
		}
		for (int l65 = 0; l65 < 3; l65 = l65 + 1) {
			fRec51[l65] = 0.0;
		}
		for (int l66 = 0; l66 < 2; l66 = l66 + 1) {
			fRec61[l66] = 0.0;
		}
		for (int l67 = 0; l67 < 2; l67 = l67 + 1) {
			fRec70[l67] = 0.0;
		}
		for (int l68 = 0; l68 < 3; l68 = l68 + 1) {
			fRec69[l68] = 0.0;
		}
		for (int l69 = 0; l69 < 3; l69 = l69 + 1) {
			fRec68[l69] = 0.0;
		}
		for (int l70 = 0; l70 < 2; l70 = l70 + 1) {
			fVec5[l70] = 0.0;
		}
		for (int l71 = 0; l71 < 2; l71 = l71 + 1) {
			fRec67[l71] = 0.0;
		}
		for (int l72 = 0; l72 < 3; l72 = l72 + 1) {
			fRec66[l72] = 0.0;
		}
		for (int l73 = 0; l73 < 3; l73 = l73 + 1) {
			fRec65[l73] = 0.0;
		}
		for (int l74 = 0; l74 < 3; l74 = l74 + 1) {
			fRec64[l74] = 0.0;
		}
		for (int l75 = 0; l75 < 3; l75 = l75 + 1) {
			fRec63[l75] = 0.0;
		}
		for (int l76 = 0; l76 < 3; l76 = l76 + 1) {
			fRec62[l76] = 0.0;
		}
		for (int l77 = 0; l77 < 2; l77 = l77 + 1) {
			fRec71[l77] = 0.0;
		}
		for (int l78 = 0; l78 < 2; l78 = l78 + 1) {
			fRec79[l78] = 0.0;
		}
		for (int l79 = 0; l79 < 3; l79 = l79 + 1) {
			fRec78[l79] = 0.0;
		}
		for (int l80 = 0; l80 < 3; l80 = l80 + 1) {
			fRec77[l80] = 0.0;
		}
		for (int l81 = 0; l81 < 2; l81 = l81 + 1) {
			fVec6[l81] = 0.0;
		}
		for (int l82 = 0; l82 < 2; l82 = l82 + 1) {
			fRec76[l82] = 0.0;
		}
		for (int l83 = 0; l83 < 3; l83 = l83 + 1) {
			fRec75[l83] = 0.0;
		}
		for (int l84 = 0; l84 < 3; l84 = l84 + 1) {
			fRec74[l84] = 0.0;
		}
		for (int l85 = 0; l85 < 3; l85 = l85 + 1) {
			fRec73[l85] = 0.0;
		}
		for (int l86 = 0; l86 < 3; l86 = l86 + 1) {
			fRec72[l86] = 0.0;
		}
		for (int l87 = 0; l87 < 2; l87 = l87 + 1) {
			fRec80[l87] = 0.0;
		}
		for (int l88 = 0; l88 < 2; l88 = l88 + 1) {
			fRec87[l88] = 0.0;
		}
		for (int l89 = 0; l89 < 3; l89 = l89 + 1) {
			fRec86[l89] = 0.0;
		}
		for (int l90 = 0; l90 < 3; l90 = l90 + 1) {
			fRec85[l90] = 0.0;
		}
		for (int l91 = 0; l91 < 2; l91 = l91 + 1) {
			fVec7[l91] = 0.0;
		}
		for (int l92 = 0; l92 < 2; l92 = l92 + 1) {
			fRec84[l92] = 0.0;
		}
		for (int l93 = 0; l93 < 3; l93 = l93 + 1) {
			fRec83[l93] = 0.0;
		}
		for (int l94 = 0; l94 < 3; l94 = l94 + 1) {
			fRec82[l94] = 0.0;
		}
		for (int l95 = 0; l95 < 3; l95 = l95 + 1) {
			fRec81[l95] = 0.0;
		}
		for (int l96 = 0; l96 < 2; l96 = l96 + 1) {
			fRec88[l96] = 0.0;
		}
		for (int l97 = 0; l97 < 2; l97 = l97 + 1) {
			fRec94[l97] = 0.0;
		}
		for (int l98 = 0; l98 < 3; l98 = l98 + 1) {
			fRec93[l98] = 0.0;
		}
		for (int l99 = 0; l99 < 3; l99 = l99 + 1) {
			fRec92[l99] = 0.0;
		}
		for (int l100 = 0; l100 < 2; l100 = l100 + 1) {
			fVec8[l100] = 0.0;
		}
		for (int l101 = 0; l101 < 2; l101 = l101 + 1) {
			fRec91[l101] = 0.0;
		}
		for (int l102 = 0; l102 < 3; l102 = l102 + 1) {
			fRec90[l102] = 0.0;
		}
		for (int l103 = 0; l103 < 3; l103 = l103 + 1) {
			fRec89[l103] = 0.0;
		}
		for (int l104 = 0; l104 < 2; l104 = l104 + 1) {
			fRec95[l104] = 0.0;
		}
		for (int l105 = 0; l105 < 2; l105 = l105 + 1) {
			fRec98[l105] = 0.0;
		}
		for (int l106 = 0; l106 < 3; l106 = l106 + 1) {
			fRec97[l106] = 0.0;
		}
		for (int l107 = 0; l107 < 3; l107 = l107 + 1) {
			fRec96[l107] = 0.0;
		}
		for (int l108 = 0; l108 < 2; l108 = l108 + 1) {
			fRec99[l108] = 0.0;
		}
	}

	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	inline int getSampleRate() {
		return fSampleRate;
	}

	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = fConst64 * static_cast<double>(fVslider0);
		double fSlow1 = fConst64 * static_cast<double>(fVslider1);
		double fSlow2 = fConst64 * static_cast<double>(fVslider2);
		double fSlow3 = fConst64 * static_cast<double>(fVslider3);
		double fSlow4 = fConst64 * static_cast<double>(fVslider4);
		double fSlow5 = fConst64 * static_cast<double>(fVslider5);
		double fSlow6 = fConst64 * static_cast<double>(fVslider6);
		double fSlow7 = fConst64 * static_cast<double>(fVslider7);
		double fSlow8 = fConst64 * static_cast<double>(fVslider8);
		double fSlow9 = fConst64 * static_cast<double>(fVslider9);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			fVec0[0] = fTemp0;
			fRec10[0] = -(fConst8 * (fConst9 * fRec10[1] - fConst3 * (fTemp0 - fVec0[1])));
			fRec9[0] = fRec10[0] - fConst10 * (fConst11 * fRec9[2] + fConst12 * fRec9[1]);
			fRec8[0] = fConst7 * (fRec9[2] + (fRec9[0] - 2.0 * fRec9[1])) - fConst13 * (fConst14 * fRec8[2] + fConst12 * fRec8[1]);
			double fTemp1 = fConst21 * fRec7[1];
			fRec7[0] = fConst5 * (fRec8[2] + (fRec8[0] - 2.0 * fRec8[1])) - fConst17 * (fConst18 * fRec7[2] + fTemp1);
			double fTemp2 = fConst27 * fRec6[1];
			fRec6[0] = fRec7[2] + fConst17 * (fTemp1 + fConst18 * fRec7[0]) - fConst24 * (fConst25 * fRec6[2] + fTemp2);
			double fTemp3 = fConst33 * fRec5[1];
			fRec5[0] = fRec6[2] + fConst24 * (fTemp2 + fConst25 * fRec6[0]) - fConst30 * (fConst31 * fRec5[2] + fTemp3);
			double fTemp4 = fConst39 * fRec4[1];
			fRec4[0] = fRec5[2] + fConst30 * (fTemp3 + fConst31 * fRec5[0]) - fConst36 * (fConst37 * fRec4[2] + fTemp4);
			double fTemp5 = fConst45 * fRec3[1];
			fRec3[0] = fRec4[2] + fConst36 * (fTemp4 + fConst37 * fRec4[0]) - fConst42 * (fConst43 * fRec3[2] + fTemp5);
			double fTemp6 = fConst51 * fRec2[1];
			fRec2[0] = fRec3[2] + fConst42 * (fTemp5 + fConst43 * fRec3[0]) - fConst48 * (fConst49 * fRec2[2] + fTemp6);
			double fTemp7 = fConst57 * fRec1[1];
			fRec1[0] = fRec2[2] + fConst48 * (fTemp6 + fConst49 * fRec2[0]) - fConst54 * (fConst55 * fRec1[2] + fTemp7);
			double fTemp8 = fConst63 * fRec0[1];
			fRec0[0] = fRec1[2] + fConst54 * (fTemp7 + fConst55 * fRec1[0]) - fConst60 * (fConst61 * fRec0[2] + fTemp8);
			fRec11[0] = fSlow0 + fConst65 * fRec11[1];
			fRec24[0] = -(fConst8 * (fConst9 * fRec24[1] - (fTemp0 + fVec0[1])));
			fRec23[0] = fRec24[0] - fConst10 * (fConst11 * fRec23[2] + fConst12 * fRec23[1]);
			fRec22[0] = fConst10 * (fRec23[2] + fRec23[0] + 2.0 * fRec23[1]) - fConst13 * (fConst14 * fRec22[2] + fConst12 * fRec22[1]);
			double fTemp9 = fRec22[2] + fRec22[0] + 2.0 * fRec22[1];
			fVec1[0] = fTemp9;
			fRec21[0] = -(fConst70 * (fConst71 * fRec21[1] - fConst72 * (fTemp9 - fVec1[1])));
			fRec20[0] = fRec21[0] - fConst73 * (fConst74 * fRec20[2] + fConst63 * fRec20[1]);
			fRec19[0] = fConst69 * (fRec20[2] + (fRec20[0] - 2.0 * fRec20[1])) - fConst75 * (fConst76 * fRec19[2] + fConst63 * fRec19[1]);
			double fTemp10 = fConst21 * fRec18[1];
			fRec18[0] = fConst67 * (fRec19[2] + (fRec19[0] - 2.0 * fRec19[1])) - fConst17 * (fConst18 * fRec18[2] + fTemp10);
			double fTemp11 = fConst27 * fRec17[1];
			fRec17[0] = fRec18[2] + fConst17 * (fTemp10 + fConst18 * fRec18[0]) - fConst24 * (fConst25 * fRec17[2] + fTemp11);
			double fTemp12 = fConst33 * fRec16[1];
			fRec16[0] = fRec17[2] + fConst24 * (fTemp11 + fConst25 * fRec17[0]) - fConst30 * (fConst31 * fRec16[2] + fTemp12);
			double fTemp13 = fConst39 * fRec15[1];
			fRec15[0] = fRec16[2] + fConst30 * (fTemp12 + fConst31 * fRec16[0]) - fConst36 * (fConst37 * fRec15[2] + fTemp13);
			double fTemp14 = fConst45 * fRec14[1];
			fRec14[0] = fRec15[2] + fConst36 * (fTemp13 + fConst37 * fRec15[0]) - fConst42 * (fConst43 * fRec14[2] + fTemp14);
			double fTemp15 = fConst51 * fRec13[1];
			fRec13[0] = fRec14[2] + fConst42 * (fTemp14 + fConst43 * fRec14[0]) - fConst48 * (fConst49 * fRec13[2] + fTemp15);
			double fTemp16 = fConst57 * fRec12[1];
			fRec12[0] = fRec13[2] + fConst48 * (fTemp15 + fConst49 * fRec13[0]) - fConst54 * (fConst55 * fRec12[2] + fTemp16);
			fRec25[0] = fSlow1 + fConst65 * fRec25[1];
			fRec37[0] = -(fConst70 * (fConst71 * fRec37[1] - fConst13 * (fTemp9 + fVec1[1])));
			fRec36[0] = fRec37[0] - fConst73 * (fConst74 * fRec36[2] + fConst63 * fRec36[1]);
			fRec35[0] = fConst73 * (fRec36[2] + fRec36[0] + 2.0 * fRec36[1]) - fConst75 * (fConst76 * fRec35[2] + fConst63 * fRec35[1]);
			double fTemp17 = fRec35[2] + fRec35[0] + 2.0 * fRec35[1];
			fVec2[0] = fTemp17;
			fRec34[0] = -(fConst81 * (fConst82 * fRec34[1] - fConst83 * (fTemp17 - fVec2[1])));
			fRec33[0] = fRec34[0] - fConst84 * (fConst85 * fRec33[2] + fConst57 * fRec33[1]);
			fRec32[0] = fConst80 * (fRec33[2] + (fRec33[0] - 2.0 * fRec33[1])) - fConst86 * (fConst87 * fRec32[2] + fConst57 * fRec32[1]);
			double fTemp18 = fConst21 * fRec31[1];
			fRec31[0] = fConst78 * (fRec32[2] + (fRec32[0] - 2.0 * fRec32[1])) - fConst17 * (fConst18 * fRec31[2] + fTemp18);
			double fTemp19 = fConst27 * fRec30[1];
			fRec30[0] = fRec31[2] + fConst17 * (fTemp18 + fConst18 * fRec31[0]) - fConst24 * (fConst25 * fRec30[2] + fTemp19);
			double fTemp20 = fConst33 * fRec29[1];
			fRec29[0] = fRec30[2] + fConst24 * (fTemp19 + fConst25 * fRec30[0]) - fConst30 * (fConst31 * fRec29[2] + fTemp20);
			double fTemp21 = fConst39 * fRec28[1];
			fRec28[0] = fRec29[2] + fConst30 * (fTemp20 + fConst31 * fRec29[0]) - fConst36 * (fConst37 * fRec28[2] + fTemp21);
			double fTemp22 = fConst45 * fRec27[1];
			fRec27[0] = fRec28[2] + fConst36 * (fTemp21 + fConst37 * fRec28[0]) - fConst42 * (fConst43 * fRec27[2] + fTemp22);
			double fTemp23 = fConst51 * fRec26[1];
			fRec26[0] = fRec27[2] + fConst42 * (fTemp22 + fConst43 * fRec27[0]) - fConst48 * (fConst49 * fRec26[2] + fTemp23);
			fRec38[0] = fSlow2 + fConst65 * fRec38[1];
			fRec49[0] = -(fConst81 * (fConst82 * fRec49[1] - fConst75 * (fTemp17 + fVec2[1])));
			fRec48[0] = fRec49[0] - fConst84 * (fConst85 * fRec48[2] + fConst57 * fRec48[1]);
			fRec47[0] = fConst84 * (fRec48[2] + fRec48[0] + 2.0 * fRec48[1]) - fConst86 * (fConst87 * fRec47[2] + fConst57 * fRec47[1]);
			double fTemp24 = fRec47[2] + fRec47[0] + 2.0 * fRec47[1];
			fVec3[0] = fTemp24;
			fRec46[0] = -(fConst92 * (fConst93 * fRec46[1] - fConst94 * (fTemp24 - fVec3[1])));
			fRec45[0] = fRec46[0] - fConst95 * (fConst96 * fRec45[2] + fConst51 * fRec45[1]);
			fRec44[0] = fConst91 * (fRec45[2] + (fRec45[0] - 2.0 * fRec45[1])) - fConst97 * (fConst98 * fRec44[2] + fConst51 * fRec44[1]);
			double fTemp25 = fConst21 * fRec43[1];
			fRec43[0] = fConst89 * (fRec44[2] + (fRec44[0] - 2.0 * fRec44[1])) - fConst17 * (fConst18 * fRec43[2] + fTemp25);
			double fTemp26 = fConst27 * fRec42[1];
			fRec42[0] = fRec43[2] + fConst17 * (fTemp25 + fConst18 * fRec43[0]) - fConst24 * (fConst25 * fRec42[2] + fTemp26);
			double fTemp27 = fConst33 * fRec41[1];
			fRec41[0] = fRec42[2] + fConst24 * (fTemp26 + fConst25 * fRec42[0]) - fConst30 * (fConst31 * fRec41[2] + fTemp27);
			double fTemp28 = fConst39 * fRec40[1];
			fRec40[0] = fRec41[2] + fConst30 * (fTemp27 + fConst31 * fRec41[0]) - fConst36 * (fConst37 * fRec40[2] + fTemp28);
			double fTemp29 = fConst45 * fRec39[1];
			fRec39[0] = fRec40[2] + fConst36 * (fTemp28 + fConst37 * fRec40[0]) - fConst42 * (fConst43 * fRec39[2] + fTemp29);
			fRec50[0] = fSlow3 + fConst65 * fRec50[1];
			fRec60[0] = -(fConst92 * (fConst93 * fRec60[1] - fConst86 * (fTemp24 + fVec3[1])));
			fRec59[0] = fRec60[0] - fConst95 * (fConst96 * fRec59[2] + fConst51 * fRec59[1]);
			fRec58[0] = fConst95 * (fRec59[2] + fRec59[0] + 2.0 * fRec59[1]) - fConst97 * (fConst98 * fRec58[2] + fConst51 * fRec58[1]);
			double fTemp30 = fRec58[2] + fRec58[0] + 2.0 * fRec58[1];
			fVec4[0] = fTemp30;
			fRec57[0] = -(fConst103 * (fConst104 * fRec57[1] - fConst105 * (fTemp30 - fVec4[1])));
			fRec56[0] = fRec57[0] - fConst106 * (fConst107 * fRec56[2] + fConst45 * fRec56[1]);
			fRec55[0] = fConst102 * (fRec56[2] + (fRec56[0] - 2.0 * fRec56[1])) - fConst108 * (fConst109 * fRec55[2] + fConst45 * fRec55[1]);
			double fTemp31 = fConst21 * fRec54[1];
			fRec54[0] = fConst100 * (fRec55[2] + (fRec55[0] - 2.0 * fRec55[1])) - fConst17 * (fConst18 * fRec54[2] + fTemp31);
			double fTemp32 = fConst27 * fRec53[1];
			fRec53[0] = fRec54[2] + fConst17 * (fTemp31 + fConst18 * fRec54[0]) - fConst24 * (fConst25 * fRec53[2] + fTemp32);
			double fTemp33 = fConst33 * fRec52[1];
			fRec52[0] = fRec53[2] + fConst24 * (fTemp32 + fConst25 * fRec53[0]) - fConst30 * (fConst31 * fRec52[2] + fTemp33);
			double fTemp34 = fConst39 * fRec51[1];
			fRec51[0] = fRec52[2] + fConst30 * (fTemp33 + fConst31 * fRec52[0]) - fConst36 * (fConst37 * fRec51[2] + fTemp34);
			fRec61[0] = fSlow4 + fConst65 * fRec61[1];
			fRec70[0] = -(fConst103 * (fConst104 * fRec70[1] - fConst97 * (fTemp30 + fVec4[1])));
			fRec69[0] = fRec70[0] - fConst106 * (fConst107 * fRec69[2] + fConst45 * fRec69[1]);
			fRec68[0] = fConst106 * (fRec69[2] + fRec69[0] + 2.0 * fRec69[1]) - fConst108 * (fConst109 * fRec68[2] + fConst45 * fRec68[1]);
			double fTemp35 = fRec68[2] + fRec68[0] + 2.0 * fRec68[1];
			fVec5[0] = fTemp35;
			fRec67[0] = -(fConst114 * (fConst115 * fRec67[1] - fConst116 * (fTemp35 - fVec5[1])));
			fRec66[0] = fRec67[0] - fConst117 * (fConst118 * fRec66[2] + fConst39 * fRec66[1]);
			fRec65[0] = fConst113 * (fRec66[2] + (fRec66[0] - 2.0 * fRec66[1])) - fConst119 * (fConst120 * fRec65[2] + fConst39 * fRec65[1]);
			double fTemp36 = fConst21 * fRec64[1];
			fRec64[0] = fConst111 * (fRec65[2] + (fRec65[0] - 2.0 * fRec65[1])) - fConst17 * (fConst18 * fRec64[2] + fTemp36);
			double fTemp37 = fConst27 * fRec63[1];
			fRec63[0] = fRec64[2] + fConst17 * (fTemp36 + fConst18 * fRec64[0]) - fConst24 * (fConst25 * fRec63[2] + fTemp37);
			double fTemp38 = fConst33 * fRec62[1];
			fRec62[0] = fRec63[2] + fConst24 * (fTemp37 + fConst25 * fRec63[0]) - fConst30 * (fConst31 * fRec62[2] + fTemp38);
			fRec71[0] = fSlow5 + fConst65 * fRec71[1];
			fRec79[0] = -(fConst114 * (fConst115 * fRec79[1] - fConst108 * (fTemp35 + fVec5[1])));
			fRec78[0] = fRec79[0] - fConst117 * (fConst118 * fRec78[2] + fConst39 * fRec78[1]);
			fRec77[0] = fConst117 * (fRec78[2] + fRec78[0] + 2.0 * fRec78[1]) - fConst119 * (fConst120 * fRec77[2] + fConst39 * fRec77[1]);
			double fTemp39 = fRec77[2] + fRec77[0] + 2.0 * fRec77[1];
			fVec6[0] = fTemp39;
			fRec76[0] = -(fConst125 * (fConst126 * fRec76[1] - fConst127 * (fTemp39 - fVec6[1])));
			fRec75[0] = fRec76[0] - fConst128 * (fConst129 * fRec75[2] + fConst33 * fRec75[1]);
			fRec74[0] = fConst124 * (fRec75[2] + (fRec75[0] - 2.0 * fRec75[1])) - fConst130 * (fConst131 * fRec74[2] + fConst33 * fRec74[1]);
			double fTemp40 = fConst21 * fRec73[1];
			fRec73[0] = fConst122 * (fRec74[2] + (fRec74[0] - 2.0 * fRec74[1])) - fConst17 * (fConst18 * fRec73[2] + fTemp40);
			double fTemp41 = fConst27 * fRec72[1];
			fRec72[0] = fRec73[2] + fConst17 * (fTemp40 + fConst18 * fRec73[0]) - fConst24 * (fConst25 * fRec72[2] + fTemp41);
			fRec80[0] = fSlow6 + fConst65 * fRec80[1];
			fRec87[0] = -(fConst125 * (fConst126 * fRec87[1] - fConst119 * (fTemp39 + fVec6[1])));
			fRec86[0] = fRec87[0] - fConst128 * (fConst129 * fRec86[2] + fConst33 * fRec86[1]);
			fRec85[0] = fConst128 * (fRec86[2] + fRec86[0] + 2.0 * fRec86[1]) - fConst130 * (fConst131 * fRec85[2] + fConst33 * fRec85[1]);
			double fTemp42 = fRec85[2] + fRec85[0] + 2.0 * fRec85[1];
			fVec7[0] = fTemp42;
			fRec84[0] = -(fConst136 * (fConst137 * fRec84[1] - fConst138 * (fTemp42 - fVec7[1])));
			fRec83[0] = fRec84[0] - fConst139 * (fConst140 * fRec83[2] + fConst27 * fRec83[1]);
			fRec82[0] = fConst135 * (fRec83[2] + (fRec83[0] - 2.0 * fRec83[1])) - fConst141 * (fConst142 * fRec82[2] + fConst27 * fRec82[1]);
			double fTemp43 = fConst21 * fRec81[1];
			fRec81[0] = fConst133 * (fRec82[2] + (fRec82[0] - 2.0 * fRec82[1])) - fConst17 * (fConst18 * fRec81[2] + fTemp43);
			fRec88[0] = fSlow7 + fConst65 * fRec88[1];
			fRec94[0] = -(fConst136 * (fConst137 * fRec94[1] - fConst130 * (fTemp42 + fVec7[1])));
			fRec93[0] = fRec94[0] - fConst139 * (fConst140 * fRec93[2] + fConst27 * fRec93[1]);
			fRec92[0] = fConst139 * (fRec93[2] + fRec93[0] + 2.0 * fRec93[1]) - fConst141 * (fConst142 * fRec92[2] + fConst27 * fRec92[1]);
			double fTemp44 = fRec92[2] + fRec92[0] + 2.0 * fRec92[1];
			fVec8[0] = fTemp44;
			fRec91[0] = -(fConst146 * (fConst147 * fRec91[1] - fConst141 * (fTemp44 + fVec8[1])));
			fRec90[0] = fRec91[0] - fConst145 * (fConst148 * fRec90[2] + fConst21 * fRec90[1]);
			fRec89[0] = fConst145 * (fRec90[2] + fRec90[0] + 2.0 * fRec90[1]) - fConst143 * (fConst149 * fRec89[2] + fConst21 * fRec89[1]);
			fRec95[0] = fSlow8 + fConst65 * fRec95[1];
			fRec98[0] = -(fConst146 * (fConst147 * fRec98[1] - fConst151 * (fTemp44 - fVec8[1])));
			fRec97[0] = fRec98[0] - fConst145 * (fConst148 * fRec97[2] + fConst21 * fRec97[1]);
			fRec96[0] = fConst150 * (fRec97[2] + (fRec97[0] - 2.0 * fRec97[1])) - fConst143 * (fConst149 * fRec96[2] + fConst21 * fRec96[1]);
			fRec99[0] = fSlow9 + fConst65 * fRec99[1];
			output0[i0] = static_cast<float>((fRec0[2] + fConst60 * (fTemp8 + fConst61 * fRec0[0])) * std::pow(1e+01, 0.05 * fRec11[0]) + (fRec12[2] + fConst54 * (fTemp16 + fConst55 * fRec12[0])) * std::pow(1e+01, 0.05 * fRec25[0]) + (fRec26[2] + fConst48 * (fTemp23 + fConst49 * fRec26[0])) * std::pow(1e+01, 0.05 * fRec38[0]) + (fRec39[2] + fConst42 * (fTemp29 + fConst43 * fRec39[0])) * std::pow(1e+01, 0.05 * fRec50[0]) + (fRec51[2] + fConst36 * (fTemp34 + fConst37 * fRec51[0])) * std::pow(1e+01, 0.05 * fRec61[0]) + (fRec62[2] + fConst30 * (fTemp38 + fConst31 * fRec62[0])) * std::pow(1e+01, 0.05 * fRec71[0]) + (fRec72[2] + fConst24 * (fTemp41 + fConst25 * fRec72[0])) * std::pow(1e+01, 0.05 * fRec80[0]) + (fRec81[2] + fConst17 * (fTemp43 + fConst18 * fRec81[0])) * std::pow(1e+01, 0.05 * fRec88[0]) + fConst143 * ((fRec89[2] + fRec89[0] + 2.0 * fRec89[1]) * std::pow(1e+01, 0.05 * fRec95[0]) + fConst20 * (fRec96[2] + (fRec96[0] - 2.0 * fRec96[1])) * std::pow(1e+01, 0.05 * fRec99[0])));
			fVec0[1] = fVec0[0];
			fRec10[1] = fRec10[0];
			fRec9[2] = fRec9[1];
			fRec9[1] = fRec9[0];
			fRec8[2] = fRec8[1];
			fRec8[1] = fRec8[0];
			fRec7[2] = fRec7[1];
			fRec7[1] = fRec7[0];
			fRec6[2] = fRec6[1];
			fRec6[1] = fRec6[0];
			fRec5[2] = fRec5[1];
			fRec5[1] = fRec5[0];
			fRec4[2] = fRec4[1];
			fRec4[1] = fRec4[0];
			fRec3[2] = fRec3[1];
			fRec3[1] = fRec3[0];
			fRec2[2] = fRec2[1];
			fRec2[1] = fRec2[0];
			fRec1[2] = fRec1[1];
			fRec1[1] = fRec1[0];
			fRec0[2] = fRec0[1];
			fRec0[1] = fRec0[0];
			fRec11[1] = fRec11[0];
			fRec24[1] = fRec24[0];
			fRec23[2] = fRec23[1];
			fRec23[1] = fRec23[0];
			fRec22[2] = fRec22[1];
			fRec22[1] = fRec22[0];
			fVec1[1] = fVec1[0];
			fRec21[1] = fRec21[0];
			fRec20[2] = fRec20[1];
			fRec20[1] = fRec20[0];
			fRec19[2] = fRec19[1];
			fRec19[1] = fRec19[0];
			fRec18[2] = fRec18[1];
			fRec18[1] = fRec18[0];
			fRec17[2] = fRec17[1];
			fRec17[1] = fRec17[0];
			fRec16[2] = fRec16[1];
			fRec16[1] = fRec16[0];
			fRec15[2] = fRec15[1];
			fRec15[1] = fRec15[0];
			fRec14[2] = fRec14[1];
			fRec14[1] = fRec14[0];
			fRec13[2] = fRec13[1];
			fRec13[1] = fRec13[0];
			fRec12[2] = fRec12[1];
			fRec12[1] = fRec12[0];
			fRec25[1] = fRec25[0];
			fRec37[1] = fRec37[0];
			fRec36[2] = fRec36[1];
			fRec36[1] = fRec36[0];
			fRec35[2] = fRec35[1];
			fRec35[1] = fRec35[0];
			fVec2[1] = fVec2[0];
			fRec34[1] = fRec34[0];
			fRec33[2] = fRec33[1];
			fRec33[1] = fRec33[0];
			fRec32[2] = fRec32[1];
			fRec32[1] = fRec32[0];
			fRec31[2] = fRec31[1];
			fRec31[1] = fRec31[0];
			fRec30[2] = fRec30[1];
			fRec30[1] = fRec30[0];
			fRec29[2] = fRec29[1];
			fRec29[1] = fRec29[0];
			fRec28[2] = fRec28[1];
			fRec28[1] = fRec28[0];
			fRec27[2] = fRec27[1];
			fRec27[1] = fRec27[0];
			fRec26[2] = fRec26[1];
			fRec26[1] = fRec26[0];
			fRec38[1] = fRec38[0];
			fRec49[1] = fRec49[0];
			fRec48[2] = fRec48[1];
			fRec48[1] = fRec48[0];
			fRec47[2] = fRec47[1];
			fRec47[1] = fRec47[0];
			fVec3[1] = fVec3[0];
			fRec46[1] = fRec46[0];
			fRec45[2] = fRec45[1];
			fRec45[1] = fRec45[0];
			fRec44[2] = fRec44[1];
			fRec44[1] = fRec44[0];
			fRec43[2] = fRec43[1];
			fRec43[1] = fRec43[0];
			fRec42[2] = fRec42[1];
			fRec42[1] = fRec42[0];
			fRec41[2] = fRec41[1];
			fRec41[1] = fRec41[0];
			fRec40[2] = fRec40[1];
			fRec40[1] = fRec40[0];
			fRec39[2] = fRec39[1];
			fRec39[1] = fRec39[0];
			fRec50[1] = fRec50[0];
			fRec60[1] = fRec60[0];
			fRec59[2] = fRec59[1];
			fRec59[1] = fRec59[0];
			fRec58[2] = fRec58[1];
			fRec58[1] = fRec58[0];
			fVec4[1] = fVec4[0];
			fRec57[1] = fRec57[0];
			fRec56[2] = fRec56[1];
			fRec56[1] = fRec56[0];
			fRec55[2] = fRec55[1];
			fRec55[1] = fRec55[0];
			fRec54[2] = fRec54[1];
			fRec54[1] = fRec54[0];
			fRec53[2] = fRec53[1];
			fRec53[1] = fRec53[0];
			fRec52[2] = fRec52[1];
			fRec52[1] = fRec52[0];
			fRec51[2] = fRec51[1];
			fRec51[1] = fRec51[0];
			fRec61[1] = fRec61[0];
			fRec70[1] = fRec70[0];
			fRec69[2] = fRec69[1];
			fRec69[1] = fRec69[0];
			fRec68[2] = fRec68[1];
			fRec68[1] = fRec68[0];
			fVec5[1] = fVec5[0];
			fRec67[1] = fRec67[0];
			fRec66[2] = fRec66[1];
			fRec66[1] = fRec66[0];
			fRec65[2] = fRec65[1];
			fRec65[1] = fRec65[0];
			fRec64[2] = fRec64[1];
			fRec64[1] = fRec64[0];
			fRec63[2] = fRec63[1];
			fRec63[1] = fRec63[0];
			fRec62[2] = fRec62[1];
			fRec62[1] = fRec62[0];
			fRec71[1] = fRec71[0];
			fRec79[1] = fRec79[0];
			fRec78[2] = fRec78[1];
			fRec78[1] = fRec78[0];
			fRec77[2] = fRec77[1];
			fRec77[1] = fRec77[0];
			fVec6[1] = fVec6[0];
			fRec76[1] = fRec76[0];
			fRec75[2] = fRec75[1];
			fRec75[1] = fRec75[0];
			fRec74[2] = fRec74[1];
			fRec74[1] = fRec74[0];
			fRec73[2] = fRec73[1];
			fRec73[1] = fRec73[0];
			fRec72[2] = fRec72[1];
			fRec72[1] = fRec72[0];
			fRec80[1] = fRec80[0];
			fRec87[1] = fRec87[0];
			fRec86[2] = fRec86[1];
			fRec86[1] = fRec86[0];
			fRec85[2] = fRec85[1];
			fRec85[1] = fRec85[0];
			fVec7[1] = fVec7[0];
			fRec84[1] = fRec84[0];
			fRec83[2] = fRec83[1];
			fRec83[1] = fRec83[0];
			fRec82[2] = fRec82[1];
			fRec82[1] = fRec82[0];
			fRec81[2] = fRec81[1];
			fRec81[1] = fRec81[0];
			fRec88[1] = fRec88[0];
			fRec94[1] = fRec94[0];
			fRec93[2] = fRec93[1];
			fRec93[1] = fRec93[0];
			fRec92[2] = fRec92[1];
			fRec92[1] = fRec92[0];
			fVec8[1] = fVec8[0];
			fRec91[1] = fRec91[0];
			fRec90[2] = fRec90[1];
			fRec90[1] = fRec90[0];
			fRec89[2] = fRec89[1];
			fRec89[1] = fRec89[0];
			fRec95[1] = fRec95[0];
			fRec98[1] = fRec98[0];
			fRec97[2] = fRec97[1];
			fRec97[1] = fRec97[0];
			fRec96[2] = fRec96[1];
			fRec96[1] = fRec96[0];
			fRec99[1] = fRec99[0];
		}
	}

	inline void calculateSizes() {
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width1 += spacing.x;
		width1 += 20.0f;
		height1 = std::max(height1, 100.0f);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Graphic EQ");
		changed |= editBand10();
		ImGui::SameLine();
		changed |= editBand1();
		ImGui::SameLine();
		changed |= editBand2();
		ImGui::SameLine();
		changed |= editBand3();
		ImGui::SameLine();
		changed |= editBand4();
		ImGui::SameLine();
		changed |= editBand5();
		ImGui::SameLine();
		changed |= editBand6();
		ImGui::SameLine();
		changed |= editBand7();
		ImGui::SameLine();
		changed |= editBand8();
		ImGui::SameLine();
		changed |= editBand9();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float band10 = -10.0f;
		float band1 = -10.0f;
		float band2 = -10.0f;
		float band3 = -10.0f;
		float band4 = -10.0f;
		float band5 = -10.0f;
		float band6 = -10.0f;
		float band7 = -10.0f;
		float band8 = -10.0f;
		float band9 = -10.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider0 = parameters.band10;
		fVslider8 = parameters.band1;
		fVslider9 = parameters.band2;
		fVslider7 = parameters.band3;
		fVslider6 = parameters.band4;
		fVslider5 = parameters.band5;
		fVslider4 = parameters.band6;
		fVslider3 = parameters.band7;
		fVslider2 = parameters.band8;
		fVslider1 = parameters.band9;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.band10 = fVslider0;
		parameters.band1 = fVslider8;
		parameters.band2 = fVslider9;
		parameters.band3 = fVslider7;
		parameters.band4 = fVslider6;
		parameters.band5 = fVslider5;
		parameters.band6 = fVslider4;
		parameters.band7 = fVslider3;
		parameters.band8 = fVslider2;
		parameters.band9 = fVslider1;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("band10", &fVslider0, -10.0f);
		callback("band1", &fVslider8, -10.0f);
		callback("band2", &fVslider9, -10.0f);
		callback("band3", &fVslider7, -10.0f);
		callback("band4", &fVslider6, -10.0f);
		callback("band5", &fVslider5, -10.0f);
		callback("band6", &fVslider4, -10.0f);
		callback("band7", &fVslider3, -10.0f);
		callback("band8", &fVslider2, -10.0f);
		callback("band9", &fVslider1, -10.0f);
	}

	inline bool editBand10() { auto changed = ImGui::VSliderFloat("##Band10", ImVec2(20.0f, 100.0f), &fVslider0, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider0); return changed; }
	inline bool editBand1() { auto changed = ImGui::VSliderFloat("##Band1", ImVec2(20.0f, 100.0f), &fVslider8, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider8); return changed; }
	inline bool editBand2() { auto changed = ImGui::VSliderFloat("##Band2", ImVec2(20.0f, 100.0f), &fVslider9, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider9); return changed; }
	inline bool editBand3() { auto changed = ImGui::VSliderFloat("##Band3", ImVec2(20.0f, 100.0f), &fVslider7, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider7); return changed; }
	inline bool editBand4() { auto changed = ImGui::VSliderFloat("##Band4", ImVec2(20.0f, 100.0f), &fVslider6, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider6); return changed; }
	inline bool editBand5() { auto changed = ImGui::VSliderFloat("##Band5", ImVec2(20.0f, 100.0f), &fVslider5, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider5); return changed; }
	inline bool editBand6() { auto changed = ImGui::VSliderFloat("##Band6", ImVec2(20.0f, 100.0f), &fVslider4, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider4); return changed; }
	inline bool editBand7() { auto changed = ImGui::VSliderFloat("##Band7", ImVec2(20.0f, 100.0f), &fVslider3, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider3); return changed; }
	inline bool editBand8() { auto changed = ImGui::VSliderFloat("##Band8", ImVec2(20.0f, 100.0f), &fVslider2, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider2); return changed; }
	inline bool editBand9() { auto changed = ImGui::VSliderFloat("##Band9", ImVec2(20.0f, 100.0f), &fVslider1, -70.0f, 10.0f, ""); if (ImGui::IsItemActive() || ImGui::IsItemHovered()) ImGui::SetTooltip("%.1fdB", fVslider1); return changed; }

	inline void setBand10(float value) { fVslider0 = value; }
	inline void setBand1(float value) { fVslider8 = value; }
	inline void setBand2(float value) { fVslider9 = value; }
	inline void setBand3(float value) { fVslider7 = value; }
	inline void setBand4(float value) { fVslider6 = value; }
	inline void setBand5(float value) { fVslider5 = value; }
	inline void setBand6(float value) { fVslider4 = value; }
	inline void setBand7(float value) { fVslider3 = value; }
	inline void setBand8(float value) { fVslider2 = value; }
	inline void setBand9(float value) { fVslider1 = value; }

	inline float getBand10() { return fVslider0; }
	inline float getBand1() { return fVslider8; }
	inline float getBand2() { return fVslider9; }
	inline float getBand3() { return fVslider7; }
	inline float getBand4() { return fVslider6; }
	inline float getBand5() { return fVslider5; }
	inline float getBand6() { return fVslider4; }
	inline float getBand7() { return fVslider3; }
	inline float getBand8() { return fVslider2; }
	inline float getBand9() { return fVslider1; }

private:
	bool initialized = false;
	float width;
	float height;
};
