//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtLfo
//

class OtLfoSIG0 {
protected:	
	int iVec0[2];
	int iRec0[2];

public:	
	int getNumInputsOtLfoSIG0() {
		return 0;
	}
	int getNumOutputsOtLfoSIG0() {
		return 1;
	}
	
	void instanceInitOtLfoSIG0([[maybe_unused]] int sample_rate) {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			iRec0[l1] = 0;
		}
	}
	
	void fillOtLfoSIG0(int count, double* table) {
		for (int i1 = 0; i1 < count; i1 = i1 + 1) {
			iVec0[0] = 1;
			iRec0[0] = (iVec0[1] + iRec0[1]) % 65536;
			table[i1] = std::sin(9.587379924285257e-05 * static_cast<double>(iRec0[0]));
			iVec0[1] = iVec0[0];
			iRec0[1] = iRec0[0];
		}
	}

};

static OtLfoSIG0* newOtLfoSIG0() { return (OtLfoSIG0*)new OtLfoSIG0(); }
static void deleteOtLfoSIG0(OtLfoSIG0* dsp) { delete dsp; }

static double ftbl0OtLfoSIG0[65536];

class OtLfo : public OtFaust {
protected:
	float fHslider0;
	int iVec1[2];
	int fSampleRate;
	double fConst0;
	double fRec1[2];
	
 public:
	OtLfo() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Generator");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtLfo -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtLfo.dsp");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "LFO");
		m->declare("oscillators.lib/lf_sawpos:author", "Bart Brouns, revised by Stéphane Letz");
		m->declare("oscillators.lib/lf_sawpos:licence", "STK-4.3");
		m->declare("oscillators.lib/lf_triangle:author", "Bart Brouns");
		m->declare("oscillators.lib/lf_triangle:licence", "STK-4.3");
		m->declare("oscillators.lib/name", "Faust Oscillator Library");
		m->declare("oscillators.lib/saw1:author", "Bart Brouns");
		m->declare("oscillators.lib/saw1:licence", "STK-4.3");
		m->declare("oscillators.lib/version", "1.6.0");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
		OtLfoSIG0* sig0 = newOtLfoSIG0();
		sig0->instanceInitOtLfoSIG0(sample_rate);
		sig0->fillOtLfoSIG0(65536, ftbl0OtLfoSIG0);
		deleteOtLfoSIG0(sig0);
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = 4.4e+02 / std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
	}
	
	inline void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(1.0);
	}
	
	inline void instanceClear() {
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			iVec1[l2] = 0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec1[l3] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
		
	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = static_cast<double>(fHslider0);
		int iSlow1 = fSlow0 >= 4.0;
		int iSlow2 = fSlow0 >= 2.0;
		int iSlow3 = fSlow0 >= 1.0;
		int iSlow4 = fSlow0 >= 3.0;
		int iSlow5 = fSlow0 >= 6.0;
		int iSlow6 = fSlow0 >= 5.0;
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iVec1[0] = 1;
			double fTemp0 = ((1 - iVec1[1]) ? 0.0 : fRec1[1] + fConst0 * std::pow(2.0, static_cast<double>(input0[i0])));
			fRec1[0] = fTemp0 - std::floor(fTemp0);
			double fTemp1 = 2.0 * fRec1[0] + -1.0;
			double fTemp2 = 2.0 * (1.0 - std::fabs(fTemp1)) + -1.0;
			output0[i0] = static_cast<float>(((iSlow1) ? ((iSlow5) ? 2.0 * static_cast<double>(fRec1[0] <= 0.7) + -1.0 : ((iSlow6) ? 2.0 * static_cast<double>(fRec1[0] <= 0.5) + -1.0 : fTemp1)) : ((iSlow2) ? ((iSlow4) ? 0.75 * fTemp2 + 0.25 * fTemp1 : fTemp2) : ((iSlow3) ? ftbl0OtLfoSIG0[std::max<int>(0, std::min<int>(static_cast<int>(65536.0 * fRec1[0]), 65535))] : 0.0))));
			iVec1[1] = iVec1[0];
			fRec1[1] = fRec1[0];
		}
	}

	inline void calculateSizes() {
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 = std::max(width1, 100.0f);
		height1 += 20.0f;
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("LFO");
		changed |= editWaveForm();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float waveForm = 1.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider0 = parameters.waveForm;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.waveForm = fHslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("waveForm", &fHslider0, 1.0f);
	}

	inline bool editWaveForm() { ImGui::SetNextItemWidth(100.0f); return ImGui::SliderFloat("WaveForm", &fHslider0, 0.0f, 7.0f, "%.0f"); }

	inline void setWaveForm(float value) { fHslider0 = value; }

	inline float getWaveForm() { return fHslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
