//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtNoise
//

class OtNoise : public OtFaust {
protected:
	float fHslider0;
	int iRec0[2];
	float fHslider1;
	double fRec1[4];
	int fSampleRate;
	
 public:
	OtNoise() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("category", "Noise");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtNoise -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtNoise.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Noise");
		m->declare("noises.lib/name", "Faust Noise Generator Library");
		m->declare("noises.lib/version", "1.5.0");
	}

	inline int getNumInputs() {
		return 0;
	}
	inline int getNumOutputs() {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
	}
	
	inline void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(0.0);
		fHslider1 = static_cast<float>(0.0);
	}
	
	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iRec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 4; l1 = l1 + 1) {
			fRec1[l1] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
	
	inline void buildUserInterface(UI* ui_interface) {
		ui_interface->openHorizontalBox("Noise");
		ui_interface->declare(&fHslider0, "0", "");
		ui_interface->declare(&fHslider0, "style", "knob");
		ui_interface->addHorizontalSlider("White", &fHslider0, float(0.0), float(0.0), float(1.0), float(0.01));
		ui_interface->declare(&fHslider1, "1", "");
		ui_interface->declare(&fHslider1, "style", "knob");
		ui_interface->addHorizontalSlider("Pink", &fHslider1, float(0.0), float(0.0), float(1.0), float(0.01));
		ui_interface->closeBox();
	}
	
	inline void compute(int count, float** inputs, float** outputs) {
		float* output0 = outputs[0];
		double fSlow0 = 4.656612875245797e-10 * static_cast<double>(fHslider0);
		double fSlow1 = 4.0 * static_cast<double>(fHslider1);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iRec0[0] = 1103515245 * iRec0[1] + 12345;
			double fTemp0 = static_cast<double>(iRec0[0]);
			fRec1[0] = 0.5221894 * fRec1[3] + 4.656612875245797e-10 * fTemp0 + 2.494956002 * fRec1[1] - 2.017265875 * fRec1[2];
			output0[i0] = static_cast<float>(fSlow0 * fTemp0 + fSlow1 * (0.049922035 * fRec1[0] + 0.050612699 * fRec1[2] - (0.095993537 * fRec1[1] + 0.004408786 * fRec1[3])));
			iRec0[1] = iRec0[0];
			for (int j0 = 3; j0 > 0; j0 = j0 - 1) {
				fRec1[j0] = fRec1[j0 - 1];
			}
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Noise");
		changed |= editWhite();
		ImGui::SameLine();
		changed |= editPink();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float white = 0.0f;
		float pink = 0.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider0 = parameters.white;
		fHslider1 = parameters.pink;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.white = fHslider0;
		parameters.pink = fHslider1;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("white", &fHslider0, 0.0f);
		callback("pink", &fHslider1, 0.0f);
	}

	inline bool editWhite() { return OtUi::knob("White", &fHslider0, 0.0f, 1.0f, "%.2f"); }
	inline bool editPink() { return OtUi::knob("Pink", &fHslider1, 0.0f, 1.0f, "%.2f"); }

	inline void setWhite(float value) { fHslider0 = value; }
	inline void setPink(float value) { fHslider1 = value; }

	inline float getWhite() { return fHslider0; }
	inline float getPink() { return fHslider1; }

private:
	bool initialized = false;
	float width;
	float height;
};
