//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtNoise
//

class OtNoise : public OtFaust {
protected:
	float fHslider0;
	float fCheckbox0;
	int iRec0[2];
	double fRec1[4];
	int fSampleRate;
	
 public:
	OtNoise() {
	}
	
	OtNoise(const OtNoise&) = default;
	
	virtual ~OtNoise() = default;
	
	OtNoise& operator=(const OtNoise&) = default;
	
	void metadata(Meta* m) override { 
		m->declare("category", "Noise");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtNoise -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtNoise.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("id", "Noise");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Noise");
		m->declare("noises.lib/name", "Faust Noise Generator Library");
		m->declare("noises.lib/version", "1.5.0");
	}

	int getNumInputs() override {
		return 0;
	}
	int getNumOutputs() override {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
	}
	
	virtual void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(0.0);
		fCheckbox0 = static_cast<float>(0.0);
	}
	
	virtual void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iRec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 4; l1 = l1 + 1) {
			fRec1[l1] = 0.0;
		}
	}
	
	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
	
	virtual OtNoise* clone() {
		return new OtNoise(*this);
	}
	
	int getSampleRate() override {
		return fSampleRate;
	}
	
	void buildUserInterface(UI* ui_interface) override {
		ui_interface->openVerticalBox("Noise");
		ui_interface->declare(&fCheckbox0, "0", "");
		ui_interface->declare(&fCheckbox0, "off", "White");
		ui_interface->declare(&fCheckbox0, "on", "Pink");
		ui_interface->addCheckButton("Type", &fCheckbox0);
		ui_interface->declare(&fHslider0, "1", "");
		ui_interface->addHorizontalSlider("Volume", &fHslider0, float(0.0), float(0.0), float(1.0), float(0.01));
		ui_interface->closeBox();
	}
	
	void compute(int count, [[maybe_unused]] float** inputs, float** outputs) override {
		float* output0 = outputs[0];
		double fSlow0 = static_cast<double>(fHslider0);
		int iSlow1 = static_cast<int>(static_cast<double>(fCheckbox0));
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iRec0[0] = 1103515245 * iRec0[1] + 12345;
			double fTemp0 = 4.656612875245797e-10 * static_cast<double>(iRec0[0]);
			fRec1[0] = 0.5221894 * fRec1[3] + fTemp0 + 2.494956002 * fRec1[1] - 2.017265875 * fRec1[2];
			output0[i0] = static_cast<float>(fSlow0 * ((iSlow1) ? 0.049922035 * fRec1[0] + 0.050612699 * fRec1[2] - (0.095993537 * fRec1[1] + 0.004408786 * fRec1[3]) : fTemp0));
			iRec0[1] = iRec0[0];
			for (int j0 = 3; j0 > 0; j0 = j0 - 1) {
				fRec1[j0] = fRec1[j0 - 1];
			}
		}
	}

	struct Parameters {
		float type;
		float volume;
	};

	inline void setParameters(Parameters& parameters) {
		fCheckbox0 = parameters.type;
		fHslider0 = parameters.volume;
	}

	inline void getParameters(Parameters& parameters) {
		parameters.type = fCheckbox0;
		parameters.volume = fHslider0;
	}

	inline void setType(float value) { fCheckbox0 = value; }
	inline void setVolume(float value) { fHslider0 = value; }

	inline float getType() { return fCheckbox0; }
	inline float getVolume() { return fHslider0; }
};
