//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtOsc
//

class OtOscSIG0 {
protected:	
	int iVec0[2];
	int iRec0[2];

public:	
	int getNumInputsOtOscSIG0() {
		return 0;
	}
	int getNumOutputsOtOscSIG0() {
		return 1;
	}
	
	void instanceInitOtOscSIG0([[maybe_unused]] int sample_rate) {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			iRec0[l1] = 0;
		}
	}
	
	void fillOtOscSIG0(int count, double* table) {
		for (int i1 = 0; i1 < count; i1 = i1 + 1) {
			iVec0[0] = 1;
			iRec0[0] = (iVec0[1] + iRec0[1]) % 65536;
			table[i1] = std::sin(9.587379924285257e-05 * static_cast<double>(iRec0[0]));
			iVec0[1] = iVec0[0];
			iRec0[1] = iRec0[0];
		}
	}

};

static OtOscSIG0* newOtOscSIG0() { return (OtOscSIG0*)new OtOscSIG0(); }
static void deleteOtOscSIG0(OtOscSIG0* dsp) { delete dsp; }

static double ftbl0OtOscSIG0[65536];
static double OtOsc_faustpower2_f(double value) {
	return value * value;
}

class OtOsc : public OtFaust {
protected:
	float fHslider0;
	int iVec1[2];
	int fSampleRate;
	double fConst0;
	double fConst1;
	double fRec1[2];
	double fConst2;
	double fConst3;
	double fConst4;
	double fRec3[2];
	double fVec2[2];
	int IOTA0;
	double fVec3[1024];
	double fConst5;
	double fRec2[2];
	double fRec4[2];
	double fConst6;
	
 public:
	OtOsc() {
	}
	
	OtOsc(const OtOsc&) = default;
	
	virtual ~OtOsc() = default;
	
	OtOsc& operator=(const OtOsc&) = default;
	
	void metadata(Meta* m) override { 
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Generator");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtOsc -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtOsc.dsp");
		m->declare("filters.lib/lowpass0_highpass1", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/pole:author", "Julius O. Smith III");
		m->declare("filters.lib/pole:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/pole:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Oscillator");
		m->declare("oscillators.lib/lf_sawpos:author", "Bart Brouns, revised by Stéphane Letz");
		m->declare("oscillators.lib/lf_sawpos:licence", "STK-4.3");
		m->declare("oscillators.lib/name", "Faust Oscillator Library");
		m->declare("oscillators.lib/saw2ptr:author", "Julius O. Smith III");
		m->declare("oscillators.lib/saw2ptr:license", "STK-4.3");
		m->declare("oscillators.lib/sawN:author", "Julius O. Smith III");
		m->declare("oscillators.lib/sawN:license", "STK-4.3");
		m->declare("oscillators.lib/version", "1.6.0");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
	}

	int getNumInputs() override {
		return 1;
	}
	int getNumOutputs() override {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
		OtOscSIG0* sig0 = newOtOscSIG0();
		sig0->instanceInitOtOscSIG0(sample_rate);
		sig0->fillOtOscSIG0(65536, ftbl0OtOscSIG0);
		deleteOtOscSIG0(sig0);
	}
	
	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 4.4e+02 / fConst0;
		fConst2 = 1.76e+03 / fConst0;
		fConst3 = 0.25 * fConst0;
		fConst4 = 1.0 / fConst0;
		fConst5 = 0.5 * fConst0;
		fConst6 = 0.7 * fConst0;
	}
	
	virtual void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(1.0);
	}
	
	virtual void instanceClear() {
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			iVec1[l2] = 0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec1[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec3[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fVec2[l5] = 0.0;
		}
		IOTA0 = 0;
		for (int l6 = 0; l6 < 1024; l6 = l6 + 1) {
			fVec3[l6] = 0.0;
		}
		for (int l7 = 0; l7 < 2; l7 = l7 + 1) {
			fRec2[l7] = 0.0;
		}
		for (int l8 = 0; l8 < 2; l8 = l8 + 1) {
			fRec4[l8] = 0.0;
		}
	}
	
	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
	
	virtual OtOsc* clone() {
		return new OtOsc(*this);
	}
	
	int getSampleRate() override {
		return fSampleRate;
	}
		
	void compute(int count, [[maybe_unused]] float** inputs, float** outputs) override {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = static_cast<double>(fHslider0);
		int iSlow1 = fSlow0 >= 4.0;
		int iSlow2 = fSlow0 >= 2.0;
		int iSlow3 = fSlow0 >= 1.0;
		int iSlow4 = fSlow0 >= 3.0;
		int iSlow5 = fSlow0 >= 6.0;
		int iSlow6 = fSlow0 >= 5.0;
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iVec1[0] = 1;
			int iTemp0 = 1 - iVec1[1];
			double fTemp1 = std::pow(2.0, static_cast<double>(input0[i0]));
			double fTemp2 = ((iTemp0) ? 0.0 : fRec1[1] + fConst1 * fTemp1);
			fRec1[0] = fTemp2 - std::floor(fTemp2);
			double fTemp3 = 4.4e+02 * fTemp1;
			double fTemp4 = std::max<double>(fTemp3, 23.44894968246214);
			double fTemp5 = std::max<double>(2e+01, std::fabs(fTemp4));
			double fTemp6 = ((iTemp0) ? 0.0 : fRec3[1] + fConst4 * fTemp5);
			fRec3[0] = fTemp6 - std::floor(fTemp6);
			double fTemp7 = OtOsc_faustpower2_f(2.0 * fRec3[0] + -1.0);
			fVec2[0] = fTemp7;
			double fTemp8 = static_cast<double>(iVec1[1]) * (fTemp7 - fVec2[1]) / fTemp5;
			fVec3[IOTA0 & 1023] = fTemp8;
			double fTemp9 = std::max<double>(0.0, std::min<double>(2047.0, fConst5 / fTemp4));
			int iTemp10 = static_cast<int>(fTemp9);
			double fTemp11 = std::floor(fTemp9);
			double fTemp12 = fConst3 * (fTemp8 - fVec3[(IOTA0 - iTemp10) & 1023] * (fTemp11 + (1.0 - fTemp9)) - (fTemp9 - fTemp11) * fVec3[(IOTA0 - (iTemp10 + 1)) & 1023]);
			fRec2[0] = 0.999 * fRec2[1] + fTemp12;
			double fTemp13 = fConst2 * fRec2[0] * fTemp1;
			double fTemp14 = std::max<double>(2.220446049250313e-16, std::fabs(fTemp3));
			double fTemp15 = fRec4[1] + fConst4 * fTemp14;
			double fTemp16 = fTemp15 + -1.0;
			int iTemp17 = fTemp16 < 0.0;
			fRec4[0] = ((iTemp17) ? fTemp15 : fTemp16);
			double fRec5 = ((iTemp17) ? fTemp15 : fTemp15 + (1.0 - fConst0 / fTemp14) * fTemp16);
			double fTemp18 = 2.0 * fRec5;
			double fTemp19 = std::max<double>(0.0, std::min<double>(2047.0, fConst6 / fTemp4));
			int iTemp20 = static_cast<int>(fTemp19);
			double fTemp21 = std::floor(fTemp19);
			output0[i0] = static_cast<float>(((iSlow1) ? ((iSlow5) ? fConst3 * (fTemp8 - fVec3[(IOTA0 - iTemp20) & 1023] * (fTemp21 + (1.0 - fTemp19)) - (fTemp19 - fTemp21) * fVec3[(IOTA0 - (iTemp20 + 1)) & 1023]) : ((iSlow6) ? fTemp12 : fTemp18 + -1.0)) : ((iSlow2) ? ((iSlow4) ? 0.6666666666666666 * (fTemp18 + fTemp13 + -1.0) : fTemp13) : ((iSlow3) ? ftbl0OtOscSIG0[std::max<int>(0, std::min<int>(static_cast<int>(65536.0 * fRec1[0]), 65535))] : 0.0))));
			iVec1[1] = iVec1[0];
			fRec1[1] = fRec1[0];
			fRec3[1] = fRec3[0];
			fVec2[1] = fVec2[0];
			IOTA0 = IOTA0 + 1;
			fRec2[1] = fRec2[0];
			fRec4[1] = fRec4[0];
		}
	}

	inline void calculateSizes() {
		width1 = std::max(width1, 100.0f);
		height1 += 20.0f;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginChild("Oscillator", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY);
		ImGui::SetNextItemWidth(100.0f);
		changed |= ImGui::SliderFloat("WaveForm", &fHslider0, 0.0f, 7.0f, "%.0f");
		ImGui::EndChild();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width1;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height1;
	}

	struct Parameters {
		float waveForm;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider0 = parameters.waveForm;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.waveForm = fHslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("waveForm", &fHslider0, 1.0f);
	}

	inline void setWaveForm(float value) { fHslider0 = value; }

	inline float getWaveForm() { return fHslider0; }

private:
	bool initialized = false;
	float width1;
	float height1;
};
