//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtOsc
//

static double OtOsc_faustpower2_f(double value) {
	return value * value;
}

class OtOsc : public OtFaust {
protected:
	float fHslider0;
	float fHslider1;
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fHslider2;
	int iVec0[2];
	double fConst2;
	double fConst3;
	double fRec1[2];
	double fVec1[2];
	int IOTA0;
	double fVec2[4096];
	double fConst4;
	double fRec0[2];
	double fRec2[2];
	float fHslider3;
	
 public:
	OtOsc() {
	}
	
	OtOsc(const OtOsc&) = default;
	
	virtual ~OtOsc() = default;
	
	OtOsc& operator=(const OtOsc&) = default;
	
	void metadata(Meta* m) override { 
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Generator");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtOsc -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtOsc.dsp");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/pole:author", "Julius O. Smith III");
		m->declare("filters.lib/pole:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/pole:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Oscillator");
		m->declare("oscillators.lib/lf_sawpos:author", "Bart Brouns, revised by Stéphane Letz");
		m->declare("oscillators.lib/lf_sawpos:licence", "STK-4.3");
		m->declare("oscillators.lib/name", "Faust Oscillator Library");
		m->declare("oscillators.lib/saw2ptr:author", "Julius O. Smith III");
		m->declare("oscillators.lib/saw2ptr:license", "STK-4.3");
		m->declare("oscillators.lib/sawN:author", "Julius O. Smith III");
		m->declare("oscillators.lib/sawN:license", "STK-4.3");
		m->declare("oscillators.lib/version", "1.6.0");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
	}

	int getNumInputs() override {
		return 0;
	}
	int getNumOutputs() override {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	virtual void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 4.0 / fConst0;
		fConst2 = 0.25 * fConst0;
		fConst3 = 1.0 / fConst0;
		fConst4 = 0.5 * fConst0;
	}
	
	virtual void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(7.0);
		fHslider1 = static_cast<float>(0.0);
		fHslider2 = static_cast<float>(4.4e+02);
		fHslider3 = static_cast<float>(0.5);
	}
	
	virtual void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec1[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fVec1[l2] = 0.0;
		}
		IOTA0 = 0;
		for (int l3 = 0; l3 < 4096; l3 = l3 + 1) {
			fVec2[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec0[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fRec2[l5] = 0.0;
		}
	}
	
	void init([[maybe_unused]] int sample_rate) override {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	virtual void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
	
	virtual OtOsc* clone() {
		return new OtOsc(*this);
	}
	
	int getSampleRate() override {
		return fSampleRate;
	}
		
	void compute(int count, [[maybe_unused]] float** inputs, float** outputs) override {
		float* output0 = outputs[0];
		double fSlow0 = 0.09090909090909091 * static_cast<double>(fHslider0);
		double fSlow1 = static_cast<double>(fHslider1);
		int iSlow2 = fSlow1 >= 2.0;
		int iSlow3 = fSlow1 >= 1.0;
		double fSlow4 = static_cast<double>(fHslider2);
		double fSlow5 = fConst1 * fSlow4;
		double fSlow6 = std::max<double>(fSlow4, 23.44894968246214);
		double fSlow7 = std::max<double>(2e+01, std::fabs(fSlow6));
		double fSlow8 = fConst2 / fSlow7;
		double fSlow9 = fConst3 * fSlow7;
		double fSlow10 = std::max<double>(0.0, std::min<double>(2047.0, fConst4 / fSlow6));
		double fSlow11 = std::floor(fSlow10);
		double fSlow12 = fSlow11 + (1.0 - fSlow10);
		int iSlow13 = static_cast<int>(fSlow10);
		double fSlow14 = fSlow10 - fSlow11;
		int iSlow15 = iSlow13 + 1;
		double fSlow16 = std::max<double>(2.220446049250313e-16, std::fabs(fSlow4));
		double fSlow17 = fConst3 * fSlow16;
		double fSlow18 = 1.0 - fConst0 / fSlow16;
		int iSlow19 = fSlow1 >= 3.0;
		double fSlow20 = std::max<double>(0.0, std::min<double>(2047.0, fConst0 * (static_cast<double>(fHslider3) / fSlow6)));
		double fSlow21 = std::floor(fSlow20);
		double fSlow22 = fSlow21 + (1.0 - fSlow20);
		int iSlow23 = static_cast<int>(fSlow20);
		double fSlow24 = fSlow20 - fSlow21;
		int iSlow25 = iSlow23 + 1;
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iVec0[0] = 1;
			double fTemp0 = ((1 - iVec0[1]) ? 0.0 : fSlow9 + fRec1[1]);
			fRec1[0] = fTemp0 - std::floor(fTemp0);
			double fTemp1 = OtOsc_faustpower2_f(2.0 * fRec1[0] + -1.0);
			fVec1[0] = fTemp1;
			double fTemp2 = fSlow8 * static_cast<double>(iVec0[1]) * (fTemp1 - fVec1[1]);
			fVec2[IOTA0 & 4095] = fTemp2;
			fRec0[0] = 0.999 * fRec0[1] + fTemp2 - (fSlow12 * fVec2[(IOTA0 - iSlow13) & 4095] + fSlow14 * fVec2[(IOTA0 - iSlow15) & 4095]);
			double fTemp3 = fSlow5 * fRec0[0];
			double fTemp4 = fSlow17 + fRec2[1] + -1.0;
			int iTemp5 = fTemp4 < 0.0;
			double fTemp6 = fSlow17 + fRec2[1];
			fRec2[0] = ((iTemp5) ? fTemp6 : fTemp4);
			double fRec3 = ((iTemp5) ? fTemp6 : fSlow17 + fRec2[1] + fSlow18 * fTemp4);
			double fTemp7 = 2.0 * fRec3;
			output0[i0] = static_cast<float>(fSlow0 * ((iSlow2) ? ((iSlow19) ? fTemp2 - (fSlow22 * fVec2[(IOTA0 - iSlow23) & 4095] + fSlow24 * fVec2[(IOTA0 - iSlow25) & 4095]) : fTemp7 + -1.0) : ((iSlow3) ? 0.5 * (fTemp7 + fTemp3 + -1.0) : fTemp3)));
			iVec0[1] = iVec0[0];
			fRec1[1] = fRec1[0];
			fVec1[1] = fVec1[0];
			IOTA0 = IOTA0 + 1;
			fRec0[1] = fRec0[0];
			fRec2[1] = fRec2[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing.x;
		width2 += knobWidth;
		height2 = std::max(height2, knobHeight);
		width2 += spacing;
		width2 += knobWidth;
		height2 = std::max(height2, knobHeight);
		width2 += spacing;
		width2 += knobWidth;
		height2 = std::max(height2, knobHeight);
		width1 = std::max(width1, width2);
		height1 += height2;
		width1 = std::max(width1, 0.0f);
		height1 += 0.0f;
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginChild("Oscillator", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY);
		ImGui::BeginChild("0x00", ImVec2(), ImGuiChildFlags_AutoResizeX | ImGuiChildFlags_AutoResizeY);
		changed |= OtUi::knob("Freq", &fHslider2, 60.0f, 6000.0f, "%.0f");
		ImGui::SameLine();
		changed |= OtUi::knob("PW", &fHslider3, 0.0f, 1.0f, "%.2f");
		ImGui::SameLine();
		changed |= OtUi::knob("Gain", &fHslider0, 0.0f, 11.0f, "%.2f");
		ImGui::EndChild();
		ImGui::EndChild();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float freq;
		float pW;
		float gain;
		float waveForm;
	};

	inline void setParameters([[maybe_unused]] Parameters& parameters) {
		fHslider2 = parameters.freq;
		fHslider3 = parameters.pW;
		fHslider0 = parameters.gain;
		fHslider1 = parameters.waveForm;
	}

	inline void getParameters([[maybe_unused]] Parameters& parameters) {
		parameters.freq = fHslider2;
		parameters.pW = fHslider3;
		parameters.gain = fHslider0;
		parameters.waveForm = fHslider1;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("freq", &fHslider2, 440.0f);
		callback("pW", &fHslider3, 0.5f);
		callback("gain", &fHslider0, 7.0f);
		callback("waveForm", &fHslider1, 0.0f);
	}

	inline void setFreq(float value) { fHslider2 = value; }
	inline void setPW(float value) { fHslider3 = value; }
	inline void setGain(float value) { fHslider0 = value; }
	inline void setWaveForm(float value) { fHslider1 = value; }

	inline float getFreq() { return fHslider2; }
	inline float getPW() { return fHslider3; }
	inline float getGain() { return fHslider0; }
	inline float getWaveForm() { return fHslider1; }

private:
	bool initialized = false;
	float width = -1.0f;
	float height = -1.0f;
	float width1;
	float height1;
	float width2;
	float height2;
};
