//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtPhaser
//

static double OtPhaser_faustpower2_f(double value) {
	return value * value;
}

class OtPhaser : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fVslider0;
	double fConst2;
	int iVec0[2];
	double fRec0[2];
	float fVslider1;
	double fRec10[2];
	double fConst3;
	double fConst4;
	double fConst5;
	double fConst6;
	float fVslider2;
	double fRec13[2];
	double fRec11[2];
	double fRec12[2];
	double fConst7;
	double fRec9[3];
	double fRec8[3];
	double fRec7[3];
	double fRec6[3];
	double fRec5[3];
	double fRec4[3];
	double fRec3[3];
	double fRec2[3];
	double fRec1[2];
	
 public:
	OtPhaser() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("category", "Modulation");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtPhaser -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtPhaser.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/nlf2:author", "Julius O. Smith III");
		m->declare("filters.lib/nlf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/nlf2:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Phaser");
		m->declare("oscillators.lib/name", "Faust Oscillator Library");
		m->declare("oscillators.lib/version", "1.6.0");
		m->declare("phaflangers.lib/name", "Faust Phaser and Flanger Library");
		m->declare("phaflangers.lib/version", "1.1.0");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 44.1 / fConst0;
		fConst2 = 1.0 - fConst1;
		fConst3 = std::exp(-(31415.926535897932 / fConst0));
		fConst4 = 2.0 * fConst3;
		fConst5 = 1.0 / fConst0;
		fConst6 = 6.283185307179586 / fConst0;
		fConst7 = OtPhaser_faustpower2_f(fConst3);
	}
	
	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(5e+01);
		fVslider1 = static_cast<float>(0.0);
		fVslider2 = static_cast<float>(1.0);
	}
	
	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec0[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec10[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec13[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec11[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fRec12[l5] = 0.0;
		}
		for (int l6 = 0; l6 < 3; l6 = l6 + 1) {
			fRec9[l6] = 0.0;
		}
		for (int l7 = 0; l7 < 3; l7 = l7 + 1) {
			fRec8[l7] = 0.0;
		}
		for (int l8 = 0; l8 < 3; l8 = l8 + 1) {
			fRec7[l8] = 0.0;
		}
		for (int l9 = 0; l9 < 3; l9 = l9 + 1) {
			fRec6[l9] = 0.0;
		}
		for (int l10 = 0; l10 < 3; l10 = l10 + 1) {
			fRec5[l10] = 0.0;
		}
		for (int l11 = 0; l11 < 3; l11 = l11 + 1) {
			fRec4[l11] = 0.0;
		}
		for (int l12 = 0; l12 < 3; l12 = l12 + 1) {
			fRec3[l12] = 0.0;
		}
		for (int l13 = 0; l13 < 3; l13 = l13 + 1) {
			fRec2[l13] = 0.0;
		}
		for (int l14 = 0; l14 < 2; l14 = l14 + 1) {
			fRec1[l14] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
		
	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = fConst1 * static_cast<double>(fVslider0);
		double fSlow1 = fConst1 * static_cast<double>(fVslider1);
		double fSlow2 = fConst1 * static_cast<double>(fVslider2);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			iVec0[0] = 1;
			fRec0[0] = fSlow0 + fConst2 * fRec0[1];
			fRec10[0] = fSlow1 + fConst2 * fRec10[1];
			fRec13[0] = fSlow2 + fConst2 * fRec13[1];
			double fTemp1 = fConst6 * fRec13[0];
			double fTemp2 = std::sin(fTemp1);
			double fTemp3 = std::cos(fTemp1);
			fRec11[0] = fRec12[1] * fTemp2 + fRec11[1] * fTemp3;
			fRec12[0] = static_cast<double>(1 - iVec0[1]) + fRec12[1] * fTemp3 - fTemp2 * fRec11[1];
			double fTemp4 = std::cos(fConst5 * (62769.02121872407 * (1.0 - fRec11[0]) + 125.66370614359172));
			fRec9[0] = fTemp0 + fRec10[0] * fRec1[1] + fConst4 * fRec9[1] * fTemp4 - fConst7 * fRec9[2];
			fRec8[0] = fRec9[2] + fConst7 * (fRec9[0] - fRec8[2]) - fConst4 * fTemp4 * (fRec9[1] - fRec8[1]);
			fRec7[0] = fRec8[2] + fConst7 * (fRec8[0] - fRec7[2]) - fConst4 * fTemp4 * (fRec8[1] - fRec7[1]);
			fRec6[0] = fRec7[2] + fConst7 * (fRec7[0] - fRec6[2]) - fConst4 * fTemp4 * (fRec7[1] - fRec6[1]);
			fRec5[0] = fRec6[2] + fConst7 * (fRec6[0] - fRec5[2]) - fConst4 * fTemp4 * (fRec6[1] - fRec5[1]);
			fRec4[0] = fRec5[2] + fConst7 * (fRec5[0] - fRec4[2]) - fConst4 * fTemp4 * (fRec5[1] - fRec4[1]);
			fRec3[0] = fRec4[2] + fConst7 * (fRec4[0] - fRec3[2]) - fConst4 * fTemp4 * (fRec4[1] - fRec3[1]);
			fRec2[0] = fRec3[2] + fConst7 * (fRec3[0] - fRec2[2]) - fConst4 * fTemp4 * (fRec3[1] - fRec2[1]);
			fRec1[0] = fRec2[2] + fConst7 * fRec2[0] - fConst4 * fTemp4 * fRec2[1];
			output0[i0] = static_cast<float>(fTemp0 * (1.0 - 0.005 * fRec0[0]) + 0.005 * fRec0[0] * fRec1[0]);
			iVec0[1] = iVec0[0];
			fRec0[1] = fRec0[0];
			fRec10[1] = fRec10[0];
			fRec13[1] = fRec13[0];
			fRec11[1] = fRec11[0];
			fRec12[1] = fRec12[0];
			fRec9[2] = fRec9[1];
			fRec9[1] = fRec9[0];
			fRec8[2] = fRec8[1];
			fRec8[1] = fRec8[0];
			fRec7[2] = fRec7[1];
			fRec7[1] = fRec7[0];
			fRec6[2] = fRec6[1];
			fRec6[1] = fRec6[0];
			fRec5[2] = fRec5[1];
			fRec5[1] = fRec5[0];
			fRec4[2] = fRec4[1];
			fRec4[1] = fRec4[0];
			fRec3[2] = fRec3[1];
			fRec3[1] = fRec3[0];
			fRec2[2] = fRec2[1];
			fRec2[1] = fRec2[0];
			fRec1[1] = fRec1[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Phaser");
		changed |= editSpeed();
		ImGui::SameLine();
		changed |= editDepth();
		ImGui::SameLine();
		changed |= editFeedbck();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float speed = 1.0f;
		float depth = 50.0f;
		float feedbck = 0.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider2 = parameters.speed;
		fVslider0 = parameters.depth;
		fVslider1 = parameters.feedbck;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.speed = fVslider2;
		parameters.depth = fVslider0;
		parameters.feedbck = fVslider1;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("speed", &fVslider2, 1.0f);
		callback("depth", &fVslider0, 50.0f);
		callback("feedbck", &fVslider1, 0.0f);
	}

	inline bool editSpeed() { return OtUi::knob("Speed", &fVslider2, 0.001f, 20.0f, "%.01fhz", false); }
	inline bool editDepth() { return OtUi::knob("Depth", &fVslider0, 0.0f, 100.0f, "%.0f%%", false); }
	inline bool editFeedbck() { return OtUi::knob("Feedbck", &fVslider1, -1.0f, 1.0f, "%.2f", false); }

	inline void setSpeed(float value) { fVslider2 = value; }
	inline void setDepth(float value) { fVslider0 = value; }
	inline void setFeedbck(float value) { fVslider1 = value; }

	inline float getSpeed() { return fVslider2; }
	inline float getDepth() { return fVslider0; }
	inline float getFeedbck() { return fVslider1; }

private:
	bool initialized = false;
	float width;
	float height;
};
