//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtPowerAmp
//

static double OtPowerAmp_faustpower2_f(double value) {
	return value * value;
}

class OtPowerAmp : public OtFaust {
protected:
	float fHslider0;
	double fRec3[2];
	int fSampleRate;
	double fConst0;
	double fConst1;
	double fConst2;
	float fHslider1;
	double fConst3;
	float fHslider2;
	double fConst4;
	double fRec4[2];
	double fConst5;
	double fConst6;
	double fConst7;
	double fRec6[3];
	double fConst8;
	double fRec5[3];
	double fConst9;
	double fConst10;
	double fRec7[2];
	float fHslider3;
	double fRec8[2];
	float fHslider4;
	double fRec9[2];
	double fVec0[2];
	double fRec2[2];
	double fRec1[2];
	double fRec0[2];
	
 public:
	OtPowerAmp() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("analyzers.lib/name", "Faust Analyzer Library");
		m->declare("analyzers.lib/version", "1.3.0");
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtPowerAmp -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtPowerAmp.dsp");
		m->declare("filters.lib/dcblocker:author", "Julius O. Smith III");
		m->declare("filters.lib/dcblocker:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/dcblocker:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/pole:author", "Julius O. Smith III");
		m->declare("filters.lib/pole:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/pole:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf1:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("filters.lib/zero:author", "Julius O. Smith III");
		m->declare("filters.lib/zero:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/zero:license", "MIT-style STK-4.3 license");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "OtPowerAmp");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
		m->declare("webaudio.lib/author", "GRAME");
		m->declare("webaudio.lib/copyright", "GRAME");
		m->declare("webaudio.lib/license", "LGPL with exception");
		m->declare("webaudio.lib/name", "Faust WebAudio Filters Library");
		m->declare("webaudio.lib/version", "1.1.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 3.141592653589793 * std::max<double>(0.01, std::min<double>(8e+03 / fConst0, 0.99));
		fConst2 = 0.5 * std::sin(fConst1);
		fConst3 = 44.1 / fConst0;
		fConst4 = 1.0 - fConst3;
		fConst5 = 3.141592653589793 * std::max<double>(0.01, std::min<double>(4e+03 / fConst0, 0.99));
		fConst6 = 0.5 * std::sin(fConst5);
		fConst7 = 2.0 * std::cos(fConst5);
		fConst8 = 2.0 * std::cos(fConst1);
		fConst9 = std::exp(-(25.0 / fConst0));
		fConst10 = 1.0 - fConst9;
	}
	
	inline void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(1.0);
		fHslider1 = static_cast<float>(0.0);
		fHslider2 = static_cast<float>(-0.4);
		fHslider3 = static_cast<float>(4.0);
		fHslider4 = static_cast<float>(1.0);
	}
	
	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fRec3[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec4[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 3; l2 = l2 + 1) {
			fRec6[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 3; l3 = l3 + 1) {
			fRec5[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec7[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fRec8[l5] = 0.0;
		}
		for (int l6 = 0; l6 < 2; l6 = l6 + 1) {
			fRec9[l6] = 0.0;
		}
		for (int l7 = 0; l7 < 2; l7 = l7 + 1) {
			fVec0[l7] = 0.0;
		}
		for (int l8 = 0; l8 < 2; l8 = l8 + 1) {
			fRec2[l8] = 0.0;
		}
		for (int l9 = 0; l9 < 2; l9 = l9 + 1) {
			fRec1[l9] = 0.0;
		}
		for (int l10 = 0; l10 < 2; l10 = l10 + 1) {
			fRec0[l10] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
		
	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = 0.0050000000000000044 * static_cast<double>(fHslider0);
		double fSlow1 = std::pow(1e+01, 0.025 * static_cast<double>(fHslider1));
		double fSlow2 = fConst2 / fSlow1;
		double fSlow3 = 1.0 / (fSlow2 + 1.0);
		double fSlow4 = fConst3 * static_cast<double>(fHslider2);
		double fSlow5 = fConst2 * fSlow1;
		double fSlow6 = fSlow5 + 1.0;
		double fSlow7 = fConst6 / fSlow1;
		double fSlow8 = 1.0 / (fSlow7 + 1.0);
		double fSlow9 = fConst6 * fSlow1;
		double fSlow10 = fSlow9 + 1.0;
		double fSlow11 = 1.0 - fSlow7;
		double fSlow12 = 1.0 - fSlow9;
		double fSlow13 = 1.0 - fSlow2;
		double fSlow14 = 1.0 - fSlow5;
		double fSlow15 = 0.0050000000000000044 * static_cast<double>(fHslider3);
		double fSlow16 = 0.0050000000000000044 * static_cast<double>(fHslider4);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			fRec3[0] = fSlow0 + 0.995 * fRec3[1];
			fRec4[0] = fSlow4 + fConst4 * fRec4[1];
			double fTemp0 = fConst7 * fRec6[1];
			fRec6[0] = fRec0[1] - fSlow8 * (fSlow11 * fRec6[2] - fTemp0);
			double fTemp1 = fConst8 * fRec5[1];
			fRec5[0] = fSlow8 * (fSlow10 * fRec6[0] - fTemp0 + fSlow12 * fRec6[2]) - fSlow3 * (fSlow13 * fRec5[2] - fTemp1);
			double fTemp2 = static_cast<double>(input0[i0]) + fSlow3 * fRec4[0] * (fSlow6 * fRec5[0] - fTemp1 + fSlow14 * fRec5[2]);
			double fTemp3 = std::fabs(fTemp2);
			fRec7[0] = std::max<double>(fTemp3, fConst9 * fRec7[1] + fConst10 * fTemp3);
			fRec8[0] = fSlow15 + 0.995 * fRec8[1];
			double fTemp4 = std::min<double>(3.0, std::max<double>(-3.0, fRec7[0] + fRec8[0] * fTemp2));
			fRec9[0] = fSlow16 + 0.995 * fRec9[1];
			double fTemp5 = OtPowerAmp_faustpower2_f(fRec9[0]);
			double fTemp6 = fTemp5 * OtPowerAmp_faustpower2_f(fTemp4);
			double fTemp7 = fTemp6 + 27.0;
			double fTemp8 = 9.0 * fTemp5 + 27.0;
			double fTemp9 = (9.0 * fTemp6 + 27.0) * (fTemp5 + 27.0);
			double fTemp10 = (1.0 - fRec3[0]) * fTemp2 + 0.24 * (fRec3[0] * fTemp4 * fTemp7 * fTemp8 / fTemp9);
			fVec0[0] = fTemp10;
			fRec2[0] = fVec0[1] - 0.24 * (fTemp4 * fTemp7 * fTemp8 * (fRec2[1] - fTemp10) / fTemp9);
			fRec1[0] = fRec2[0] + 0.995 * fRec1[1] - fRec2[1];
			fRec0[0] = fRec1[0];
			output0[i0] = static_cast<float>(4.0 * fRec0[0]);
			fRec3[1] = fRec3[0];
			fRec4[1] = fRec4[0];
			fRec6[2] = fRec6[1];
			fRec6[1] = fRec6[0];
			fRec5[2] = fRec5[1];
			fRec5[1] = fRec5[0];
			fRec7[1] = fRec7[0];
			fRec8[1] = fRec8[0];
			fRec9[1] = fRec9[0];
			fVec0[1] = fVec0[0];
			fRec2[1] = fRec2[0];
			fRec1[1] = fRec1[0];
			fRec0[1] = fRec0[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("PowerAmp");
		changed |= editCurve();
		ImGui::SameLine();
		changed |= editDrive();
		ImGui::SameLine();
		changed |= editSaturation();
		ImGui::SameLine();
		changed |= editPresence();
		ImGui::SameLine();
		changed |= editFeedback();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float curve = 1.0f;
		float drive = 4.0f;
		float saturation = 1.0f;
		float presence = 0.0f;
		float feedback = -0.4f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider4 = parameters.curve;
		fHslider3 = parameters.drive;
		fHslider0 = parameters.saturation;
		fHslider1 = parameters.presence;
		fHslider2 = parameters.feedback;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.curve = fHslider4;
		parameters.drive = fHslider3;
		parameters.saturation = fHslider0;
		parameters.presence = fHslider1;
		parameters.feedback = fHslider2;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("curve", &fHslider4, 1.0f);
		callback("drive", &fHslider3, 4.0f);
		callback("saturation", &fHslider0, 1.0f);
		callback("presence", &fHslider1, 0.0f);
		callback("feedback", &fHslider2, -0.4f);
	}

	inline bool editCurve() { return OtUi::knob("Curve", &fHslider4, 0.1f, 4.0f, "%.2f", false); }
	inline bool editDrive() { return OtUi::knob("Drive", &fHslider3, -10.0f, 10.0f, "%.2f", false); }
	inline bool editSaturation() { return OtUi::knob("Sat", &fHslider0, 0.0f, 1.0f, "%.2f", false); }
	inline bool editPresence() { return OtUi::knob("Pres", &fHslider1, -15.0f, 15.0f, "%.1f", false); }
	inline bool editFeedback() { return OtUi::knob("Fback", &fHslider2, -0.8f, 1.0f, "%.2f", false); }

	inline void setCurve(float value) { fHslider4 = value; }
	inline void setDrive(float value) { fHslider3 = value; }
	inline void setSaturation(float value) { fHslider0 = value; }
	inline void setPresence(float value) { fHslider1 = value; }
	inline void setFeedback(float value) { fHslider2 = value; }

	inline float getCurve() { return fHslider4; }
	inline float getDrive() { return fHslider3; }
	inline float getSaturation() { return fHslider0; }
	inline float getPresence() { return fHslider1; }
	inline float getFeedback() { return fHslider2; }

private:
	bool initialized = false;
	float width;
	float height;
};
