//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated by source/build.py
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"


//
//  OtToneStackPeavey
//

static double OtToneStackPeavey_faustpower2_f(double value) {
	return value * value;
}
static double OtToneStackPeavey_faustpower3_f(double value) {
	return value * value * value;
}

class OtToneStackPeavey : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	float fVslider0;
	float fVslider1;
	double fConst1;
	double fConst2;
	float fVslider2;
	double fConst3;
	double fRec0[4];

public:
	OtToneStackPeavey() {
		init(OtAudioSettings::sampleRate);
	}

	inline void metadata(Meta* m) {
		m->declare("category", "Equalizer");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtToneStackPeavey -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtToneStackPeavey.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Tone Stack");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("tonestacks.lib/author", "Guitarix project (<http://guitarix.sourceforge.net/>)");
		m->declare("tonestacks.lib/copyright", "Guitarix project");
		m->declare("tonestacks.lib/license", "LGPL");
		m->declare("tonestacks.lib/name", "Faust Tonestack Emulation Library");
		m->declare("tonestacks.lib/version", "1.28.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = 2.0 * std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = OtToneStackPeavey_faustpower2_f(fConst0);
		fConst2 = OtToneStackPeavey_faustpower3_f(fConst0);
		fConst3 = 3.0 * fConst2;
	}

	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(0.5);
		fVslider1 = static_cast<float>(0.5);
		fVslider2 = static_cast<float>(0.5);
	}

	inline void instanceClear() {
		for (int l0 = 0; l0 < 4; l0 = l0 + 1) {
			fRec0[l0] = 0.0;
		}
	}

	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	inline int getSampleRate() {
		return fSampleRate;
	}

	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = static_cast<double>(fVslider0);
		double fSlow1 = 0.00044 * fSlow0;
		double fSlow2 = std::exp(3.4 * (static_cast<double>(fVslider1) + -1.0));
		double fSlow3 = 0.0055675 * fSlow2;
		double fSlow4 = fConst0 * (fSlow1 + fSlow3 + 0.0035049);
		double fSlow5 = 1.95976e-07 * fSlow0;
		double fSlow6 = fConst1 * (fSlow0 * (2.4497000000000004e-06 * fSlow2 + -4.3256399999999996e-07 - fSlow5) + 8.801210000000002e-06 * fSlow2 + 9.060568000000001e-07);
		double fSlow7 = fSlow4 + fSlow6;
		double fSlow8 = 2.0778120000000008e-10 * fSlow2 - 1.6622496000000003e-11 * fSlow0;
		double fSlow9 = 5.553900000000002e-10 * fSlow2;
		double fSlow10 = fConst2 * (fSlow0 * (fSlow8 + -2.7808704000000013e-11) + fSlow9 + 4.4431200000000016e-11);
		double fSlow11 = 1.0 / (-1.0 - (fSlow7 + fSlow10));
		double fSlow12 = static_cast<double>(fVslider2);
		double fSlow13 = fConst1 * (2.0196000000000004e-07 * fSlow12 + fSlow0 * (2.2567600000000002e-07 - fSlow5) + fSlow2 * (2.4497000000000004e-06 * fSlow0 + 5.732100000000001e-07) + 4.585680000000001e-08);
		double fSlow14 = fSlow0 * (fSlow8 + 1.6622496000000003e-11) + fSlow12 * (fSlow9 + 4.4431200000000016e-11 * (1.0 - fSlow0));
		double fSlow15 = fConst3 * fSlow14;
		double fSlow16 = fConst0 * (fSlow3 + fSlow1 + 6.75e-05 * fSlow12 + 0.00044540000000000004);
		double fSlow17 = fSlow13 + fSlow15 - fSlow16;
		double fSlow18 = fSlow6 - (fSlow4 + 3.0 * (1.0 - fSlow10));
		double fSlow19 = fSlow7 - 3.0 * (fSlow10 + 1.0);
		double fSlow20 = fSlow4 + fSlow10 + (-1.0 - fSlow6);
		double fSlow21 = fSlow16 + fSlow13;
		double fSlow22 = fSlow21 - fSlow15;
		double fSlow23 = fConst2 * fSlow14;
		double fSlow24 = fSlow16 + fSlow23 - fSlow13;
		double fSlow25 = fSlow21 + fSlow23;
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			fRec0[0] = static_cast<double>(input0[i0]) - fSlow11 * (fSlow18 * fRec0[1] + fSlow19 * fRec0[2] + fSlow20 * fRec0[3]);
			output0[i0] = static_cast<float>(fSlow11 * (fSlow17 * fRec0[1] + fSlow22 * fRec0[2] + fSlow24 * fRec0[3] - fSlow25 * fRec0[0]));
			for (int j0 = 3; j0 > 0; j0 = j0 - 1) {
				fRec0[j0] = fRec0[j0 - 1];
			}
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtAudioUi::knobWidth();
		auto knobHeight = OtAudioUi::knobHeight();
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 = std::max(width1, knobWidth);
		height1 += knobHeight;
		width1 = std::max(width1, knobWidth);
		height1 += knobHeight;
		width1 = std::max(width1, knobWidth);
		height1 += knobHeight;
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Tone Stack");
		changed |= editBass();
		changed |= editMiddle();
		changed |= editTreble();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float bass = 0.5f;
		float middle = 0.5f;
		float treble = 0.5f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider1 = parameters.bass;
		fVslider0 = parameters.middle;
		fVslider2 = parameters.treble;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.bass = fVslider1;
		parameters.middle = fVslider0;
		parameters.treble = fVslider2;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("bass", &fVslider1, 0.5f);
		callback("middle", &fVslider0, 0.5f);
		callback("treble", &fVslider2, 0.5f);
	}

	inline bool editBass() { return OtAudioUi::knob("Bass", &fVslider1, 0.0f, 1.0f, "%.2f", false); }
	inline bool editMiddle() { return OtAudioUi::knob("Middle", &fVslider0, 0.0f, 1.0f, "%.2f", false); }
	inline bool editTreble() { return OtAudioUi::knob("Treble", &fVslider2, 0.0f, 1.0f, "%.2f", false); }

	inline void setBass(float value) { fVslider1 = value; }
	inline void setMiddle(float value) { fVslider0 = value; }
	inline void setTreble(float value) { fVslider2 = value; }

	inline float getBass() { return fVslider1; }
	inline float getMiddle() { return fVslider0; }
	inline float getTreble() { return fVslider2; }

private:
	bool initialized = false;
	float width;
	float height;
};
