//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated by source/build.py
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"


//
//  OtTremolo
//

class OtTremolo : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fVslider0;
	double fConst2;
	int iVec0[2];
	double fRec0[2];
	double fConst3;
	float fVslider1;
	double fRec3[2];
	double fRec4[2];
	double fRec2[2];
	double fRec1[2];

public:
	OtTremolo() {
		init(OtAudioSettings::sampleRate);
	}

	inline void metadata(Meta* m) {
		m->declare("category", "Modulation");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtTremolo -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtTremolo.dsp");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Tremolo");
		m->declare("oscillators.lib/name", "Faust Oscillator Library");
		m->declare("oscillators.lib/version", "1.7.0");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 44.1 / fConst0;
		fConst2 = 1.0 - fConst1;
		fConst3 = 6.283185307179586 / fConst0;
	}

	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(5e+01);
		fVslider1 = static_cast<float>(8.0);
	}

	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec0[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec3[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec4[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec2[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fRec1[l5] = 0.0;
		}
	}

	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	inline int getSampleRate() {
		return fSampleRate;
	}

	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = fConst1 * static_cast<double>(fVslider0);
		double fSlow1 = fConst1 * static_cast<double>(fVslider1);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iVec0[0] = 1;
			fRec0[0] = fSlow0 + fConst2 * fRec0[1];
			fRec3[0] = fSlow1 + fConst2 * fRec3[1];
			fRec4[0] = fRec4[1] - fConst3 * fRec3[0] * fRec1[1];
			fRec2[0] = fConst3 * fRec3[0] * fRec4[0] + static_cast<double>(1 - iVec0[1]) + fRec2[1];
			fRec1[0] = fRec2[0];
			output0[i0] = static_cast<float>(static_cast<double>(input0[i0]) * (1.0 - 0.01 * fRec0[0] * (1.0 - std::max<double>(0.0, 0.5 * (fRec1[0] + 1.0)))));
			iVec0[1] = iVec0[0];
			fRec0[1] = fRec0[0];
			fRec3[1] = fRec3[0];
			fRec4[1] = fRec4[0];
			fRec2[1] = fRec2[0];
			fRec1[1] = fRec1[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtAudioUi::knobWidth();
		auto knobHeight = OtAudioUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Tremolo");
		changed |= editSpeed();
		ImGui::SameLine();
		changed |= editDepth();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float speed = 8.0f;
		float depth = 50.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider1 = parameters.speed;
		fVslider0 = parameters.depth;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.speed = fVslider1;
		parameters.depth = fVslider0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("speed", &fVslider1, 8.0f);
		callback("depth", &fVslider0, 50.0f);
	}

	inline bool editSpeed() { return OtAudioUi::knob("Speed", &fVslider1, 0.1f, 50.0f, "%.01fhz", false); }
	inline bool editDepth() { return OtAudioUi::knob("Depth", &fVslider0, 0.0f, 100.0f, "%.0f%%", false); }

	inline void setSpeed(float value) { fVslider1 = value; }
	inline void setDepth(float value) { fVslider0 = value; }

	inline float getSpeed() { return fVslider1; }
	inline float getDepth() { return fVslider0; }

private:
	bool initialized = false;
	float width;
	float height;
};
