//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated by source/build.py
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"
#include "OtTube.h"


//
//  OtTubePre12AX7
//

class OtTubePre12AX7 : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	double fConst2;
	double fConst3;
	double fConst4;
	double fConst5;
	double fConst6;
	double fConst7;
	float fVslider0;
	double fRec5[2];
	double fVec0[2];
	double fRec14[2];
	double fRec13[3];
	double fConst8;
	double fConst9;
	double fVec1[2];
	double fConst10;
	double fRec15[2];
	double fRec12[2];
	double fConst11;
	double fRec11[2];
	double fVec2[2];
	double fRec10[2];
	double fRec9[2];
	double fRec8[3];
	double fConst12;
	double fConst13;
	double fVec3[2];
	double fConst14;
	double fRec16[2];
	double fRec7[2];
	double fRec6[2];
	double fVec4[2];
	double fRec4[2];
	double fRec3[2];
	double fRec2[3];
	double fConst15;
	double fConst16;
	double fVec5[2];
	double fConst17;
	double fRec17[2];
	double fRec1[2];
	double fRec0[2];
	float fVslider1;
	double fRec18[2];

public:
	OtTubePre12AX7() {
		init(OtAudioSettings::sampleRate);
	}

	inline void metadata(Meta* m) {
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtTubePre12AX7 -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("filename", "OtTubePre12AX7.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/highpass:author", "Julius O. Smith III");
		m->declare("filters.lib/highpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowpass:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/tf1:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf1s:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1s:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf2s:author", "Julius O. Smith III");
		m->declare("filters.lib/tf2s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf2s:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "OtTubePre12AX7");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = std::tan(97.38937226128358 / fConst0);
		fConst2 = 1.0 / fConst1;
		fConst3 = 1.0 / (fConst2 + 1.0);
		fConst4 = 0.025 / fConst1;
		fConst5 = 1.0 / std::tan(20517.741620594938 / fConst0);
		fConst6 = 1.0 / (fConst5 + 1.0);
		fConst7 = 1.0 - fConst5;
		fConst8 = 1.0 / std::tan(270.1769682087222 / fConst0);
		fConst9 = 1.0 / (fConst8 + 1.0);
		fConst10 = 1.0 - fConst8;
		fConst11 = 1.0 - fConst2;
		fConst12 = 1.0 / std::tan(414.6902302738527 / fConst0);
		fConst13 = 1.0 / (fConst12 + 1.0);
		fConst14 = 1.0 - fConst12;
		fConst15 = 1.0 / std::tan(609.4689747964198 / fConst0);
		fConst16 = 1.0 / (fConst15 + 1.0);
		fConst17 = 1.0 - fConst15;
	}

	inline void instanceResetUserInterface() {
		fVslider0 = static_cast<float>(-6.0);
		fVslider1 = static_cast<float>(0.0);
	}

	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fRec5[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fVec0[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fRec14[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 3; l3 = l3 + 1) {
			fRec13[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fVec1[l4] = 0.0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			fRec15[l5] = 0.0;
		}
		for (int l6 = 0; l6 < 2; l6 = l6 + 1) {
			fRec12[l6] = 0.0;
		}
		for (int l7 = 0; l7 < 2; l7 = l7 + 1) {
			fRec11[l7] = 0.0;
		}
		for (int l8 = 0; l8 < 2; l8 = l8 + 1) {
			fVec2[l8] = 0.0;
		}
		for (int l9 = 0; l9 < 2; l9 = l9 + 1) {
			fRec10[l9] = 0.0;
		}
		for (int l10 = 0; l10 < 2; l10 = l10 + 1) {
			fRec9[l10] = 0.0;
		}
		for (int l11 = 0; l11 < 3; l11 = l11 + 1) {
			fRec8[l11] = 0.0;
		}
		for (int l12 = 0; l12 < 2; l12 = l12 + 1) {
			fVec3[l12] = 0.0;
		}
		for (int l13 = 0; l13 < 2; l13 = l13 + 1) {
			fRec16[l13] = 0.0;
		}
		for (int l14 = 0; l14 < 2; l14 = l14 + 1) {
			fRec7[l14] = 0.0;
		}
		for (int l15 = 0; l15 < 2; l15 = l15 + 1) {
			fRec6[l15] = 0.0;
		}
		for (int l16 = 0; l16 < 2; l16 = l16 + 1) {
			fVec4[l16] = 0.0;
		}
		for (int l17 = 0; l17 < 2; l17 = l17 + 1) {
			fRec4[l17] = 0.0;
		}
		for (int l18 = 0; l18 < 2; l18 = l18 + 1) {
			fRec3[l18] = 0.0;
		}
		for (int l19 = 0; l19 < 3; l19 = l19 + 1) {
			fRec2[l19] = 0.0;
		}
		for (int l20 = 0; l20 < 2; l20 = l20 + 1) {
			fVec5[l20] = 0.0;
		}
		for (int l21 = 0; l21 < 2; l21 = l21 + 1) {
			fRec17[l21] = 0.0;
		}
		for (int l22 = 0; l22 < 2; l22 = l22 + 1) {
			fRec1[l22] = 0.0;
		}
		for (int l23 = 0; l23 < 2; l23 = l23 + 1) {
			fRec0[l23] = 0.0;
		}
		for (int l24 = 0; l24 < 2; l24 = l24 + 1) {
			fRec18[l24] = 0.0;
		}
	}

	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	inline int getSampleRate() {
		return fSampleRate;
	}

	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = 0.0010000000000000009 * std::pow(1e+01, 0.05 * static_cast<double>(fVslider0));
		double fSlow1 = 0.0010000000000000009 * std::pow(1e+01, 0.05 * static_cast<double>(fVslider1));
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			fRec5[0] = fSlow0 + 0.999 * fRec5[1];
			double fTemp0 = static_cast<double>(input0[i0]);
			fVec0[0] = fTemp0;
			fRec14[0] = 0.9302847925323914 * (fTemp0 + fVec0[1]) - 0.8605695850647829 * fRec14[1];
			fRec13[0] = fRec14[0] - (1.8405051250752198 * fRec13[1] + 0.8612942439318627 * fRec13[2]);
			double fTemp1 = 0.9254498422517706 * (fRec13[0] + fRec13[2]);
			double fTemp2 = 1.8508996845035413 * fRec13[1];
			double fTemp3 = (fTemp2 + fTemp1) / (OtTubeGetR(TUBE_TABLE_12AX7_68k, fRec12[1]) + 1e+05);
			fVec1[0] = fTemp3;
			fRec15[0] = fConst9 * (2.7e+03 * (fTemp3 + fVec1[1]) - fConst10 * fRec15[1]);
			fRec12[0] = OtTubeGetF(TUBE_TABLE_12AX7_68k, fTemp1 + fRec15[0] + fTemp2 + -1.581656) + -191.42014814814814;
			fRec11[0] = fConst3 * (fConst4 * (fRec12[0] - fRec12[1]) - fConst11 * fRec11[1]);
			double fTemp4 = fRec11[0] * fRec5[0];
			fVec2[0] = fTemp4;
			fRec10[0] = -(fConst6 * (fConst7 * fRec10[1] - (fTemp4 + fVec2[1])));
			fRec9[0] = 0.9302847925323914 * (fRec10[0] + fRec10[1]) - 0.8605695850647829 * fRec9[1];
			fRec8[0] = fRec9[0] - (1.8405051250752198 * fRec8[1] + 0.8612942439318627 * fRec8[2]);
			double fTemp5 = 0.9254498422517706 * (fRec8[0] + fRec8[2]);
			double fTemp6 = 1.8508996845035413 * fRec8[1];
			double fTemp7 = (fTemp6 + fTemp5) / (OtTubeGetR(TUBE_TABLE_12AX7_250k, fRec7[1]) + 1e+05);
			fVec3[0] = fTemp7;
			fRec16[0] = fConst13 * (1.5e+03 * (fTemp7 + fVec3[1]) - fConst14 * fRec16[1]);
			fRec7[0] = OtTubeGetF(TUBE_TABLE_12AX7_250k, fTemp5 + fRec16[0] + fTemp6 + -1.204285) + -169.71433333333334;
			fRec6[0] = fConst3 * (fConst4 * (fRec7[0] - fRec7[1]) - fConst11 * fRec6[1]);
			double fTemp8 = fRec5[0] * fRec6[0];
			fVec4[0] = fTemp8;
			fRec4[0] = -(fConst6 * (fConst7 * fRec4[1] - (fTemp8 + fVec4[1])));
			fRec3[0] = 0.9302847925323914 * (fRec4[0] + fRec4[1]) - 0.8605695850647829 * fRec3[1];
			fRec2[0] = fRec3[0] - (1.8405051250752198 * fRec2[1] + 0.8612942439318627 * fRec2[2]);
			double fTemp9 = 0.9254498422517706 * (fRec2[0] + fRec2[2]);
			double fTemp10 = 1.8508996845035413 * fRec2[1];
			double fTemp11 = (fTemp10 + fTemp9) / (OtTubeGetR(TUBE_TABLE_12AX7_250k, fRec1[1]) + 1e+05);
			fVec5[0] = fTemp11;
			fRec17[0] = fConst16 * (8.2e+02 * (fTemp11 + fVec5[1]) - fConst17 * fRec17[1]);
			fRec1[0] = OtTubeGetF(TUBE_TABLE_12AX7_250k, fTemp9 + fRec17[0] + fTemp10 + -0.840703) + -147.47524390243905;
			fRec0[0] = fConst3 * (fConst4 * (fRec1[0] - fRec1[1]) - fConst11 * fRec0[1]);
			fRec18[0] = fSlow1 + 0.999 * fRec18[1];
			output0[i0] = static_cast<float>(fRec0[0] * fRec18[0]);
			fRec5[1] = fRec5[0];
			fVec0[1] = fVec0[0];
			fRec14[1] = fRec14[0];
			fRec13[2] = fRec13[1];
			fRec13[1] = fRec13[0];
			fVec1[1] = fVec1[0];
			fRec15[1] = fRec15[0];
			fRec12[1] = fRec12[0];
			fRec11[1] = fRec11[0];
			fVec2[1] = fVec2[0];
			fRec10[1] = fRec10[0];
			fRec9[1] = fRec9[0];
			fRec8[2] = fRec8[1];
			fRec8[1] = fRec8[0];
			fVec3[1] = fVec3[0];
			fRec16[1] = fRec16[0];
			fRec7[1] = fRec7[0];
			fRec6[1] = fRec6[0];
			fVec4[1] = fVec4[0];
			fRec4[1] = fRec4[0];
			fRec3[1] = fRec3[0];
			fRec2[2] = fRec2[1];
			fRec2[1] = fRec2[0];
			fVec5[1] = fVec5[0];
			fRec17[1] = fRec17[0];
			fRec1[1] = fRec1[0];
			fRec0[1] = fRec0[0];
			fRec18[1] = fRec18[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width1 += spacing.x;
		width1 += knobWidth;
		height1 = std::max(height1, knobHeight);
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("preamp");
		changed |= editGain();
		ImGui::SameLine();
		changed |= editVolume();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float gain = -6.0f;
		float volume = 0.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fVslider0 = parameters.gain;
		fVslider1 = parameters.volume;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.gain = fVslider0;
		parameters.volume = fVslider1;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("gain", &fVslider0, -6.0f);
		callback("volume", &fVslider1, 0.0f);
	}

	inline bool editGain() { return OtUi::knob("Gain", &fVslider0, -20.0f, 20.0f, "%.1fdB", false); }
	inline bool editVolume() { return OtUi::knob("Volume", &fVslider1, -20.0f, 20.0f, "%.1fdB", false); }

	inline void setGain(float value) { fVslider0 = value; }
	inline void setVolume(float value) { fVslider1 = value; }

	inline float getGain() { return fVslider0; }
	inline float getVolume() { return fVslider1; }

private:
	bool initialized = false;
	float width;
	float height;
};
