//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated by source/build.py
//


#pragma once


//
//	Include files
//

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <math.h>

#include "OtFaust.h"
#include "OtTs9.h"


//
//  OtTubeScreamer
//

class OtTubeScreamer : public OtFaust {
protected:
	int fSampleRate;
	double fConst0;
	double fConst1;
	float fHslider0;
	double fVec0[2];
	double fConst2;
	double fConst3;
	double fConst4;
	double fConst5;
	float fHslider1;
	double fRec1[2];
	double fVec1[2];
	double fRec0[2];
	float fHslider2;
	double fRec2[2];

public:
	OtTubeScreamer() {
		init(OtAudioSettings::sampleRate);
	}

	inline void metadata(Meta* m) {
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Distortion");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtTubeScreamer -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("description", "Ibanez TS-9 simulation");
		m->declare("filename", "OtTubeScreamer.dsp");
		m->declare("filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowpass0_highpass1:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:author", "Julius O. Smith III");
		m->declare("filters.lib/lowpass:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/lowpass:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/tf1:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/tf1s:author", "Julius O. Smith III");
		m->declare("filters.lib/tf1s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/tf1s:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Tube Screamer");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 1;
	}
	inline int getNumOutputs() {
		return 1;
	}

	static void classInit([[maybe_unused]] int sample_rate) {
	}

	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 3.141592653589793 / fConst0;
		fConst2 = 0.00044179999999999995 * fConst0;
		fConst3 = 1.0 / (fConst2 + 1.0);
		fConst4 = 1.0 - fConst2;
		fConst5 = 9.4e-08 * fConst0;
	}

	inline void instanceResetUserInterface() {
		fHslider0 = static_cast<float>(4e+02);
		fHslider1 = static_cast<float>(0.5);
		fHslider2 = static_cast<float>(-16.0);
	}

	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			fVec0[l0] = 0.0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			fRec1[l1] = 0.0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			fVec1[l2] = 0.0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec0[l3] = 0.0;
		}
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			fRec2[l4] = 0.0;
		}
	}

	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}

	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}

	inline int getSampleRate() {
		return fSampleRate;
	}

	inline void compute(int count, [[maybe_unused]] float** inputs, float** outputs) {
		float* input0 = inputs[0];
		float* output0 = outputs[0];
		double fSlow0 = 1.0 / std::tan(fConst1 * static_cast<double>(fHslider0));
		double fSlow1 = 1.0 / (fSlow0 + 1.0);
		double fSlow2 = 1.0 - fSlow0;
		double fSlow3 = fConst5 * (5e+05 * static_cast<double>(fHslider1) + 5.57e+04);
		double fSlow4 = fSlow3 + 1.0;
		double fSlow5 = 1.0 - fSlow3;
		double fSlow6 = 0.0010000000000000009 * std::pow(1e+01, 0.05 * static_cast<double>(fHslider2));
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			double fTemp0 = static_cast<double>(input0[i0]);
			fVec0[0] = fTemp0;
			fRec1[0] = -(fConst3 * (fConst4 * fRec1[1] - (fSlow4 * fTemp0 + fSlow5 * fVec0[1])));
			double fTemp1 = fTemp0 - OtTs9(fRec1[0] - fTemp0);
			fVec1[0] = fTemp1;
			fRec0[0] = -(fSlow1 * (fSlow2 * fRec0[1] - (fTemp1 + fVec1[1])));
			fRec2[0] = fSlow6 + 0.999 * fRec2[1];
			output0[i0] = static_cast<float>(fRec0[0] * fRec2[0]);
			fVec0[1] = fVec0[0];
			fRec1[1] = fRec1[0];
			fVec1[1] = fVec1[0];
			fRec0[1] = fRec0[0];
			fRec2[1] = fRec2[0];
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtAudioUi::knobWidth();
		auto knobHeight = OtAudioUi::knobHeight();
		float width1 = 0.0f;
		float height1 = 0.0f;
		width1 = std::max(width1, knobWidth);
		height1 += knobHeight;
		width1 = std::max(width1, knobWidth);
		height1 += knobHeight;
		width1 = std::max(width1, knobWidth);
		height1 += knobHeight;
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Tube Screamer");
		changed |= editDrive();
		changed |= editTone();
		changed |= editLevel();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float drive = 0.5f;
		float tone = 400.0f;
		float level = -16.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider1 = parameters.drive;
		fHslider0 = parameters.tone;
		fHslider2 = parameters.level;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.drive = fHslider1;
		parameters.tone = fHslider0;
		parameters.level = fHslider2;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("drive", &fHslider1, 0.5f);
		callback("tone", &fHslider0, 400.0f);
		callback("level", &fHslider2, -16.0f);
	}

	inline bool editDrive() { return OtAudioUi::knob("Drive", &fHslider1, 0.0f, 1.0f, "%.2f", false); }
	inline bool editTone() { return OtAudioUi::knob("Tone", &fHslider0, 100.0f, 1000.0f, "%.0f", false); }
	inline bool editLevel() { return OtAudioUi::knob("Level", &fHslider2, -20.0f, 4.0f, "%.1fdB", false); }

	inline void setDrive(float value) { fHslider1 = value; }
	inline void setTone(float value) { fHslider0 = value; }
	inline void setLevel(float value) { fHslider2 = value; }

	inline float getDrive() { return fHslider1; }
	inline float getTone() { return fHslider0; }
	inline float getLevel() { return fHslider2; }

private:
	bool initialized = false;
	float width;
	float height;
};
