//	ObjectTalk Scripting Language
//	Copyright (c) 1993-2026 Johan A. Goossens. All rights reserved.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


//
//	Do not edit this file, it is automatically generated
//


#pragma once


//
//	Include files
//

#include "OtFaust.h"


//
//  OtVoice
//

class OtVoiceSIG0 {
protected:	
	int iVec2[2];
	int iRec2[2];

public:	
	int getNumInputsOtVoiceSIG0() {
		return 0;
	}
	int getNumOutputsOtVoiceSIG0() {
		return 1;
	}
	
	void instanceInitOtVoiceSIG0([[maybe_unused]] int sample_rate) {
		for (int l4 = 0; l4 < 2; l4 = l4 + 1) {
			iVec2[l4] = 0;
		}
		for (int l5 = 0; l5 < 2; l5 = l5 + 1) {
			iRec2[l5] = 0;
		}
	}
	
	void fillOtVoiceSIG0(int count, double* table) {
		for (int i1 = 0; i1 < count; i1 = i1 + 1) {
			iVec2[0] = 1;
			iRec2[0] = (iVec2[1] + iRec2[1]) % 65536;
			table[i1] = std::sin(9.587379924285257e-05 * static_cast<double>(iRec2[0]));
			iVec2[1] = iVec2[0];
			iRec2[1] = iRec2[0];
		}
	}

};

static OtVoiceSIG0* newOtVoiceSIG0() { return (OtVoiceSIG0*)new OtVoiceSIG0(); }
static void deleteOtVoiceSIG0(OtVoiceSIG0* dsp) { delete dsp; }

static double ftbl0OtVoiceSIG0[65536];
static double OtVoice_faustpower2_f(double value) {
	return value * value;
}

class OtVoice : public OtFaust {
protected:
	float fButton0;
	int iVec0[2];
	float fVslider0;
	int iVec1[2];
	int iRec1[2];
	int fSampleRate;
	double fConst0;
	float fVslider1;
	float fVslider2;
	double fConst1;
	float fVslider3;
	double fRec0[2];
	float fHslider0;
	float fHslider1;
	float fHslider2;
	double fRec3[2];
	double fConst2;
	double fConst3;
	double fRec5[2];
	double fVec3[2];
	int IOTA0;
	double fVec4[4096];
	double fConst4;
	double fRec4[2];
	double fRec6[2];
	double fConst5;
	float fHslider3;
	float fHslider4;
	float fHslider5;
	double fRec8[2];
	double fRec10[2];
	double fVec5[2];
	double fVec6[4096];
	double fRec9[2];
	double fRec11[2];
	float fHslider6;
	int iRec13[2];
	float fHslider7;
	double fRec14[4];
	
 public:
	OtVoice() {
		init(OtAudioSettings::sampleRate);
	}
				
	inline void metadata(Meta* m) { 
		m->declare("basics.lib/name", "Faust Basic Element Library");
		m->declare("basics.lib/version", "1.22.0");
		m->declare("category", "Generator");
		m->declare("compile_options", "-lang cpp -fpga-mem-th 4 -ct 1 -cn OtVoice -scn OtFaust -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0");
		m->declare("envelopes.lib/adsre:author", "Julius O. Smith III");
		m->declare("envelopes.lib/adsre:licence", "STK-4.3");
		m->declare("envelopes.lib/author", "GRAME");
		m->declare("envelopes.lib/copyright", "GRAME");
		m->declare("envelopes.lib/license", "LGPL with exception");
		m->declare("envelopes.lib/name", "Faust Envelope Library");
		m->declare("envelopes.lib/version", "1.3.0");
		m->declare("filename", "OtVoice.dsp");
		m->declare("filters.lib/fir:author", "Julius O. Smith III");
		m->declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/fir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/iir:author", "Julius O. Smith III");
		m->declare("filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/iir:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/lowpass0_highpass1", "MIT-style STK-4.3 license");
		m->declare("filters.lib/name", "Faust Filters Library");
		m->declare("filters.lib/pole:author", "Julius O. Smith III");
		m->declare("filters.lib/pole:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
		m->declare("filters.lib/pole:license", "MIT-style STK-4.3 license");
		m->declare("filters.lib/version", "1.7.1");
		m->declare("license", "MIT");
		m->declare("maths.lib/author", "GRAME");
		m->declare("maths.lib/copyright", "GRAME");
		m->declare("maths.lib/license", "LGPL with exception");
		m->declare("maths.lib/name", "Faust Math Library");
		m->declare("maths.lib/version", "2.9.0");
		m->declare("name", "Voice");
		m->declare("noises.lib/name", "Faust Noise Generator Library");
		m->declare("noises.lib/version", "1.5.0");
		m->declare("oscillators.lib/lf_sawpos:author", "Bart Brouns, revised by Stéphane Letz");
		m->declare("oscillators.lib/lf_sawpos:licence", "STK-4.3");
		m->declare("oscillators.lib/name", "Faust Oscillator Library");
		m->declare("oscillators.lib/saw2ptr:author", "Julius O. Smith III");
		m->declare("oscillators.lib/saw2ptr:license", "STK-4.3");
		m->declare("oscillators.lib/sawN:author", "Julius O. Smith III");
		m->declare("oscillators.lib/sawN:license", "STK-4.3");
		m->declare("oscillators.lib/version", "1.6.0");
		m->declare("platform.lib/name", "Generic Platform Library");
		m->declare("platform.lib/version", "1.3.0");
		m->declare("signals.lib/name", "Faust Signal Routing Library");
		m->declare("signals.lib/version", "1.6.0");
	}

	inline int getNumInputs() {
		return 0;
	}
	inline int getNumOutputs() {
		return 1;
	}
	
	static void classInit([[maybe_unused]] int sample_rate) {
		OtVoiceSIG0* sig0 = newOtVoiceSIG0();
		sig0->instanceInitOtVoiceSIG0(sample_rate);
		sig0->fillOtVoiceSIG0(65536, ftbl0OtVoiceSIG0);
		deleteOtVoiceSIG0(sig0);
	}
	
	inline void instanceConstants([[maybe_unused]] int sample_rate) {
		fSampleRate = sample_rate;
		fConst0 = std::min<double>(1.92e+05, std::max<double>(1.0, static_cast<double>(fSampleRate)));
		fConst1 = 1.0 / fConst0;
		fConst2 = 4.0 / fConst0;
		fConst3 = 0.25 * fConst0;
		fConst4 = 0.5 * fConst0;
		fConst5 = 0.7 * fConst0;
	}
	
	inline void instanceResetUserInterface() {
		fButton0 = static_cast<float>(0.0);
		fVslider0 = static_cast<float>(0.03);
		fVslider1 = static_cast<float>(0.01);
		fVslider2 = static_cast<float>(0.05);
		fVslider3 = static_cast<float>(0.8);
		fHslider0 = static_cast<float>(0.0);
		fHslider1 = static_cast<float>(1.0);
		fHslider2 = static_cast<float>(4.4e+02);
		fHslider3 = static_cast<float>(0.0);
		fHslider4 = static_cast<float>(1.0);
		fHslider5 = static_cast<float>(4.4e+02);
		fHslider6 = static_cast<float>(0.0);
		fHslider7 = static_cast<float>(0.0);
	}
	
	inline void instanceClear() {
		for (int l0 = 0; l0 < 2; l0 = l0 + 1) {
			iVec0[l0] = 0;
		}
		for (int l1 = 0; l1 < 2; l1 = l1 + 1) {
			iVec1[l1] = 0;
		}
		for (int l2 = 0; l2 < 2; l2 = l2 + 1) {
			iRec1[l2] = 0;
		}
		for (int l3 = 0; l3 < 2; l3 = l3 + 1) {
			fRec0[l3] = 0.0;
		}
		for (int l6 = 0; l6 < 2; l6 = l6 + 1) {
			fRec3[l6] = 0.0;
		}
		for (int l7 = 0; l7 < 2; l7 = l7 + 1) {
			fRec5[l7] = 0.0;
		}
		for (int l8 = 0; l8 < 2; l8 = l8 + 1) {
			fVec3[l8] = 0.0;
		}
		IOTA0 = 0;
		for (int l9 = 0; l9 < 4096; l9 = l9 + 1) {
			fVec4[l9] = 0.0;
		}
		for (int l10 = 0; l10 < 2; l10 = l10 + 1) {
			fRec4[l10] = 0.0;
		}
		for (int l11 = 0; l11 < 2; l11 = l11 + 1) {
			fRec6[l11] = 0.0;
		}
		for (int l12 = 0; l12 < 2; l12 = l12 + 1) {
			fRec8[l12] = 0.0;
		}
		for (int l13 = 0; l13 < 2; l13 = l13 + 1) {
			fRec10[l13] = 0.0;
		}
		for (int l14 = 0; l14 < 2; l14 = l14 + 1) {
			fVec5[l14] = 0.0;
		}
		for (int l15 = 0; l15 < 4096; l15 = l15 + 1) {
			fVec6[l15] = 0.0;
		}
		for (int l16 = 0; l16 < 2; l16 = l16 + 1) {
			fRec9[l16] = 0.0;
		}
		for (int l17 = 0; l17 < 2; l17 = l17 + 1) {
			fRec11[l17] = 0.0;
		}
		for (int l18 = 0; l18 < 2; l18 = l18 + 1) {
			iRec13[l18] = 0;
		}
		for (int l19 = 0; l19 < 4; l19 = l19 + 1) {
			fRec14[l19] = 0.0;
		}
	}
	
	inline void init([[maybe_unused]] int sample_rate) {
		classInit(sample_rate);
		instanceInit(sample_rate);
	}
	
	inline void instanceInit([[maybe_unused]] int sample_rate) {
		instanceConstants(sample_rate);
		instanceResetUserInterface();
		instanceClear();
	}
		
	inline int getSampleRate() {
		return fSampleRate;
	}
	
	inline void buildUserInterface(UI* ui_interface) {
		ui_interface->openVerticalBox("Voice");
		ui_interface->declare(0, "0", "");
		ui_interface->openHorizontalBox("Vco");
		ui_interface->declare(&fHslider1, "1", "");
		ui_interface->declare(&fHslider1, "style", "knob");
		ui_interface->addHorizontalSlider("WaveForm1", &fHslider1, float(1.0), float(0.0), float(7.0), float(1.0));
		ui_interface->declare(&fHslider4, "2", "");
		ui_interface->declare(&fHslider4, "style", "knob");
		ui_interface->addHorizontalSlider("WaveForm2", &fHslider4, float(1.0), float(0.0), float(7.0), float(1.0));
		ui_interface->declare(&fHslider2, "3", "");
		ui_interface->declare(&fHslider2, "style", "knob");
		ui_interface->addHorizontalSlider("Freq1", &fHslider2, float(4.4e+02), float(6e+01), float(1e+04), float(1.0));
		ui_interface->declare(&fHslider5, "3", "");
		ui_interface->declare(&fHslider5, "style", "knob");
		ui_interface->addHorizontalSlider("Freq2", &fHslider5, float(4.4e+02), float(6e+01), float(1e+04), float(1.0));
		ui_interface->closeBox();
		ui_interface->declare(0, "10", "");
		ui_interface->openHorizontalBox("Mixer");
		ui_interface->declare(&fHslider0, "11", "");
		ui_interface->declare(&fHslider0, "style", "knob");
		ui_interface->addHorizontalSlider("Osc1", &fHslider0, float(0.0), float(0.0), float(1.0), float(0.01));
		ui_interface->declare(&fHslider3, "12", "");
		ui_interface->declare(&fHslider3, "style", "knob");
		ui_interface->addHorizontalSlider("Osc2", &fHslider3, float(0.0), float(0.0), float(1.0), float(0.01));
		ui_interface->declare(&fHslider6, "13", "");
		ui_interface->declare(&fHslider6, "style", "knob");
		ui_interface->addHorizontalSlider("White", &fHslider6, float(0.0), float(0.0), float(1.0), float(0.01));
		ui_interface->declare(&fHslider7, "14", "");
		ui_interface->declare(&fHslider7, "style", "knob");
		ui_interface->addHorizontalSlider("Pink", &fHslider7, float(0.0), float(0.0), float(1.0), float(0.01));
		ui_interface->closeBox();
		ui_interface->declare(0, "20", "");
		ui_interface->openHorizontalBox("Vca");
		ui_interface->declare(&fVslider1, "21", "");
		ui_interface->declare(&fVslider1, "format", "%.3fs");
		ui_interface->declare(&fVslider1, "style", "knob");
		ui_interface->addVerticalSlider("Attack", &fVslider1, float(0.01), float(0.0), float(1e+01), float(0.1));
		ui_interface->declare(&fVslider2, "22", "");
		ui_interface->declare(&fVslider2, "format", "%.3fs");
		ui_interface->declare(&fVslider2, "style", "knob");
		ui_interface->addVerticalSlider("Decay", &fVslider2, float(0.05), float(0.0), float(1e+01), float(0.1));
		ui_interface->declare(&fVslider3, "23", "");
		ui_interface->declare(&fVslider3, "format", "%.2f");
		ui_interface->declare(&fVslider3, "style", "knob");
		ui_interface->addVerticalSlider("Sustain", &fVslider3, float(0.8), float(0.0), float(1.0), float(1.0));
		ui_interface->declare(&fVslider0, "24", "");
		ui_interface->declare(&fVslider0, "format", "%.3fs");
		ui_interface->declare(&fVslider0, "style", "knob");
		ui_interface->addVerticalSlider("Release", &fVslider0, float(0.03), float(0.0), float(1e+01), float(0.1));
		ui_interface->declare(&fButton0, "25", "");
		ui_interface->addButton("Gate", &fButton0);
		ui_interface->closeBox();
		ui_interface->closeBox();
	}
	
	inline void compute(int count, float** inputs, float** outputs) {
		float* output0 = outputs[0];
		int iSlow0 = static_cast<double>(fButton0) > 0.0;
		double fSlow1 = static_cast<double>(fVslider0);
		double fSlow2 = static_cast<double>(fVslider1);
		int iSlow3 = static_cast<int>(fConst0 * fSlow2);
		double fSlow4 = static_cast<double>(fVslider2);
		double fSlow5 = static_cast<double>(iSlow0);
		double fSlow6 = static_cast<double>(fVslider3) * fSlow5;
		double fSlow7 = static_cast<double>(fHslider0);
		double fSlow8 = static_cast<double>(fHslider1);
		int iSlow9 = fSlow8 >= 4.0;
		int iSlow10 = fSlow8 >= 2.0;
		int iSlow11 = fSlow8 >= 1.0;
		double fSlow12 = static_cast<double>(fHslider2);
		double fSlow13 = fConst1 * fSlow12;
		int iSlow14 = fSlow8 >= 3.0;
		double fSlow15 = fConst2 * fSlow12;
		double fSlow16 = std::max<double>(fSlow12, 23.44894968246214);
		double fSlow17 = std::max<double>(2e+01, std::fabs(fSlow16));
		double fSlow18 = fConst3 / fSlow17;
		double fSlow19 = fConst1 * fSlow17;
		double fSlow20 = std::max<double>(0.0, std::min<double>(2047.0, fConst4 / fSlow16));
		double fSlow21 = std::floor(fSlow20);
		double fSlow22 = fSlow21 + (1.0 - fSlow20);
		int iSlow23 = static_cast<int>(fSlow20);
		double fSlow24 = fSlow20 - fSlow21;
		int iSlow25 = iSlow23 + 1;
		double fSlow26 = std::max<double>(2.220446049250313e-16, std::fabs(fSlow12));
		double fSlow27 = fConst1 * fSlow26;
		double fSlow28 = 1.0 - fConst0 / fSlow26;
		int iSlow29 = fSlow8 >= 6.0;
		int iSlow30 = fSlow8 >= 5.0;
		double fSlow31 = std::max<double>(0.0, std::min<double>(2047.0, fConst5 / fSlow16));
		double fSlow32 = std::floor(fSlow31);
		double fSlow33 = fSlow32 + (1.0 - fSlow31);
		int iSlow34 = static_cast<int>(fSlow31);
		double fSlow35 = fSlow31 - fSlow32;
		int iSlow36 = iSlow34 + 1;
		double fSlow37 = static_cast<double>(fHslider3);
		double fSlow38 = static_cast<double>(fHslider4);
		int iSlow39 = fSlow38 >= 4.0;
		int iSlow40 = fSlow38 >= 2.0;
		int iSlow41 = fSlow38 >= 1.0;
		double fSlow42 = static_cast<double>(fHslider5);
		double fSlow43 = fConst1 * fSlow42;
		int iSlow44 = fSlow38 >= 3.0;
		double fSlow45 = fConst2 * fSlow42;
		double fSlow46 = std::max<double>(fSlow42, 23.44894968246214);
		double fSlow47 = std::max<double>(2e+01, std::fabs(fSlow46));
		double fSlow48 = fConst3 / fSlow47;
		double fSlow49 = fConst1 * fSlow47;
		double fSlow50 = std::max<double>(0.0, std::min<double>(2047.0, fConst4 / fSlow46));
		double fSlow51 = std::floor(fSlow50);
		double fSlow52 = fSlow51 + (1.0 - fSlow50);
		int iSlow53 = static_cast<int>(fSlow50);
		double fSlow54 = fSlow50 - fSlow51;
		int iSlow55 = iSlow53 + 1;
		double fSlow56 = std::max<double>(2.220446049250313e-16, std::fabs(fSlow42));
		double fSlow57 = fConst1 * fSlow56;
		double fSlow58 = 1.0 - fConst0 / fSlow56;
		int iSlow59 = fSlow38 >= 6.0;
		int iSlow60 = fSlow38 >= 5.0;
		double fSlow61 = std::max<double>(0.0, std::min<double>(2047.0, fConst5 / fSlow46));
		double fSlow62 = std::floor(fSlow61);
		double fSlow63 = fSlow62 + (1.0 - fSlow61);
		int iSlow64 = static_cast<int>(fSlow61);
		double fSlow65 = fSlow61 - fSlow62;
		int iSlow66 = iSlow64 + 1;
		double fSlow67 = 4.656612875245797e-10 * static_cast<double>(fHslider6);
		double fSlow68 = 4.0 * static_cast<double>(fHslider7);
		for (int i0 = 0; i0 < count; i0 = i0 + 1) {
			iVec0[0] = iSlow0;
			iVec1[0] = 1;
			iRec1[0] = iSlow0 * (iRec1[1] + 1);
			int iTemp0 = iSlow0 - iVec0[1];
			int iTemp1 = (iRec1[0] < iSlow3) | (iTemp0 * (iTemp0 > 0));
			double fTemp2 = 0.1447178002894356 * ((iSlow0) ? ((iTemp1) ? fSlow2 : fSlow4) : fSlow1);
			int iTemp3 = std::fabs(fTemp2) < 2.220446049250313e-16;
			double fTemp4 = ((iTemp3) ? 0.0 : std::exp(-(fConst1 / ((iTemp3) ? 1.0 : fTemp2))));
			fRec0[0] = (1.0 - fTemp4) * ((iSlow0) ? ((iTemp1) ? fSlow5 : fSlow6) : 0.0) + fTemp4 * fRec0[1];
			int iTemp5 = 1 - iVec1[1];
			double fTemp6 = ((iTemp5) ? 0.0 : fSlow13 + fRec3[1]);
			fRec3[0] = fTemp6 - std::floor(fTemp6);
			double fTemp7 = static_cast<double>(iVec1[1]);
			double fTemp8 = ((iTemp5) ? 0.0 : fSlow19 + fRec5[1]);
			fRec5[0] = fTemp8 - std::floor(fTemp8);
			double fTemp9 = OtVoice_faustpower2_f(2.0 * fRec5[0] + -1.0);
			fVec3[0] = fTemp9;
			double fTemp10 = fSlow18 * fTemp7 * (fTemp9 - fVec3[1]);
			fVec4[IOTA0 & 4095] = fTemp10;
			double fTemp11 = fSlow22 * fVec4[(IOTA0 - iSlow23) & 4095] + fSlow24 * fVec4[(IOTA0 - iSlow25) & 4095];
			fRec4[0] = 0.999 * fRec4[1] + fTemp10 - fTemp11;
			double fTemp12 = fSlow15 * fRec4[0];
			double fTemp13 = fSlow27 + fRec6[1] + -1.0;
			int iTemp14 = fTemp13 < 0.0;
			double fTemp15 = fSlow27 + fRec6[1];
			fRec6[0] = ((iTemp14) ? fTemp15 : fTemp13);
			double fRec7 = ((iTemp14) ? fTemp15 : fSlow27 + fRec6[1] + fSlow28 * fTemp13);
			double fTemp16 = 2.0 * fRec7;
			double fTemp17 = ((iTemp5) ? 0.0 : fSlow43 + fRec8[1]);
			fRec8[0] = fTemp17 - std::floor(fTemp17);
			double fTemp18 = ((iTemp5) ? 0.0 : fSlow49 + fRec10[1]);
			fRec10[0] = fTemp18 - std::floor(fTemp18);
			double fTemp19 = OtVoice_faustpower2_f(2.0 * fRec10[0] + -1.0);
			fVec5[0] = fTemp19;
			double fTemp20 = fSlow48 * fTemp7 * (fTemp19 - fVec5[1]);
			fVec6[IOTA0 & 4095] = fTemp20;
			double fTemp21 = fSlow52 * fVec6[(IOTA0 - iSlow53) & 4095] + fSlow54 * fVec6[(IOTA0 - iSlow55) & 4095];
			fRec9[0] = 0.999 * fRec9[1] + fTemp20 - fTemp21;
			double fTemp22 = fSlow45 * fRec9[0];
			double fTemp23 = fSlow57 + fRec11[1] + -1.0;
			int iTemp24 = fTemp23 < 0.0;
			double fTemp25 = fSlow57 + fRec11[1];
			fRec11[0] = ((iTemp24) ? fTemp25 : fTemp23);
			double fRec12 = ((iTemp24) ? fTemp25 : fSlow57 + fRec11[1] + fSlow58 * fTemp23);
			double fTemp26 = 2.0 * fRec12;
			iRec13[0] = 1103515245 * iRec13[1] + 12345;
			double fTemp27 = static_cast<double>(iRec13[0]);
			fRec14[0] = 0.5221894 * fRec14[3] + 4.656612875245797e-10 * fTemp27 + 2.494956002 * fRec14[1] - 2.017265875 * fRec14[2];
			output0[i0] = static_cast<float>(0.25 * fRec0[0] * (fSlow7 * ((iSlow9) ? ((iSlow29) ? fTemp10 - (fSlow33 * fVec4[(IOTA0 - iSlow34) & 4095] + fSlow35 * fVec4[(IOTA0 - iSlow36) & 4095]) : ((iSlow30) ? fTemp10 - fTemp11 : fTemp16 + -1.0)) : ((iSlow10) ? ((iSlow14) ? 0.6666666666666666 * (fTemp16 + fTemp12 + -1.0) : fTemp12) : ((iSlow11) ? ftbl0OtVoiceSIG0[std::max<int>(0, std::min<int>(static_cast<int>(65536.0 * fRec3[0]), 65535))] : 0.0))) + fSlow37 * ((iSlow39) ? ((iSlow59) ? fTemp20 - (fSlow63 * fVec6[(IOTA0 - iSlow64) & 4095] + fSlow65 * fVec6[(IOTA0 - iSlow66) & 4095]) : ((iSlow60) ? fTemp20 - fTemp21 : fTemp26 + -1.0)) : ((iSlow40) ? ((iSlow44) ? 0.6666666666666666 * (fTemp26 + fTemp22 + -1.0) : fTemp22) : ((iSlow41) ? ftbl0OtVoiceSIG0[std::max<int>(0, std::min<int>(static_cast<int>(65536.0 * fRec8[0]), 65535))] : 0.0))) + fSlow67 * fTemp27 + fSlow68 * (0.049922035 * fRec14[0] + 0.050612699 * fRec14[2] - (0.095993537 * fRec14[1] + 0.004408786 * fRec14[3]))));
			iVec0[1] = iVec0[0];
			iVec1[1] = iVec1[0];
			iRec1[1] = iRec1[0];
			fRec0[1] = fRec0[0];
			fRec3[1] = fRec3[0];
			fRec5[1] = fRec5[0];
			fVec3[1] = fVec3[0];
			IOTA0 = IOTA0 + 1;
			fRec4[1] = fRec4[0];
			fRec6[1] = fRec6[0];
			fRec8[1] = fRec8[0];
			fRec10[1] = fRec10[0];
			fVec5[1] = fVec5[0];
			fRec9[1] = fRec9[0];
			fRec11[1] = fRec11[0];
			iRec13[1] = iRec13[0];
			for (int j0 = 3; j0 > 0; j0 = j0 - 1) {
				fRec14[j0] = fRec14[j0 - 1];
			}
		}
	}

	inline void calculateSizes() {
		auto knobWidth = OtUi::knobWidth();
		auto knobHeight = OtUi::knobHeight();
		auto spacing = ImGui::GetStyle().ItemSpacing;
		auto frame = ImGui::GetFrameHeightWithSpacing();
		float width1 = 0.0f;
		float height1 = 0.0f;
		float width2 = 0.0f;
		float height2 = 0.0f;
		width2 += knobWidth;
		height2 = std::max(height2, knobHeight);
		width2 += spacing.x;
		width2 += knobWidth;
		height2 = std::max(height2, knobHeight);
		width2 += spacing.x;
		width2 += knobWidth;
		height2 = std::max(height2, knobHeight);
		width2 += spacing.x;
		width2 += knobWidth;
		height2 = std::max(height2, knobHeight);
		width1 = std::max(width1, width2);
		height1 += height2;
		float width3 = 0.0f;
		float height3 = 0.0f;
		width3 += knobWidth;
		height3 = std::max(height3, knobHeight);
		width3 += spacing.x;
		width3 += knobWidth;
		height3 = std::max(height3, knobHeight);
		width3 += spacing.x;
		width3 += knobWidth;
		height3 = std::max(height3, knobHeight);
		width3 += spacing.x;
		width3 += knobWidth;
		height3 = std::max(height3, knobHeight);
		width1 = std::max(width1, width3);
		height1 += height3;
		float width4 = 0.0f;
		float height4 = 0.0f;
		width4 += knobWidth;
		height4 = std::max(height4, knobHeight);
		width4 += spacing.x;
		width4 += knobWidth;
		height4 = std::max(height4, knobHeight);
		width4 += spacing.x;
		width4 += knobWidth;
		height4 = std::max(height4, knobHeight);
		width4 += spacing.x;
		width4 += knobWidth;
		height4 = std::max(height4, knobHeight);
		width4 += spacing.x;
		width4 += ImGui::CalcTextSize("Gate").x + ImGui::GetStyle().FramePadding.x * 2.0f;
		height4 = std::max(height4, frame);
		width1 = std::max(width1, width4);
		height1 += height4;
		width = width1;
		height = height1;
		initialized = true;
	}

	inline bool renderUI() {
		if (!initialized) {
			calculateSizes();
		}

		bool changed = false;
		ImGui::BeginGroup();
		ImGui::PushID("Voice");
		ImGui::BeginGroup();
		ImGui::PushID("Vco");
		changed |= editVcoWaveForm1();
		ImGui::SameLine();
		changed |= editVcoWaveForm2();
		ImGui::SameLine();
		changed |= editVcoFreq1();
		ImGui::SameLine();
		changed |= editVcoFreq2();
		ImGui::PopID();
		ImGui::EndGroup();
		ImGui::BeginGroup();
		ImGui::PushID("Mixer");
		changed |= editMixerOsc1();
		ImGui::SameLine();
		changed |= editMixerOsc2();
		ImGui::SameLine();
		changed |= editMixerWhite();
		ImGui::SameLine();
		changed |= editMixerPink();
		ImGui::PopID();
		ImGui::EndGroup();
		ImGui::BeginGroup();
		ImGui::PushID("Vca");
		changed |= editVcaAttack();
		ImGui::SameLine();
		changed |= editVcaDecay();
		ImGui::SameLine();
		changed |= editVcaSustain();
		ImGui::SameLine();
		changed |= editVcaRelease();
		ImGui::SameLine();
		changed |= editVcaGate();
		ImGui::PopID();
		ImGui::EndGroup();
		ImGui::PopID();
		ImGui::EndGroup();
		return changed;
	}

	inline float getRenderWidth() {
		if (!initialized) {
			calculateSizes();
		}

		return width;
	}

	inline float getRenderHeight() {
		if (!initialized) {
			calculateSizes();
		}

		return height;
	}

	struct Parameters {
		float vcoWaveForm1 = 1.0f;
		float vcoWaveForm2 = 1.0f;
		float vcoFreq1 = 440.0f;
		float vcoFreq2 = 440.0f;
		float mixerOsc1 = 0.0f;
		float mixerOsc2 = 0.0f;
		float mixerWhite = 0.0f;
		float mixerPink = 0.0f;
		float vcaAttack = 0.01f;
		float vcaDecay = 0.05f;
		float vcaSustain = 0.8f;
		float vcaRelease = 0.03f;
		float vcaGate = 0.0f;
	};

	inline void setParameters([[maybe_unused]] const Parameters& parameters) {
		fHslider1 = parameters.vcoWaveForm1;
		fHslider4 = parameters.vcoWaveForm2;
		fHslider2 = parameters.vcoFreq1;
		fHslider5 = parameters.vcoFreq2;
		fHslider0 = parameters.mixerOsc1;
		fHslider3 = parameters.mixerOsc2;
		fHslider6 = parameters.mixerWhite;
		fHslider7 = parameters.mixerPink;
		fVslider1 = parameters.vcaAttack;
		fVslider2 = parameters.vcaDecay;
		fVslider3 = parameters.vcaSustain;
		fVslider0 = parameters.vcaRelease;
		fButton0 = parameters.vcaGate;
	}

	inline Parameters getParameters() {
		Parameters parameters;
		parameters.vcoWaveForm1 = fHslider1;
		parameters.vcoWaveForm2 = fHslider4;
		parameters.vcoFreq1 = fHslider2;
		parameters.vcoFreq2 = fHslider5;
		parameters.mixerOsc1 = fHslider0;
		parameters.mixerOsc2 = fHslider3;
		parameters.mixerWhite = fHslider6;
		parameters.mixerPink = fHslider7;
		parameters.vcaAttack = fVslider1;
		parameters.vcaDecay = fVslider2;
		parameters.vcaSustain = fVslider3;
		parameters.vcaRelease = fVslider0;
		parameters.vcaGate = fButton0;
		return parameters;
	}

	inline void iterateParameters([[maybe_unused]] std::function<void(const char*, float*, float)> callback) override {
		callback("vcoWaveForm1", &fHslider1, 1.0f);
		callback("vcoWaveForm2", &fHslider4, 1.0f);
		callback("vcoFreq1", &fHslider2, 440.0f);
		callback("vcoFreq2", &fHslider5, 440.0f);
		callback("mixerOsc1", &fHslider0, 0.0f);
		callback("mixerOsc2", &fHslider3, 0.0f);
		callback("mixerWhite", &fHslider6, 0.0f);
		callback("mixerPink", &fHslider7, 0.0f);
		callback("vcaAttack", &fVslider1, 0.01f);
		callback("vcaDecay", &fVslider2, 0.05f);
		callback("vcaSustain", &fVslider3, 0.8f);
		callback("vcaRelease", &fVslider0, 0.03f);
		callback("vcaGate", &fButton0, 0.0f);
	}

	inline bool editVcoWaveForm1() { return OtUi::knob("WaveForm1", &fHslider1, 0.0f, 7.0f, "%.0f"); }
	inline bool editVcoWaveForm2() { return OtUi::knob("WaveForm2", &fHslider4, 0.0f, 7.0f, "%.0f"); }
	inline bool editVcoFreq1() { return OtUi::knob("Freq1", &fHslider2, 60.0f, 10000.0f, "%.0f"); }
	inline bool editVcoFreq2() { return OtUi::knob("Freq2", &fHslider5, 60.0f, 10000.0f, "%.0f"); }
	inline bool editMixerOsc1() { return OtUi::knob("Osc1", &fHslider0, 0.0f, 1.0f, "%.2f"); }
	inline bool editMixerOsc2() { return OtUi::knob("Osc2", &fHslider3, 0.0f, 1.0f, "%.2f"); }
	inline bool editMixerWhite() { return OtUi::knob("White", &fHslider6, 0.0f, 1.0f, "%.2f"); }
	inline bool editMixerPink() { return OtUi::knob("Pink", &fHslider7, 0.0f, 1.0f, "%.2f"); }
	inline bool editVcaAttack() { return OtUi::knob("Attack", &fVslider1, 0.0f, 10.0f, "%.3fs"); }
	inline bool editVcaDecay() { return OtUi::knob("Decay", &fVslider2, 0.0f, 10.0f, "%.3fs"); }
	inline bool editVcaSustain() { return OtUi::knob("Sustain", &fVslider3, 0.0f, 1.0f, "%.2f"); }
	inline bool editVcaRelease() { return OtUi::knob("Release", &fVslider0, 0.0f, 10.0f, "%.3fs"); }
	inline bool editVcaGate() { ImGui::Button("Gate"); return ImGui::IsItemActive() ? 1.0f : 0.0f; }

	inline void setVcoWaveForm1(float value) { fHslider1 = value; }
	inline void setVcoWaveForm2(float value) { fHslider4 = value; }
	inline void setVcoFreq1(float value) { fHslider2 = value; }
	inline void setVcoFreq2(float value) { fHslider5 = value; }
	inline void setMixerOsc1(float value) { fHslider0 = value; }
	inline void setMixerOsc2(float value) { fHslider3 = value; }
	inline void setMixerWhite(float value) { fHslider6 = value; }
	inline void setMixerPink(float value) { fHslider7 = value; }
	inline void setVcaAttack(float value) { fVslider1 = value; }
	inline void setVcaDecay(float value) { fVslider2 = value; }
	inline void setVcaSustain(float value) { fVslider3 = value; }
	inline void setVcaRelease(float value) { fVslider0 = value; }
	inline void setVcaGate(float value) { fButton0 = value; }

	inline float getVcoWaveForm1() { return fHslider1; }
	inline float getVcoWaveForm2() { return fHslider4; }
	inline float getVcoFreq1() { return fHslider2; }
	inline float getVcoFreq2() { return fHslider5; }
	inline float getMixerOsc1() { return fHslider0; }
	inline float getMixerOsc2() { return fHslider3; }
	inline float getMixerWhite() { return fHslider6; }
	inline float getMixerPink() { return fHslider7; }
	inline float getVcaAttack() { return fVslider1; }
	inline float getVcaDecay() { return fVslider2; }
	inline float getVcaSustain() { return fVslider3; }
	inline float getVcaRelease() { return fVslider0; }
	inline float getVcaGate() { return fButton0; }

private:
	bool initialized = false;
	float width;
	float height;
};
