#	ObjectTalk Scripting Language
#	Copyright (c) 1993-2024 Johan A. Goossens. All rights reserved.
#
#	This work is licensed under the terms of the MIT license.
#	For a copy, see <https://opensource.org/licenses/MIT>.

FROM alpine:latest

RUN apk add --no-cache \
	gdb \
	cmake \
	alpine-sdk \
	linux-headers

WORKDIR /ot
